import { useState } from "react";
import { LanguageSwitcher } from "./locale.jsx";
import { CanadianFrenchProcurement } from "./CanadianFrenchProcurement.jsx";

const WHATSAPP_URL = import.meta.env.VITE_WHATSAPP_URL ?? "https://wa.me/8617759190848";
const Arrow = () => <span aria-hidden="true">↗</span>;

function Header({ active }) {
  const [menu,setMenu]=useState(false);
  return <header className={`zhoni-header fr-ca-header ${menu?"zhoni-header-open":""}`}><a className="zhoni-wordmark" href="/fr-ca/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><button className="zhoni-menu" onClick={()=>setMenu(value=>!value)} aria-expanded={menu}>{menu?"FERMER":"MENU"}</button><nav aria-label="Navigation principale"><a className={active==="products"?"active":""} href="/fr-ca/products/">PRODUITS</a><a className={active==="solutions"?"active":""} href="/fr-ca/solutions/">SOLUTIONS</a><a className={active==="guides"?"active":""} href="/fr-ca/guides/">GUIDES D'ACHAT</a><a href="/fr-ca/our-process/">PROCESSUS</a><a href="/fr-ca/faq/">FAQ</a><a href="/fr-ca/about/">À PROPOS</a></nav><LanguageSwitcher/><a className="zhoni-header-cta" href="/fr-ca/request-a-quote/">DEMANDER UNE SOUMISSION <Arrow/></a></header>;
}

function Footer(){return <footer className="site-footer"><div className="site-footer-main"><a className="zhoni-wordmark" href="/fr-ca/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><div className="site-footer-copy"><p>Articles et cadeaux de golf personnalisés pour clubs, tournois, entreprises et marques.</p><span>ENSEMBLES-CADEAUX · COUVRE-BÂTONS · CASQUETTES · SERVIETTES · ACCESSOIRES · EMBALLAGES</span><div className="site-footer-contact"><b>CONTACT DIRECT</b><a href="mailto:sales@zhonigolf.com">sales@zhonigolf.com</a><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer">WhatsApp +86 177 5919 0848 <Arrow/></a></div></div><nav aria-label="Navigation de pied de page"><a href="/fr-ca/products/">Produits</a><a href="/fr-ca/solutions/">Solutions</a><a href="/fr-ca/guides/">Guides d'achat</a><a href="/fr-ca/our-process/">Notre processus</a><a href="/fr-ca/faq/">FAQ</a><a href="/fr-ca/about/">À propos</a><a href="/fr-ca/request-a-quote/">Soumission <Arrow/></a></nav></div><div className="site-footer-base"><span>ZHONI · CUSTOM GOLF MERCHANDISE</span><span>Entité exploitante : Xiamen Jindongyu Trading Co., Ltd.</span></div></footer>}

const categoryContent={
  frCaHeadcovers:{eyebrow:"COUVRE-BÂTONS DE GOLF PERSONNALISÉS",brief:"Couvre-bâtons de golf personnalisés",title:"Protéger les bâtons.\nFaire vivre la marque.",intro:"Développez des couvre-bâtons pour bois de départ, bois d'allée, hybrides et fers droits selon l'ajustement, la matière, l'identité visuelle et la composition de l'ensemble.",image:"/assets/images/zhoni-product-headcovers-v3.png",alt:"Couvre-bâtons de golf personnalisés vert forêt avec monogramme Z doré",rows:[["Types","Bois de départ · bois d'allée · hybride · fer droit lame ou maillet"],["Matières","PU, similicuir, tissu, tricot et constructions mixtes"],["Marquage","Broderie, appliqué, débossage, écusson et étiquette"],["Points à valider","Ajustement, ouverture, doublure, coutures, position du logo et repères de série"]],checklist:["Types de bâtons et répartition des quantités","Références de matière et de toucher","Logo vectoriel et couleurs de marque","Emballage individuel ou en ensemble","Date de réception et lieu de livraison"]},
  frCaCaps:{eyebrow:"CASQUETTES ET VISIÈRES DE GOLF",brief:"Casquettes et visières de golf personnalisées",title:"Une identité de marque\nqui dépasse le parcours.",intro:"Planifiez des casquettes et visières pour tournois, programmes de membres et événements d'entreprise selon l'ajustement, le climat, le tissu et la méthode de marquage.",image:"/assets/images/zhoni-product-caps-v3.png",alt:"Casquette et visière de golf personnalisées vert forêt avec logo Z doré",rows:[["Modèles","Casquette structurée ou souple · performance · visière · filet"],["Tissus","Sergé de coton, polyester, tissu technique et filet"],["Marquage","Broderie à plat ou 3D, écusson tissé ou caoutchouc, logos latéral et arrière"],["Points à valider","Couronne, visière, bandeau absorbant, fermeture et plage de tailles"]],checklist:["Profil des personnes et saison d'utilisation","Style de casquette ou de visière","Performance du tissu et couleurs","Emplacements du logo à l'avant, au côté et à l'arrière","Quantité, échéance et destination"]},
  frCaTowels:{eyebrow:"SERVIETTES DE GOLF PERSONNALISÉES",brief:"Serviettes de golf personnalisées",title:"Une utilité réelle,\navec les bons détails de marque.",intro:"Planifiez le tissu gaufré, la broderie, le mousqueton et le système magnétique selon l'utilisation sur le parcours et la composition du cadeau.",image:"/assets/images/zhoni-product-magnetic-towel-v4.png",alt:"Serviette de golf magnétique personnalisée avec broderie Z dorée",rows:[["Formats","Gaufrée · magnétique · avec mousqueton · pour ensemble-cadeau"],["Matières","Microfibre gaufrée, coton et solutions adaptées au projet"],["Marquage","Broderie, étiquette tissée, impression et carte d'emballage"],["Points à valider","Dimensions, grammage, bordure, aimant ou mousqueton et tenue après lavage"]],checklist:["Usage prévu et dimensions souhaitées","Références de tissu et de couleur","Taille et position de la broderie","Besoin d'un aimant ou d'un mousqueton","Emballage individuel ou composition en ensemble"]},
  frCaAccessories:{eyebrow:"ACCESSOIRES DE GOLF PERSONNALISÉS",brief:"Accessoires de golf personnalisés",title:"Une expérience de marque claire,\nmême dans les petits formats.",intro:"Composez marque-balles, relève-pitchs, pinces à casquette, étiquettes de sac et pochettes selon leur rôle dans un ensemble de tournoi, un cadeau d'entreprise ou un programme de club.",image:"/assets/images/zhoni-product-accessories-v3.png",alt:"Pochette et étiquette de sac de golf personnalisées avec marque Z dorée",rows:[["Produits","Marque-balle · relève-pitch · pince à casquette · étiquette de sac · pochette"],["Matières","Métal, PU, textile et combinaisons selon le produit"],["Marquage","Gravure, émail, débossage, broderie et impression"],["Points à valider","Dimensions, placage, bords, assemblage des pièces et emballage individuel"]],checklist:["Destinataires et objectif","Combinaison de produits et quantités","Finition du métal ou orientation de matière","Épaisseur des traits et couleurs du logo","Besoin d'un emballage en ensemble"]},
  frCaPackaging:{eyebrow:"EMBALLAGES DE GOLF PERSONNALISÉS",brief:"Emballages de golf personnalisés",title:"Compléter le projet\njusqu'au moment de remise.",intro:"Concevez boîtes-cadeaux, calages, fourreaux, cartes et protection de transport selon la composition des produits, l'expérience de marque et les conditions réelles d'expédition.",image:"/assets/images/zhoni-product-packaging-v3.png",alt:"Boîte-cadeau de golf personnalisée avec calage et logo Z doré",rows:[["Structures","Boîte pliante · boîte rigide · fourreau · calage"],["Finitions","Impression, dorure, gaufrage ou débossage et étiquette"],["Aménagement intérieur","EVA, carton, textile, protection et maintien des produits"],["Points à valider","Dimensions, ordre d'ouverture, protection, efficacité des cartons et mode de livraison"]],checklist:["Liste finale des produits dans la boîte","Dimensions et priorité de présentation","Couleurs de marque et fichiers de logo","Carte, fourreau et étiquettes requis","Destination et exigences des cartons extérieurs"]},
};

function CategoryPage({pageKey}){const c=categoryContent[pageKey];return <main className="zhoni-page category-page fr-ca-page"><Header active="products"/><section className="category-hero"><aside className="category-rail" aria-hidden="true"><strong>Z</strong><span>CUSTOM GOLF PRODUCTS</span></aside><div className="category-intro"><p>{c.eyebrow}</p><h1>{c.title.split("\n").map((line,index)=><span key={line}>{line}{index===0&&<br/>}</span>)}</h1><p>{c.intro}</p><a href={`/fr-ca/request-a-quote/?product=${encodeURIComponent(c.brief)}`}>PRÉSENTER CE PRODUIT <Arrow/></a><small>CLUBS · TOURNOIS · ENTREPRISES · MARQUES</small></div><img src={c.image} alt={c.alt}/></section><section className="guide-table"><table><thead><tr><th>POINT À ÉVALUER</th><th>ORIENTATION PRATIQUE</th></tr></thead><tbody>{c.rows.map(row=><tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td></tr>)}</tbody></table></section><section className="guide-decision"><div><p>PRÉPARATION DU PROJET</p><h2>Aligner les spécifications avant de comparer les prix.</h2><p>La quantité minimale, le prix, l'échantillonnage et le délai dépendent de la construction, de la personnalisation, du volume, de l'emballage et de la destination. Ces renseignements rendent l'évaluation plus réaliste.</p></div><aside><p>LISTE DE L'ACHETEUR</p><h3>À préparer dans le cahier des charges</h3><ul>{c.checklist.map(item=><li key={item}>{item}</li>)}</ul></aside></section><section className="guide-products"><p>PARCOURS CONNEXES</p><h2>Passer du produit au projet concret.</h2><div><a href="/fr-ca/products/">Tous les produits<Arrow/></a><a href="/fr-ca/solutions/">Solutions par projet<Arrow/></a><a href="/fr-ca/our-process/">Notre processus<Arrow/></a><a href="/fr-ca/request-a-quote/">Demander une soumission<Arrow/></a></div></section><section className="guide-close"><div><p>PRÊT À ÉVALUER LE PROJET?</p><h2>Partagez le produit, la quantité et la date cible.</h2><a href={`/fr-ca/request-a-quote/?product=${encodeURIComponent(c.brief)}`}>ENVOYER LE CAHIER DES CHARGES <Arrow/></a></div><img src={c.image} alt={c.alt}/></section><Footer/></main>}

const solutionContent={
  frCaTournamentGifts:{label:"CADEAUX DE TOURNOI ET SACS DE BIENVENUE",title:"Des cadeaux adaptés au rôle de chaque participant.",intro:"Les cadeaux des joueurs, des commanditaires, des invités VIP et des gagnants répondent à des objectifs différents, même au sein du même tournoi.",image:"/assets/images/zhoni-golf-tournament-gift-delivery-v2.png",solution:"golf-tournament-gifts",steps:[["01","Définir les groupes","Distinguer les participants, commanditaires, invités VIP, équipe organisatrice et gagnants."],["02","Composer les produits","Choisir selon le moment d'utilisation, l'orientation budgétaire et la facilité de distribution."],["03","Coordonner marque et emballage","Évaluer ensemble le logo de l'événement, la visibilité des commanditaires et la remise sur place."],["04","Planifier à rebours","Prévoir validation, échantillonnage, production, emballage et livraison à partir de la date du tournoi."]],products:"Serviettes magnétiques, casquettes, marque-balles, relève-pitchs, pochettes et boîtes-cadeaux peuvent être réunis selon le rôle de chaque groupe."},
  frCaCorporateGifts:{label:"CADEAUX DE GOLF D'ENTREPRISE",title:"Des cadeaux pensés selon la relation et le moment de remise.",intro:"Pour la reconnaissance des clients, les récompenses d'équipe, les événements de partenaires et les campagnes de marque, commencez par définir le destinataire et le niveau de présentation.",image:"/assets/images/zhoni-custom-golf-packaging-v2.png",solution:"corporate-golf-gifts",steps:[["01","Identifier les destinataires","Distinguer clients, cadres, équipes, partenaires et participants à l'événement."],["02","Définir le niveau du cadeau","Choisir un article pratique distinctif ou un ensemble haut de gamme."],["03","Ajuster l'expression de marque","Adapter la taille et la visibilité du logo au produit et à la relation."],["04","Préparer la remise","Confirmer carte-message, emballage individuel, destinations et date de réception."]],products:"Couvre-bâtons, casquettes, serviettes, accessoires métalliques et boîtes personnalisées peuvent former une expérience-cadeau d'entreprise cohérente."},
};

function SolutionDetail({pageKey}){const c=solutionContent[pageKey];return <main className="zhoni-page corporate-page fr-ca-page"><Header active="solutions"/><section className="corporate-hero"><aside className="corporate-rail" aria-hidden="true"><strong>Z</strong><span>GOLF GIFT SOLUTIONS</span></aside><div><p>{c.label}</p><h1>{c.title}</h1><p>{c.intro}</p><a href={`/fr-ca/request-a-quote/?solution=${c.solution}`}>PRÉSENTER LE PROJET <Arrow/></a></div><img src={c.image} alt={c.label}/></section><section className="corporate-ledger"><div><p>PARCOURS DE PLANIFICATION</p>{c.steps.map(([n,t,d])=><article key={n}><b>{n}</b><h2>{t}</h2><p>{d}</p><span>→</span></article>)}</div><aside><p>RENSEIGNEMENTS ESSENTIELS</p><ul><li><b>Destinataires</b><span>Qui recevra les cadeaux et combien de personnes?</span></li><li><b>Échéance</b><span>Date de l'événement ou de réception souhaitée</span></li><li><b>Destination</b><span>Pays, ville et points de distribution</span></li><li><b>Éléments de marque</b><span>Logo, couleurs et images de référence</span></li><li><b>Emballage</b><span>Présentation individuelle ou en ensemble</span></li></ul></aside></section><section className="corporate-closing"><img src="/assets/images/zhoni-golf-product-development-v2.png" alt="Examen du marquage d'articles de golf personnalisés"/><div><p>CADEAUX DE GOLF COORDONNÉS</p><h2>Définir le rôle du cadeau avant de choisir les produits.</h2><p>{c.products}</p><a href="/fr-ca/products/">EXPLORER LES PRODUITS <Arrow/></a></div></section><section className="guide-products"><p>PARCOURS CONNEXES</p><h2>Continuer avec le bon niveau de détail.</h2><div><a href="/fr-ca/products/">Produits personnalisés<Arrow/></a><a href="/fr-ca/custom-golf-packaging/">Emballages personnalisés<Arrow/></a><a href="/fr-ca/our-process/">Notre processus<Arrow/></a><a href={`/fr-ca/request-a-quote/?solution=${c.solution}`}>Demander une soumission<Arrow/></a></div></section><Footer/></main>}

const guides=[
  {key:"gifts",group:"event",label:"CENTRE DE PROJET",title:"Cadeaux de golf personnalisés",copy:"Reliez destinataires, produits, marquage, emballage et livraison dans un même projet.",href:"/fr-ca/custom-golf-gifts/"},
  {key:"headcovers",group:"product",label:"PRODUITS ET PERSONNALISATION",title:"Guide d'achat de couvre-bâtons personnalisés",copy:"Préparez les types de bâtons, l'ajustement, la matière, le logo, l'échantillon et l'emballage.",href:"/fr-ca/guides/custom-golf-headcovers-procurement-guide/"},
  {key:"caps",group:"product",label:"PRODUITS ET PERSONNALISATION",title:"Guide d'achat de casquettes et visières",copy:"Comparez la forme, le tissu, l'ajustement, la fermeture et les emplacements de logo.",href:"/fr-ca/guides/custom-golf-caps-and-visors/"},
  {key:"towels",group:"product",label:"PRODUITS ET PERSONNALISATION",title:"Guide d'achat de serviettes de golf",copy:"Définissez le tissu gaufré, le système magnétique, les dimensions et la broderie.",href:"/fr-ca/guides/custom-golf-towels-procurement-guide/"},
  {key:"packaging",group:"readiness",label:"QUALITÉ ET LIVRAISON",title:"Guide d'achat d'emballages personnalisés",copy:"Évaluez la structure de boîte, le calage, l'impression, la protection et les cartons d'expédition.",href:"/fr-ca/guides/custom-golf-packaging-procurement-guide/"},
  {key:"branding",group:"product",label:"PRODUITS ET PERSONNALISATION",title:"Méthodes de marquage",copy:"Comparez broderie, débossage, impression, écussons et finitions métalliques.",href:"/fr-ca/guides/branding-methods-for-premium-golf-merchandise/"},
  {key:"artwork",group:"product",label:"PRODUITS ET PERSONNALISATION",title:"Préparer les logos et fichiers",copy:"Rassemblez fichiers vectoriels, couleurs, dimensions, positions et références.",href:"/fr-ca/guides/prepare-artwork-for-custom-golf-products/"},
  {key:"moq",group:"procurement",label:"MOQ ET PREMIÈRE COMMANDE",title:"Comprendre les quantités minimales",copy:"Voyez comment produit, matière, couleurs, logo et emballage influencent le MOQ.",href:"/fr-ca/guides/custom-golf-merchandise-moq-explained/"},
  {key:"firstorder",group:"procurement",label:"MOQ ET PREMIÈRE COMMANDE",title:"Préparer une première commande",copy:"Structurez spécifications, quantité, validation, conditions commerciales et destination.",href:"/fr-ca/first-order-guide/"},
  {key:"quote",group:"procurement",label:"MOQ ET PREMIÈRE COMMANDE",title:"Ce qui influence une soumission",copy:"Comparez portée, spécifications, échantillons, emballage et conditions de livraison.",href:"/fr-ca/guides/what-affects-a-custom-golf-merchandise-quote/"},
  {key:"quality",group:"readiness",label:"QUALITÉ ET LIVRAISON",title:"Liste de contrôle qualité",copy:"Contrôlez matières, dimensions, logo, fonctions, emballage et cartons.",href:"/fr-ca/guides/custom-golf-merchandise-quality-checklist/"},
  {key:"delivery",group:"readiness",label:"QUALITÉ ET LIVRAISON",title:"Planifier la date de livraison",copy:"Planifiez à rebours validation, échantillon, production, emballage et transport.",href:"/fr-ca/guides/how-to-plan-a-golf-merchandise-delivery-date/"},
  {key:"export",group:"readiness",label:"QUALITÉ ET LIVRAISON",title:"Qualité, emballage et exportation",copy:"Reliez contrôle, emballage, cartons, destination et conditions de remise.",href:"/fr-ca/quality-packaging-export-readiness/"},
  {key:"postbrief",group:"procurement",label:"MOQ ET PREMIÈRE COMMANDE",title:"Après l'envoi du cahier des charges",copy:"Comprenez la réception, l'évaluation, les questions et la prochaine étape.",href:"/fr-ca/guides/what-happens-after-a-custom-golf-project-brief/"},
];

function GuidesHub(){const [filter,setFilter]=useState("all");return <main className="zhoni-page guides-page fr-ca-page"><Header active="guides"/><section className="guides-hero"><div><p>GUIDES D'ACHAT D'ARTICLES DE GOLF</p><h1>Des décisions plus claires,<br/>avant la soumission.</h1><p>Des guides pratiques pour choisir le produit, préparer les spécifications et comprendre les points qui influencent les quantités minimales, les échantillons, l'emballage et la livraison.</p></div><aside><b>LA PREMIÈRE QUESTION</b><p>Avant de choisir un produit, précisez qui le recevra, à quelle occasion, à quelle date et de quelle façon il sera remis.</p><a href="/fr-ca/request-a-quote/">PRÉSENTER UN PROJET <Arrow/></a></aside></section><section className="guide-filter" aria-label="Filtres des guides d'achat"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>TOUS LES GUIDES</button><button className={filter==="product"?"active":""} onClick={()=>setFilter("product")}>PRODUITS ET MARQUAGE</button><button className={filter==="event"?"active":""} onClick={()=>setFilter("event")}>CADEAUX ET ÉVÉNEMENTS</button><button className={filter==="procurement"?"active":""} onClick={()=>setFilter("procurement")}>MOQ ET PREMIÈRE COMMANDE</button><button className={filter==="readiness"?"active":""} onClick={()=>setFilter("readiness")}>QUALITÉ ET LIVRAISON</button></section><section className="guide-catalog">{guides.filter(guide=>filter==="all"||guide.group===filter).map((guide,index)=><a href={guide.href} key={guide.key}><b>{String(index+1).padStart(2,"0")}</b><span>{guide.label}</span><h2>{guide.title}</h2><p>{guide.copy}</p><em>LIRE LE GUIDE <Arrow/></em></a>)}</section><section className="guide-decision"><div><p>PRÉPARER L'ACHAT</p><h2>Passer du guide aux renseignements propres au projet.</h2><p>Une orientation de produit, une quantité estimée, les éléments de marque, une date cible et une destination permettent d'évaluer plus justement la quantité minimale et la soumission.</p></div><aside><p>CAHIER DES CHARGES COMMUN</p><ul>{["Destinataires et objectif","Produit ou images de référence","Quantité estimée","Date de réception et destination","Logo et attentes d'emballage"].map(item=><li key={item}>{item}</li>)}</ul></aside></section><Footer/></main>}

const articleContent={
  frCaHeadcoversGuide:{label:"COUVRE-BÂTONS PERSONNALISÉS",title:"Six décisions à prendre avant d'acheter des couvre-bâtons",intro:"Un bon cahier des charges relie le type de bâton, l'ajustement, la matière, le marquage, les repères de série et l'emballage — pas seulement l'apparence.",image:"/assets/images/zhoni-product-headcovers-v3.png",rows:[["Composition de la série","Quantités de bois de départ, bois d'allée, hybrides et fers droits"],["Forme et ajustement","Dimensions du bâton, ouverture, longueur et maintien élastique ou magnétique"],["Matière","Toucher, durabilité et compatibilité du logo sur PU, textile ou tricot"],["Marquage","Broderie, appliqué, débossage et position du logo"],["Intérieur et finitions","Doublure, coutures, bordures et numéros de série"],["Emballage","Emballage individuel, boîte d'ensemble et étiquettes"]],checklist:["Quantité estimée par type de bâton","Images de référence de face, profil et dos","Logo vectoriel et valeurs de couleur","Référence de matière ou de toucher","Date de réception et pays de livraison"],faqs:[["La quantité minimale est-elle la même pour tous les couvre-bâtons?","Non. Elle varie selon la forme, la matière, le nombre de couleurs, la méthode de marquage et la composition de la série."],["Un échantillon physique est-il nécessaire?","Il est particulièrement utile lorsqu'une nouvelle construction ou un ajustement précis est requis. Le projet peut prévoir une maquette, un échantillon existant ou un nouvel échantillon."],["Le même visuel peut-il être utilisé pour un bois et un fer droit?","Oui, mais la structure des panneaux et la surface disponible diffèrent. Le dessin doit être adapté à chaque forme plutôt que simplement réduit." ]],product:"/fr-ca/custom-golf-headcovers/",brief:"Couvre-bâtons de golf personnalisés"},
  frCaTowelsGuide:{label:"SERVIETTES DE GOLF PERSONNALISÉES",title:"Choisir ensemble le tissu, les dimensions et le système d'attache",intro:"Une serviette de golf est un outil utilisé plusieurs fois pendant la ronde. Il faut équilibrer absorption, séchage, attache et lisibilité du logo.",image:"/assets/images/zhoni-product-magnetic-towel-v4.png",rows:[["Contexte d'utilisation","Sac de golf, voiturette, sac de bienvenue ou ensemble-cadeau"],["Tissu","Structure gaufrée, grammage, toucher et vitesse de séchage"],["Dimensions","Volume une fois pliée et surface réellement utilisable"],["Attache","Aimant, mousqueton, œillet ou pince séparée"],["Logo","Dimensions, position, couleurs de fil et effet au verso"],["Emballage","Bandeau, sac protecteur, carte ou boîte-cadeau"]],checklist:["Largeur et longueur souhaitées","Couleur du tissu et serviette de référence","Caractéristiques de l'aimant ou du mousqueton","Fichier original du logo à broder","Autres produits à réunir dans l'ensemble"],faqs:[["Que faut-il vérifier pour une serviette magnétique?","Vérifiez la position et la fixation de l'aimant, le point de contact métallique, le poids de la serviette et son usage réel sur une voiturette ou un bâton."],["Une broderie plus grande est-elle toujours préférable?","Non. Une broderie très grande peut réduire la souplesse et ralentir le séchage. Il faut équilibrer visibilité du logo et utilité."],["Peut-on répartir une commande entre plusieurs couleurs?","Cela dépend du tissu, de la méthode de teinture ou des couleurs disponibles, de la quantité totale et de la répartition demandée." ]],product:"/fr-ca/custom-golf-towels/",brief:"Serviettes de golf personnalisées"},
  frCaCapsStyleGuide:{label:"CASQUETTES ET VISIÈRES DE GOLF",title:"Définir les conditions d'utilisation avant de choisir le style",intro:"La structure de la couronne, le tissu, la respirabilité, la fermeture et l'emplacement du logo déterminent ensemble le confort et le résultat visuel.",image:"/assets/images/zhoni-product-caps-v3.png",rows:[["Personnes","Adultes ou juniors, composition du groupe et plage de tailles"],["Forme","Structurée, souple, profil bas ou moyen et visière"],["Conditions","Temps chaud, longue ronde, événement ou usage quotidien"],["Tissu","Sergé de coton, polyester, tissu technique ou filet"],["Fermeture","Boutons-pression, boucle, autoagrippant ou extensible"],["Marquage","Broderie avant, écusson et logos latéral ou arrière"]],checklist:["Référence de style de casquette ou de visière","Région et saison d'utilisation","Plage de tailles requise","Fichiers de logo pour chaque position","Date d'événement et quantité estimée"],faqs:[["Faut-il toujours un tissu technique pour le golf?","Pour un climat chaud et un port prolongé, la légèreté, le séchage et la respirabilité sont prioritaires. Le sergé peut mieux convenir si le toucher et l'apparence du cadeau sont plus importants."],["La broderie 3D convient-elle à tous les logos?","Non. Les lignes fines, les petits caractères et les détails complexes sont souvent plus nets en broderie à plat ou sur un écusson."],["Une taille unique suffit-elle?","Cela dépend du groupe et de la fermeture. Il faut vérifier la plage d'ajustement réelle et la profondeur de la couronne." ]],product:"/fr-ca/custom-golf-caps/",brief:"Casquettes et visières de golf personnalisées"},
  frCaPackagingGuide:{label:"EMBALLAGES DE GOLF PERSONNALISÉS",title:"Confirmer les produits et la remise avant de concevoir la boîte",intro:"Un bon emballage doit présenter les produits, les maintenir, les protéger pendant le transport et faciliter la distribution sur place.",image:"/assets/images/zhoni-product-packaging-v3.png",rows:[["Liste de produits","Composition finale, quantités, dimensions et poids réels"],["Structure de boîte","Rigide, pliante, avec fourreau et méthode d'ouverture"],["Calage","Maintien des produits, ordre de retrait et matière"],["Marquage","Impression, dorure, gaufrage, étiquettes et cartes"],["Protection","Rayures, compression, humidité et contact entre les pièces"],["Expédition","Cartons extérieurs, unités par carton, destination et conditions de remise"]],checklist:["Produits finaux avec dimensions réelles","Expérience d'ouverture souhaitée","Images de référence de boîte et de calage","Fichiers d'impression et couleurs de marque","Pays de livraison et méthode de distribution"],faqs:[["Peut-on finaliser la boîte avant les produits?","Ce n'est pas recommandé. Un changement de dimensions ou de disposition des produits peut modifier le calage et toute la structure de la boîte."],["Une boîte rigide haut de gamme est-elle toujours nécessaire?","Non. Pour une distribution lors d'un événement, un transport international ou un budget précis, une boîte pliante ou un fourreau peut être plus approprié."],["La quantité minimale de l'emballage est-elle identique à celle des produits?","Pas toujours. La structure, l'impression, le calage et les matières peuvent avoir leurs propres conditions de production." ]],product:"/fr-ca/custom-golf-packaging/",brief:"Emballages de golf personnalisés"},
};

function GuideArticle({pageKey}){const c=articleContent[pageKey];return <main className="zhoni-page guide-page fr-ca-page"><Header active="guides"/><section className="guide-hero"><div><p>{c.label} · GUIDE D'ACHAT</p><h1>{c.title}</h1><p>{c.intro}</p><small>CHOIX DU PRODUIT · SPÉCIFICATIONS · ÉCHANTILLON · SOUMISSION</small></div><img src={c.image} alt={c.label}/></section><section className="guide-intro"><p>EXAMEN PRATIQUE POUR L'ACHETEUR</p><h2>Les décisions utiles avant de demander un prix.</h2><p>Il n'est pas nécessaire de tout finaliser dès le départ. Les renseignements disponibles et les références permettent d'évaluer plus justement le produit, la quantité minimale, l'échantillonnage et l'échéancier applicables.</p></section><section className="guide-table"><table><thead><tr><th>POINT À ÉVALUER</th><th>RENSEIGNEMENTS À PRÉPARER</th></tr></thead><tbody>{c.rows.map(row=><tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td></tr>)}</tbody></table></section><section className="guide-decision"><div><p>PRÉPARER LE CAHIER DES CHARGES</p><h2>Comparer les fournisseurs sur la même base.</h2><p>Présenter ensemble les spécifications, le logo, la quantité, la date, l'emballage et la destination permet de comparer la portée réelle du projet, et non seulement un prix unitaire.</p></div><aside><p>LISTE DE CONTRÔLE</p><h3>À préparer avant de nous écrire</h3><ul>{c.checklist.map(item=><li key={item}>{item}</li>)}</ul></aside></section><section className="guide-faq"><p>QUESTIONS FRÉQUENTES DES ACHETEURS</p><h2>Des réponses concrètes pour la prochaine décision.</h2><div>{c.faqs.map(([question,answer],index)=><article key={question}><b>{String(index+1).padStart(2,"0")}</b><h3>{question}</h3><p>{answer}</p></article>)}</div></section><section className="guide-products"><p>PAGES CONNEXES</p><h2>Passer du guide au projet.</h2><div><a href={c.product}>Page du produit<Arrow/></a><a href="/fr-ca/solutions/">Solutions<Arrow/></a><a href="/fr-ca/our-process/">Notre processus<Arrow/></a><a href={`/fr-ca/request-a-quote/?product=${encodeURIComponent(c.brief)}`}>Demander une soumission<Arrow/></a></div></section><section className="guide-close"><div><p>PRÊT À PRÉPARER LE CAHIER DES CHARGES?</p><h2>Partagez le produit, la quantité et la date cible.</h2><a href={`/fr-ca/request-a-quote/?product=${encodeURIComponent(c.brief)}`}>ENVOYER LE PROJET <Arrow/></a></div><img src={c.image} alt={c.label}/></section><Footer/></main>}

export function CanadianFrenchExpansion({routeKey}){
  if(categoryContent[routeKey])return <CategoryPage pageKey={routeKey}/>;
  if(solutionContent[routeKey])return <SolutionDetail pageKey={routeKey}/>;
  if(articleContent[routeKey])return <GuideArticle pageKey={routeKey}/>;
  if(routeKey==="frCaGuides")return <GuidesHub/>;
  return <CanadianFrenchProcurement routeKey={routeKey}/>;
}
