import { useState } from "react";
import { LanguageSwitcher } from "./locale.jsx";

const WHATSAPP_URL = import.meta.env.VITE_WHATSAPP_URL ?? "https://wa.me/8617759190848";
const Arrow = () => <span aria-hidden="true">↗</span>;

function Header({ active }) {
  const [menu,setMenu]=useState(false);
  return <header className={`zhoni-header fr-ca-header ${menu?"zhoni-header-open":""}`}><a className="zhoni-wordmark" href="/fr-ca/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><button className="zhoni-menu" onClick={()=>setMenu(value=>!value)} aria-expanded={menu}>{menu?"FERMER":"MENU"}</button><nav aria-label="Navigation principale"><a className={active==="products"?"active":""} href="/fr-ca/products/">PRODUITS</a><a className={active==="solutions"?"active":""} href="/fr-ca/solutions/">SOLUTIONS</a><a href="/fr-ca/our-process/">NOTRE PROCESSUS</a><a href="/fr-ca/faq/">FAQ</a><a href="/fr-ca/about/">À PROPOS</a></nav><LanguageSwitcher/><a className="zhoni-header-cta" href="/fr-ca/request-a-quote/">DEMANDER UNE SOUMISSION <Arrow/></a></header>;
}

function Footer(){return <footer className="site-footer"><div className="site-footer-main"><a className="zhoni-wordmark" href="/fr-ca/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><div className="site-footer-copy"><p>Articles et cadeaux de golf personnalisés pour clubs, tournois, entreprises et marques.</p><span>ENSEMBLES-CADEAUX · COUVRE-BÂTONS · CASQUETTES · SERVIETTES · ACCESSOIRES · EMBALLAGES</span><div className="site-footer-contact"><b>CONTACT DIRECT</b><a href="mailto:sales@zhonigolf.com">sales@zhonigolf.com</a><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer">WhatsApp +86 177 5919 0848 <Arrow/></a></div></div><nav aria-label="Navigation de pied de page"><a href="/fr-ca/products/">Produits</a><a href="/fr-ca/solutions/">Solutions</a><a href="/fr-ca/our-process/">Notre processus</a><a href="/fr-ca/faq/">FAQ</a><a href="/fr-ca/about/">À propos</a><a href="/fr-ca/request-a-quote/">Soumission <Arrow/></a></nav></div><div className="site-footer-base"><span>ZHONI · CUSTOM GOLF MERCHANDISE</span><span>Entité exploitante : Xiamen Jindongyu Trading Co., Ltd.</span></div></footer>}

const categoryContent={
  frCaHeadcovers:{eyebrow:"COUVRE-BÂTONS DE GOLF PERSONNALISÉS",brief:"Couvre-bâtons de golf personnalisés",title:"Protéger les bâtons.\nFaire vivre la marque.",intro:"Développez des couvre-bâtons pour bois de départ, bois d'allée, hybrides et fers droits selon l'ajustement, la matière, l'identité visuelle et la composition de l'ensemble.",image:"/assets/images/zhoni-product-headcovers-v3.png",alt:"Couvre-bâtons de golf personnalisés vert forêt avec monogramme Z doré",rows:[["Types","Bois de départ · bois d'allée · hybride · fer droit lame ou maillet"],["Matières","PU, similicuir, tissu, tricot et constructions mixtes"],["Marquage","Broderie, appliqué, débossage, écusson et étiquette"],["Points à valider","Ajustement, ouverture, doublure, coutures, position du logo et repères de série"]],checklist:["Types de bâtons et répartition des quantités","Références de matière et de toucher","Logo vectoriel et couleurs de marque","Emballage individuel ou en ensemble","Date de réception et lieu de livraison"]},
  frCaCaps:{eyebrow:"CASQUETTES ET VISIÈRES DE GOLF",brief:"Casquettes et visières de golf personnalisées",title:"Une identité de marque\nqui dépasse le parcours.",intro:"Planifiez des casquettes et visières pour tournois, programmes de membres et événements d'entreprise selon l'ajustement, le climat, le tissu et la méthode de marquage.",image:"/assets/images/zhoni-product-caps-v3.png",alt:"Casquette et visière de golf personnalisées vert forêt avec logo Z doré",rows:[["Modèles","Casquette structurée ou souple · performance · visière · filet"],["Tissus","Sergé de coton, polyester, tissu technique et filet"],["Marquage","Broderie à plat ou 3D, écusson tissé ou caoutchouc, logos latéral et arrière"],["Points à valider","Couronne, visière, bandeau absorbant, fermeture et plage de tailles"]],checklist:["Profil des personnes et saison d'utilisation","Style de casquette ou de visière","Performance du tissu et couleurs","Emplacements du logo à l'avant, au côté et à l'arrière","Quantité, échéance et destination"]},
  frCaTowels:{eyebrow:"SERVIETTES DE GOLF PERSONNALISÉES",brief:"Serviettes de golf personnalisées",title:"Une utilité réelle,\navec les bons détails de marque.",intro:"Planifiez le tissu gaufré, la broderie, le mousqueton et le système magnétique selon l'utilisation sur le parcours et la composition du cadeau.",image:"/assets/images/zhoni-product-magnetic-towel-v4.png",alt:"Serviette de golf magnétique personnalisée avec broderie Z dorée",rows:[["Formats","Gaufrée · magnétique · avec mousqueton · pour ensemble-cadeau"],["Matières","Microfibre gaufrée, coton et solutions adaptées au projet"],["Marquage","Broderie, étiquette tissée, impression et carte d'emballage"],["Points à valider","Dimensions, grammage, bordure, aimant ou mousqueton et tenue après lavage"]],checklist:["Usage prévu et dimensions souhaitées","Références de tissu et de couleur","Taille et position de la broderie","Besoin d'un aimant ou d'un mousqueton","Emballage individuel ou composition en ensemble"]},
  frCaAccessories:{eyebrow:"ACCESSOIRES DE GOLF PERSONNALISÉS",brief:"Accessoires de golf personnalisés",title:"Une expérience de marque claire,\nmême dans les petits formats.",intro:"Composez marque-balles, relève-pitchs, pinces à casquette, étiquettes de sac et pochettes selon leur rôle dans un ensemble de tournoi, un cadeau d'entreprise ou un programme de club.",image:"/assets/images/zhoni-product-accessories-v3.png",alt:"Pochette et étiquette de sac de golf personnalisées avec marque Z dorée",rows:[["Produits","Marque-balle · relève-pitch · pince à casquette · étiquette de sac · pochette"],["Matières","Métal, PU, textile et combinaisons selon le produit"],["Marquage","Gravure, émail, débossage, broderie et impression"],["Points à valider","Dimensions, placage, bords, assemblage des pièces et emballage individuel"]],checklist:["Destinataires et objectif","Combinaison de produits et quantités","Finition du métal ou orientation de matière","Épaisseur des traits et couleurs du logo","Besoin d'un emballage en ensemble"]},
  frCaPackaging:{eyebrow:"EMBALLAGES DE GOLF PERSONNALISÉS",brief:"Emballages de golf personnalisés",title:"Compléter le projet\njusqu'au moment de remise.",intro:"Concevez boîtes-cadeaux, calages, fourreaux, cartes et protection de transport selon la composition des produits, l'expérience de marque et les conditions réelles d'expédition.",image:"/assets/images/zhoni-product-packaging-v3.png",alt:"Boîte-cadeau de golf personnalisée avec calage et logo Z doré",rows:[["Structures","Boîte pliante · boîte rigide · fourreau · calage"],["Finitions","Impression, dorure, gaufrage ou débossage et étiquette"],["Aménagement intérieur","EVA, carton, textile, protection et maintien des produits"],["Points à valider","Dimensions, ordre d'ouverture, protection, efficacité des cartons et mode de livraison"]],checklist:["Liste finale des produits dans la boîte","Dimensions et priorité de présentation","Couleurs de marque et fichiers de logo","Carte, fourreau et étiquettes requis","Destination et exigences des cartons extérieurs"]},
};

function CategoryPage({pageKey}){const c=categoryContent[pageKey];return <main className="zhoni-page category-page fr-ca-page"><Header active="products"/><section className="category-hero"><aside className="category-rail" aria-hidden="true"><strong>Z</strong><span>CUSTOM GOLF PRODUCTS</span></aside><div className="category-intro"><p>{c.eyebrow}</p><h1>{c.title.split("\n").map((line,index)=><span key={line}>{line}{index===0&&<br/>}</span>)}</h1><p>{c.intro}</p><a href={`/fr-ca/request-a-quote/?product=${encodeURIComponent(c.brief)}`}>PRÉSENTER CE PRODUIT <Arrow/></a><small>CLUBS · TOURNOIS · ENTREPRISES · MARQUES</small></div><img src={c.image} alt={c.alt}/></section><section className="guide-table"><table><thead><tr><th>POINT À ÉVALUER</th><th>ORIENTATION PRATIQUE</th></tr></thead><tbody>{c.rows.map(row=><tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td></tr>)}</tbody></table></section><section className="guide-decision"><div><p>PRÉPARATION DU PROJET</p><h2>Aligner les spécifications avant de comparer les prix.</h2><p>La quantité minimale, le prix, l'échantillonnage et le délai dépendent de la construction, de la personnalisation, du volume, de l'emballage et de la destination. Ces renseignements rendent l'évaluation plus réaliste.</p></div><aside><p>LISTE DE L'ACHETEUR</p><h3>À préparer dans le cahier des charges</h3><ul>{c.checklist.map(item=><li key={item}>{item}</li>)}</ul></aside></section><section className="guide-products"><p>PARCOURS CONNEXES</p><h2>Passer du produit au projet concret.</h2><div><a href="/fr-ca/products/">Tous les produits<Arrow/></a><a href="/fr-ca/solutions/">Solutions par projet<Arrow/></a><a href="/fr-ca/our-process/">Notre processus<Arrow/></a><a href="/fr-ca/request-a-quote/">Demander une soumission<Arrow/></a></div></section><section className="guide-close"><div><p>PRÊT À ÉVALUER LE PROJET?</p><h2>Partagez le produit, la quantité et la date cible.</h2><a href={`/fr-ca/request-a-quote/?product=${encodeURIComponent(c.brief)}`}>ENVOYER LE CAHIER DES CHARGES <Arrow/></a></div><img src={c.image} alt={c.alt}/></section><Footer/></main>}

const solutionContent={
  frCaTournamentGifts:{label:"CADEAUX DE TOURNOI ET SACS DE BIENVENUE",title:"Des cadeaux adaptés au rôle de chaque participant.",intro:"Les cadeaux des joueurs, des commanditaires, des invités VIP et des gagnants répondent à des objectifs différents, même au sein du même tournoi.",image:"/assets/images/zhoni-golf-tournament-gift-delivery-v2.png",solution:"golf-tournament-gifts",steps:[["01","Définir les groupes","Distinguer les participants, commanditaires, invités VIP, équipe organisatrice et gagnants."],["02","Composer les produits","Choisir selon le moment d'utilisation, l'orientation budgétaire et la facilité de distribution."],["03","Coordonner marque et emballage","Évaluer ensemble le logo de l'événement, la visibilité des commanditaires et la remise sur place."],["04","Planifier à rebours","Prévoir validation, échantillonnage, production, emballage et livraison à partir de la date du tournoi."]],products:"Serviettes magnétiques, casquettes, marque-balles, relève-pitchs, pochettes et boîtes-cadeaux peuvent être réunis selon le rôle de chaque groupe."},
  frCaCorporateGifts:{label:"CADEAUX DE GOLF D'ENTREPRISE",title:"Des cadeaux pensés selon la relation et le moment de remise.",intro:"Pour la reconnaissance des clients, les récompenses d'équipe, les événements de partenaires et les campagnes de marque, commencez par définir le destinataire et le niveau de présentation.",image:"/assets/images/zhoni-custom-golf-packaging-v2.png",solution:"corporate-golf-gifts",steps:[["01","Identifier les destinataires","Distinguer clients, cadres, équipes, partenaires et participants à l'événement."],["02","Définir le niveau du cadeau","Choisir un article pratique distinctif ou un ensemble haut de gamme."],["03","Ajuster l'expression de marque","Adapter la taille et la visibilité du logo au produit et à la relation."],["04","Préparer la remise","Confirmer carte-message, emballage individuel, destinations et date de réception."]],products:"Couvre-bâtons, casquettes, serviettes, accessoires métalliques et boîtes personnalisées peuvent former une expérience-cadeau d'entreprise cohérente."},
};

function SolutionDetail({pageKey}){const c=solutionContent[pageKey];return <main className="zhoni-page corporate-page fr-ca-page"><Header active="solutions"/><section className="corporate-hero"><aside className="corporate-rail" aria-hidden="true"><strong>Z</strong><span>GOLF GIFT SOLUTIONS</span></aside><div><p>{c.label}</p><h1>{c.title}</h1><p>{c.intro}</p><a href={`/fr-ca/request-a-quote/?solution=${c.solution}`}>PRÉSENTER LE PROJET <Arrow/></a></div><img src={c.image} alt={c.label}/></section><section className="corporate-ledger"><div><p>PARCOURS DE PLANIFICATION</p>{c.steps.map(([n,t,d])=><article key={n}><b>{n}</b><h2>{t}</h2><p>{d}</p><span>→</span></article>)}</div><aside><p>RENSEIGNEMENTS ESSENTIELS</p><ul><li><b>Destinataires</b><span>Qui recevra les cadeaux et combien de personnes?</span></li><li><b>Échéance</b><span>Date de l'événement ou de réception souhaitée</span></li><li><b>Destination</b><span>Pays, ville et points de distribution</span></li><li><b>Éléments de marque</b><span>Logo, couleurs et images de référence</span></li><li><b>Emballage</b><span>Présentation individuelle ou en ensemble</span></li></ul></aside></section><section className="corporate-closing"><img src="/assets/images/zhoni-golf-product-development-v2.png" alt="Examen du marquage d'articles de golf personnalisés"/><div><p>CADEAUX DE GOLF COORDONNÉS</p><h2>Définir le rôle du cadeau avant de choisir les produits.</h2><p>{c.products}</p><a href="/fr-ca/products/">EXPLORER LES PRODUITS <Arrow/></a></div></section><section className="guide-products"><p>PARCOURS CONNEXES</p><h2>Continuer avec le bon niveau de détail.</h2><div><a href="/fr-ca/products/">Produits personnalisés<Arrow/></a><a href="/fr-ca/custom-golf-packaging/">Emballages personnalisés<Arrow/></a><a href="/fr-ca/our-process/">Notre processus<Arrow/></a><a href={`/fr-ca/request-a-quote/?solution=${c.solution}`}>Demander une soumission<Arrow/></a></div></section><Footer/></main>}

export function CanadianFrenchExpansion({routeKey}){
  if(categoryContent[routeKey])return <CategoryPage pageKey={routeKey}/>;
  if(solutionContent[routeKey])return <SolutionDetail pageKey={routeKey}/>;
  return null;
}
