import { useState } from "react";
import { LanguageSwitcher } from "./locale.jsx";
import { TurnstileField } from "./turnstile.jsx";
import { trackAnalytics } from "./analytics.jsx";
import { inquirySourceForLocation } from "./seo.js";
import { CanadianFrenchExpansion } from "./CanadianFrenchExpansion.jsx";

const WHATSAPP_URL = import.meta.env.VITE_WHATSAPP_URL ?? "https://wa.me/8617759190848";
const Arrow = () => <span aria-hidden="true">↗</span>;

const productFamilies = [
  ["Couvre-bâtons", "Des couvre-bâtons personnalisés pour les clubs, tournois et marques.", "/assets/images/zhoni-product-headcovers-v3.png", "Couvre-bâtons de golf personnalisés"],
  ["Casquettes et visières", "Des modèles pensés selon l'usage, l'ajustement et l'identité de marque.", "/assets/images/zhoni-product-caps-v3.png", "Casquettes et visières de golf personnalisées"],
  ["Serviettes magnétiques", "Une solution pratique sur le parcours avec broderie et finitions soignées.", "/assets/images/zhoni-product-magnetic-towel-v4.png", "Serviettes de golf personnalisées"],
  ["Accessoires de golf", "Pochettes, étiquettes de sac, marque-balles et relève-pitchs coordonnés.", "/assets/images/zhoni-product-accessories-v3.png", "Accessoires de golf personnalisés"],
  ["Ensembles-cadeaux", "Des articles réunis autour du destinataire et du moment de remise.", "/assets/images/zhoni-product-gift-sets-v3.png", "Ensembles-cadeaux de golf"],
  ["Emballages personnalisés", "Boîtes, calages, cartes et détails de présentation pour une remise cohérente.", "/assets/images/zhoni-product-packaging-v3.png", "Emballages de golf personnalisés"],
];

function FrenchHeader({ active }) {
  const [menu, setMenu] = useState(false);
  return <header className={`zhoni-header fr-ca-header ${menu ? "zhoni-header-open" : ""}`}>
    <a className="zhoni-wordmark" href="/fr-ca/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a>
    <button className="zhoni-menu" onClick={() => setMenu(value => !value)} aria-expanded={menu}>{menu ? "FERMER" : "MENU"}</button>
    <nav aria-label="Navigation principale"><a className={active === "products" ? "active" : ""} href="/fr-ca/products/">PRODUITS</a><a className={active === "solutions" ? "active" : ""} href="/fr-ca/solutions/">SOLUTIONS</a><a className={active === "guides" ? "active" : ""} href="/fr-ca/guides/">GUIDES D'ACHAT</a><a className={active === "process" ? "active" : ""} href="/fr-ca/our-process/">PROCESSUS</a><a className={active === "faq" ? "active" : ""} href="/fr-ca/faq/">FAQ</a><a className={active === "about" ? "active" : ""} href="/fr-ca/about/">À PROPOS</a></nav>
    <LanguageSwitcher />
    <a className="zhoni-header-cta" href="/fr-ca/request-a-quote/">DEMANDER UNE SOUMISSION <Arrow /></a>
  </header>;
}

function FrenchFooter() {
  return <footer className="site-footer"><div className="site-footer-main"><a className="zhoni-wordmark" href="/fr-ca/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><div className="site-footer-copy"><p>Articles et cadeaux de golf personnalisés pour clubs, tournois, entreprises et marques.</p><span>Ensembles-cadeaux · couvre-bâtons · casquettes · serviettes · accessoires · emballages</span><div className="site-footer-contact"><b>CONTACT DIRECT</b><a href="mailto:sales@zhonigolf.com">sales@zhonigolf.com</a><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer">WhatsApp +86 177 5919 0848 <Arrow /></a></div></div><nav aria-label="Navigation de pied de page"><a href="/fr-ca/products/">Produits</a><a href="/fr-ca/solutions/">Solutions</a><a href="/fr-ca/guides/">Guides d'achat</a><a href="/fr-ca/capabilities/">Capacités</a><a href="/fr-ca/our-process/">Notre processus</a><a href="/fr-ca/faq/">FAQ</a><a href="/fr-ca/about/">À propos</a><a href="/fr-ca/request-a-quote/">Soumission <Arrow /></a></nav></div><div className="site-footer-base"><span>ZHONI · CUSTOM GOLF MERCHANDISE</span><span>Entité exploitante : Xiamen Jindongyu Trading Co., Ltd.</span></div></footer>;
}

function FrenchHome() {
  return <main className="zhoni-page fr-ca-page"><FrenchHeader />
    <section className="gifts-hero"><aside><span>CLUBS</span><span>TOURNOIS</span><span>ENTREPRISES</span><span>MARQUES</span></aside><div><p>ARTICLES DE GOLF · ENSEMBLES-CADEAUX · EMBALLAGES</p><h1>Votre marque,<br />jusque sur le parcours.</h1><p>ZHONI réunit le développement de produits, le marquage, la composition d'ensembles-cadeaux et l'emballage dans un même projet pour les clubs, tournois, entreprises et marques.</p><div className="gifts-fit"><article><b>PROJETS ADAPTÉS</b><span>Projets B2B qui exigent plusieurs articles réunis dans une expérience de marque cohérente.</span></article><article><b>POUR COMMENCER</b><span>Orientation du produit, quantité estimée, date cible, destination et fichiers de marque.</span></article></div><a href="/fr-ca/request-a-quote/">PRÉSENTER UN PROJET <Arrow /></a></div><img src="/assets/images/zhoni-golf-collection-hero-v2.png" alt="Collection d'articles et de cadeaux de golf personnalisés ZHONI" /></section>
    <section className="gift-atlas"><p>PARCOURS DE PROJET ZHONI</p><h2>D'un article unique à une collection complète.</h2><p className="atlas-intro">Nous partons du destinataire, de l'occasion et de l'échéance pour définir les produits, le marquage et l'emballage appropriés.</p>{[["01","Choisir les produits","Couvre-bâtons, casquettes, serviettes, accessoires ou ensembles-cadeaux.","VOIR LES PRODUITS","/fr-ca/products/"],["02","Structurer le programme","Tournoi, cadeau d'entreprise, programme de club ou collection de marque privée.","VOIR LES SOLUTIONS","/fr-ca/solutions/"],["03","Confirmer les détails","Matières, couleurs, méthode de marquage, emballage et étapes d'approbation.","NOTRE PROCESSUS","/fr-ca/our-process/"],["04","Partager le cahier des charges","Quantité, échéance, destination et éléments de marque permettent une évaluation utile.","DEMANDER UNE SOUMISSION","/fr-ca/request-a-quote/"]].map(([n,t,c,l,h])=><article key={n}><b>{n}</b><div><h3>{t}</h3><p>{c}</p></div><a href={h}>{l} <Arrow /></a></article>)}</section>
    <section className="gifts-closing"><img src="/assets/images/zhoni-custom-golf-packaging-v2.png" alt="Emballage personnalisé pour cadeaux de golf ZHONI" /><div><p>UN SEUL CAHIER DES CHARGES</p><h2>Un projet pensé pour le destinataire et le moment de remise.</h2><p>Indiquez-nous les produits, la quantité, la date souhaitée, la destination et les attentes d'emballage. Nous vous guiderons vers la prochaine étape réaliste.</p><a href="/fr-ca/request-a-quote/">COMMENCER LE PROJET <Arrow /></a></div></section><FrenchFooter />
  </main>;
}

function FrenchProducts() {
  const paths=["/fr-ca/custom-golf-headcovers/","/fr-ca/custom-golf-caps/","/fr-ca/custom-golf-towels/","/fr-ca/custom-golf-accessories/","/fr-ca/solutions/corporate-golf-gifts/","/fr-ca/custom-golf-packaging/"];
  return <main className="products-hub fr-ca-page"><FrenchHeader active="products" /><section className="products-hero"><img src="/assets/images/zhoni-golf-collection-hero-v2.png" alt="Collection de produits de golf personnalisés ZHONI" /><div className="products-hero-copy"><p className="products-kicker">PRODUITS DE GOLF PERSONNALISÉS</p><h1>Plus que des articles,<br />une collection cohérente.</h1><p>Des produits pensés selon l'usage, le destinataire et l'expérience de remise pour les clubs, tournois, entreprises et marques.</p><a href="/fr-ca/request-a-quote/">COMMENCER UN PROJET <Arrow /></a></div></section><section className="family-index"><div className="family-heading"><p className="products-kicker">NOS FAMILLES</p><h2>Produits</h2><p>Des usages différents.<br />Une seule identité.</p></div><div className="family-grid">{productFamilies.map(([title,copy,image],index)=><a className="family-card" href={paths[index]} key={title}><img src={image} alt={`${title} ZHONI`} /><h3>{title}</h3><p>{copy}</p><span>— &nbsp; <Arrow /></span></a>)}</div></section><section className="products-intro"><p className="products-kicker">UNE APPROCHE COORDONNÉE</p><h2>Le produit, le marquage et l'emballage sont étudiés ensemble.</h2><p>Les spécifications, quantités minimales, prix et délais dépendent de la construction, du niveau de personnalisation, de la quantité, de l'emballage et de la destination.</p><a href="/fr-ca/our-process/">VOIR NOTRE PROCESSUS <Arrow /></a></section><FrenchFooter /></main>;
}

function FrenchSolutions() {
  const programs=[["01","Cadeaux de tournoi et sacs de bienvenue","Articles pour participants, commanditaires, invités VIP et gagnants.","/assets/images/zhoni-golf-tournament-gift-delivery-v2.png","/fr-ca/solutions/golf-tournament-gifts/"],["02","Cadeaux de golf d'entreprise","Programmes de reconnaissance pour clients, équipes et partenaires.","/assets/images/zhoni-custom-golf-packaging-v2.png","/fr-ca/solutions/corporate-golf-gifts/"],["03","Programmes pour membres de club","Produits personnalisés pour événements, jalons et programmes récurrents.","/assets/images/zhoni-golf-product-development-v2.png","/fr-ca/request-a-quote/?solution=club-member-program"],["04","Collections de marque privée","Développement de gamme, co-marquage et projets de collection.","/assets/images/zhoni-golf-collection-hero-v2.png","/fr-ca/request-a-quote/?solution=private-label-collection"]];
  return <main className="zhoni-page solutions-page fr-ca-page"><FrenchHeader active="solutions" /><section className="solutions-index-hero"><div className="solutions-rail" aria-hidden="true"><strong>Z</strong><span>SOLUTIONS</span><i>PEOPLE · GOLF · BRANDS</i></div><div className="solutions-index-intro"><p>SOLUTIONS PAR PROJET</p><h1>Commencer par le public<br />et l'objectif.</h1><p>Nous évaluons le destinataire, l'occasion, la quantité et la méthode de remise avant de recommander une direction de produits.</p></div><figure><img src="/assets/images/zhoni-custom-golf-packaging-v2.png" alt="Ensemble-cadeau de golf avec emballage personnalisé" /><figcaption>PLUS QUE DES PRODUITS.<br />UNE APPROCHE PLUS RÉFLÉCHIE.</figcaption></figure></section><section className="solutions-program-index">{programs.map(([n,t,c,img,href])=><a className="solutions-program" href={href} key={n}><b>{n}</b><img src={img} alt={t} /><div><h2>{t}</h2><p><strong>CONVIENT À</strong>{c}</p></div><span>→</span></a>)}</section><section className="solutions-brief-bridge"><div><p>COMMENCEZ PAR UN CAHIER DES CHARGES</p><h2>Définir l'objectif,<br />puis construire la collection.</h2><p>Partagez le profil des destinataires, la quantité, la date cible, le lieu de livraison et l'orientation souhaitée.</p><a href="/fr-ca/request-a-quote/">PRÉSENTER LE PROJET <Arrow /></a></div><aside><p>RENSEIGNEMENTS UTILES</p><ul><li>Qui recevra les articles?</li><li>De quel événement ou programme s'agit-il?</li><li>Quelle est la quantité estimée?</li><li>Quand et où les articles sont-ils requis?</li><li>Disposez-vous d'un logo ou de références?</li></ul></aside></section><FrenchFooter /></main>;
}

function FrenchProcess() {
  const steps=[["01","Cahier des charges","Objectif, public, quantité estimée, date souhaitée et destination.","/assets/images/zhoni-material-direction-v1.png"],["02","Orientation du produit","Produit, matières, marquage et emballage adaptés au contexte.","/assets/images/zhoni-embroidery-sample-v1.png"],["03","Validation","Maquette, épreuve, échantillon ou spécifications selon le projet.","/assets/images/zhoni-gift-packaging-process-v1.png"],["04","Préparation de la production","Portée approuvée et critères de contrôle de la qualité.","/assets/images/zhoni-quality-inspection-v1.png"],["05","Emballage et expédition","Cartons, adresse de livraison et conditions d'expédition confirmés.","/assets/images/zhoni-carton-packing-v1.png"]];
  return <main className="zhoni-page process-page fr-ca-page"><FrenchHeader active="process" /><section className="process-hero"><div><p>NOTRE PROCESSUS</p><h1>Du cahier des charges<br />à la livraison.</h1><p>Un projet personnalisé relie le produit, le logo, l'emballage et l'échéancier. Chaque étape comporte des points de validation clairs.</p><a href="/fr-ca/request-a-quote/">ENVOYER UN CAHIER DES CHARGES <Arrow /></a></div><img src="/assets/images/zhoni-material-direction-v1.png" alt="Sélection de matières et de couleurs pour des produits de golf" /></section><section className="process-ledger"><p>LE PROCESSUS</p><span>UN PARCOURS EN 5 ÉTAPES</span><div>{steps.map(([n,t,c,img])=><article key={n}><b>{n}</b><h2>{t}</h2><p>{c}</p><img src={img} alt={t} /></article>)}</div></section><section className="project-input"><div><p>RENSEIGNEMENTS À FOURNIR</p><h2>Une évaluation utile commence<br />par un contexte précis.</h2><p>Il n'est pas nécessaire de tout définir dès le départ. Partagez d'abord ce que vous savez et vos références.</p></div><ul><li><b>Objectif</b><span>Club, tournoi, cadeau d'entreprise ou collection de marque</span></li><li><b>Quantité</b><span>Une estimation suffit pour commencer</span></li><li><b>Date et destination</b><span>Date de réception souhaitée, pays et ville</span></li><li><b>Éléments de marque</b><span>Logo, couleurs et images de référence</span></li><li><b>Emballage</b><span>Boîte, calage, carte ou autre méthode de présentation</span></li></ul><aside>Les quantités minimales, prix, échantillons, délais de production et conditions de livraison sont confirmés selon la portée convenue.</aside></section><FrenchFooter /></main>;
}

function FrenchFaq() {
  const [open,setOpen]=useState(0);
  const items=[["Quels produits de golf peuvent être personnalisés?","Nous pouvons étudier des couvre-bâtons, casquettes et visières, serviettes, pochettes, étiquettes de sac, marque-balles, relève-pitchs, balles de golf, ensembles-cadeaux et emballages selon la portée du projet."],["Quelle est la quantité minimale de commande?","La quantité minimale varie selon le produit, la matière, la construction, la méthode de marquage, les couleurs et l'emballage. Indiquez le produit et la quantité estimée pour obtenir les conditions applicables."],["Comment fonctionnent les échantillons et les approbations?","Selon le produit, la validation peut comprendre une maquette, une épreuve, un échantillon physique ou une fiche de spécifications. Le parcours est défini après l'examen du projet."],["Quels renseignements faut-il fournir pour une soumission?","Précisez le produit, la quantité estimée, les fichiers de logo, les attentes d'emballage, la date de réception souhaitée ainsi que la ville et le pays de livraison."],["Combien de temps faut-il prévoir?","Le délai dépend de l'état des fichiers, du produit, de l'échantillonnage, de la quantité, de l'emballage et de la destination. Mentionnez toujours la date à laquelle les produits doivent être reçus."],["Pouvez-vous créer un ensemble-cadeau complet?","Oui. Les produits, le marquage et l'emballage peuvent être coordonnés autour du public, de l'événement et du niveau de présentation souhaité."]];
  return <main className="zhoni-page faq-page fr-ca-page"><FrenchHeader active="faq" /><section className="faq-ledger-hero"><div><p>FAQ · GUIDE D'ACHAT</p><h1>Les questions clés<br />d'un projet personnalisé.</h1><p>Le produit, la quantité, le marquage, l'emballage, l'échéance et la destination doivent être évalués ensemble.</p></div><aside><p>AVANT DE NOUS ÉCRIRE</p><h2>À inclure dans votre demande</h2><ol><li>Public et objectif</li><li>Orientation du produit ou images de référence</li><li>Quantité et date de réception souhaitée</li><li>Logo et attentes d'emballage</li><li>Ville et pays de livraison</li></ol></aside></section><section className="capability-faq"><div><p>QUESTIONS FRÉQUENTES</p><h2>Des réponses utiles pour les acheteurs.</h2></div><div>{items.map(([q,a],i)=><article key={q}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><span>{q}</span><b>{open===i?"−":"+"}</b></button><p hidden={open!==i}>{a}</p></article>)}</div></section><section className="faq-path"><p>PROCHAINE ÉTAPE</p><div><a href="/fr-ca/products/"><b>01</b><span>Voir les produits</span><Arrow /></a><a href="/fr-ca/solutions/"><b>02</b><span>Choisir une solution</span><Arrow /></a><a href="/fr-ca/request-a-quote/"><b>03</b><span>Présenter le projet</span><Arrow /></a></div></section><FrenchFooter /></main>;
}

function FrenchAbout() {
  return <main className="zhoni-page about-page fr-ca-page"><FrenchHeader active="about" /><section className="zhoni-about-hero"><img src="/assets/images/zhoni-golf-collection-hero-v2.png" alt="Collection de cadeaux de golf personnalisés ZHONI" /><div><p>À PROPOS DE ZHONI</p><h1>Des projets de golf<br />avec un objectif clair.</h1><p>ZHONI accompagne les clubs, tournois, entreprises et marques dans leurs projets de produits, ensembles-cadeaux et emballages de golf personnalisés.</p><a href="/fr-ca/request-a-quote/">COMMENCER UN PROJET <Arrow /></a></div></section><section className="relationship"><div><p>STRUCTURE D'EXPLOITATION</p><h2>Une entité claire.<br />Une gestion cohérente.</h2></div><div className="relationship-copy"><p>ZHONI est une marque spécialisée en articles de golf personnalisés exploitée par Xiamen Jindongyu Trading Co., Ltd. Nous coordonnons l'orientation du produit, la personnalisation, l'emballage et la préparation commerciale projet par projet.</p><p>Nous n'appliquons pas une réponse unique à tous les besoins. La portée, les quantités minimales, l'échéancier et les exigences sont évalués à partir du cahier des charges réel du client.</p></div><div className="relationship-map"><article><b>ZHONI</b><span>Marque spécialisée en articles de golf personnalisés</span><small>Produit · personnalisation · projets clients</small></article><i>EXPLOITÉE PAR</i><article><b>Xiamen Jindongyu<br />Trading Co., Ltd.</b><span>Entité juridique exploitante</span><small>Structure commerciale · contrats · opérations</small></article></div></section><FrenchFooter /></main>;
}

function FrenchQuote() {
  const [status,setStatus]=useState("idle"); const [message,setMessage]=useState("");
  const params=typeof window==="undefined"?new URLSearchParams():new URLSearchParams(window.location.search);
  const product=params.get("product")??"";
  const solutionAliases={"club-member-program":"Ensemble-cadeau de golf","private-label-collection":"Collection de marque privée","golf-tournament-gifts":"Articles pour tournoi de golf","corporate-golf-gifts":"Cadeaux de golf d'entreprise"};
  const prefilledProduct=product||solutionAliases[params.get("solution")]||"";
  const options=["Couvre-bâtons de golf personnalisés","Casquettes et visières de golf personnalisées","Serviettes de golf personnalisées","Accessoires de golf personnalisés","Ensembles-cadeaux de golf","Articles pour tournoi de golf","Cadeaux de golf d'entreprise","Collection de marque privée","Emballages de golf personnalisés"];
  const submit=async event=>{event.preventDefault();if(status==="submitting")return;const form=event.currentTarget;const data=new FormData(form);data.set("source",inquirySourceForLocation());data.set("page_language","fr-CA");data.set("page_path",window.location.pathname);data.set("page_url",window.location.href);if(data.get("company_website")){form.reset();setStatus("success");setMessage("Votre demande a été reçue.");return;}setStatus("submitting");setMessage("Envoi de votre demande…");try{const response=await fetch(import.meta.env.VITE_INQUIRY_ENDPOINT??"/api/inquiry",{method:"POST",body:data,headers:{Accept:"application/json"}});const result=await response.json().catch(()=>({}));if(!response.ok||!result.ok)throw new Error();form.reset();setStatus("success");setMessage("Merci. Notre équipe examinera votre projet et vous répondra avec la prochaine étape appropriée.");trackAnalytics("generate_lead",{form_name:"fr_ca_quote_page_project_brief",form_source:inquirySourceForLocation(),page_language:"fr-CA",page_path:window.location.pathname});}catch{setStatus("error");setMessage("L'envoi a échoué. Veuillez réessayer ou communiquer avec nous par courriel ou WhatsApp.");}};
  return <main className="zhoni-page quote-page fr-ca-page"><FrenchHeader active="quote" /><section className="quote-ledger-hero"><div className="quote-rail" aria-hidden="true"><strong>Z</strong><span>CUSTOM GOLF MERCHANDISE</span><i>BRANDED FOR A HIGHER STANDARD</i></div><div className="quote-ledger-main"><div className="quote-ledger-intro"><p>DEMANDE DE SOUMISSION</p><h1>Parlez-nous<br />de votre projet.</h1><p>D'un seul produit à un ensemble-cadeau complet, partagez les renseignements déjà disponibles.</p></div><form className="quote-ledger-form" onSubmit={submit}><fieldset><legend><b>01</b><span>COORDONNÉES<small>Indiquez la personne à contacter pour le suivi.</small></span></legend><div className="quote-form-row"><label>NOM<input required name="name" autoComplete="name" placeholder="Votre nom" /></label><label>COURRIEL PROFESSIONNEL<input required type="email" name="email" autoComplete="email" placeholder="vous@entreprise.com" /></label></div></fieldset><fieldset><legend><b>02</b><span>PROJET<small>Partagez l'essentiel; nous guiderons la suite.</small></span></legend><div className="quote-form-row"><label>PRODUIT OU TYPE DE PROJET<select required name="project_type" defaultValue={options.includes(prefilledProduct)?prefilledProduct:""}><option value="" disabled>Sélectionner un produit ou une catégorie</option>{options.map(option=><option key={option}>{option}</option>)}</select></label><label>QUANTITÉ ESTIMÉE<input name="quantity_range" placeholder="p. ex. 200 unités" /></label></div><label className="quote-project-details">DÉTAILS DU PROJET<textarea required name="message" rows="5" placeholder="Produit, personnalisation, date d'événement, destination ou besoins d'emballage." /></label></fieldset><label className="honeypot" aria-hidden="true">Website<input name="company_website" tabIndex="-1" autoComplete="off" /></label><TurnstileField /><button className="quote-submit" type="submit" disabled={status==="submitting"}>{status==="submitting"?"ENVOI…":"ENVOYER LE CAHIER DES CHARGES"} <Arrow /></button><div className={`quote-form-status ${status}`} role="status">{message}{status==="error"&&<> <a href="mailto:sales@zhonigolf.com">COURRIEL</a><a href={WHATSAPP_URL}>WHATSAPP</a></>}</div><small>Vos renseignements servent uniquement à examiner le projet et à vous répondre.</small></form></div></section><section className="quote-after-inquiry"><div><p>CONTACT DIRECT</p><h2>Vous pouvez aussi nous écrire<br />par courriel ou WhatsApp.</h2><div className="after-inquiry-actions"><a href="mailto:sales@zhonigolf.com"><span>COURRIEL</span><strong>sales@zhonigolf.com</strong><Arrow /></a><a href={WHATSAPP_URL}><span>WHATSAPP</span><strong>+86 177 5919 0848</strong><Arrow /></a></div></div></section><FrenchFooter /></main>;
}

export function CanadianFrenchSite({ routeKey }) {
  const pages={frCaHome:<FrenchHome />,frCaProducts:<FrenchProducts />,frCaSolutions:<FrenchSolutions />,frCaProcess:<FrenchProcess />,frCaFaq:<FrenchFaq />,frCaAbout:<FrenchAbout />,frCaQuote:<FrenchQuote />};
  return pages[routeKey] ?? <CanadianFrenchExpansion routeKey={routeKey} />;
}
