import { useState } from "react";
import { LanguageSwitcher } from "./locale.jsx";
import { LocalizedBuyerEvidence } from "./LocalizedBuyerEvidence.jsx";

const WHATSAPP_URL = import.meta.env.VITE_WHATSAPP_URL ?? "https://wa.me/8617759190848";
export const Arrow = () => <span aria-hidden="true">↗</span>;

export function GermanHeader({ active = "guides" }) {
  const [menu, setMenu] = useState(false);
  return <header className={`zhoni-header de-header ${menu ? "zhoni-header-open" : ""}`}><a className="zhoni-wordmark" href="/de/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><button className="zhoni-menu" onClick={() => setMenu(value => !value)} aria-expanded={menu}>{menu ? "SCHLIESSEN" : "MENÜ"}</button><nav aria-label="Hauptnavigation"><a href="/de/products/">PRODUKTE</a><a className={active === "solutions" ? "active" : ""} href="/de/solutions/">LÖSUNGEN</a><a className={active === "guides" ? "active" : ""} href="/de/guides/">RATGEBER</a><a href="/de/our-process/">ABLAUF</a><a href="/de/faq/">FAQ</a><a href="/de/about/">ÜBER UNS</a></nav><LanguageSwitcher /><a className="zhoni-header-cta" href="/de/request-a-quote/">ANFRAGE <Arrow /></a></header>;
}

export function GermanFooter() {
  return <footer className="site-footer"><div className="site-footer-main"><a className="zhoni-wordmark" href="/de/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><div className="site-footer-copy"><p>Personalisierte Golfartikel und Verpackungen für Clubs, Turniere, Unternehmen und Marken.</p><span>Produkt · Branding · Muster · Qualität · Verpackung · Übergabe</span><div className="site-footer-contact"><b>DIREKTER KONTAKT</b><a href="mailto:sales@zhonigolf.com">sales@zhonigolf.com</a><a href={WHATSAPP_URL}>WhatsApp +86 177 5919 0848 <Arrow /></a></div></div><nav><a href="/de/products/">Produkte</a><a href="/de/solutions/">Lösungen</a><a href="/de/guides/">Ratgeber</a><a href="/de/capabilities/">Leistungsumfang</a><a href="/de/first-order-guide/">Erstbestellung</a><a href="/de/our-process/">Ablauf</a><a href="/de/request-a-quote/">Anfrage <Arrow /></a></nav></div><div className="site-footer-base"><span>ZHONI · CUSTOM GOLF MERCHANDISE</span><span>Betreibergesellschaft: Xiamen Jindongyu Trading Co., Ltd.</span></div></footer>;
}

export function GermanBuyerGuide({ item, context }) {
  return <main className="zhoni-page guide-page de-page"><GermanHeader /><section className="guide-hero"><div><p>{item.label} · EINKAUFSRATGEBER</p><h1>{item.title}</h1><p>{item.intro}</p><small>ENTSCHEIDUNGSKRITERIEN · CHECKLISTE · EINKÄUFERFRAGEN</small></div><img src={item.image} alt={item.label} /></section><section className="guide-intro"><p>PRAKTISCHE EINKAUFSPRÜFUNG</p><h2>Die Punkte klären, die Angebot, Muster und Produktion beeinflussen.</h2><p>Die endgültigen Bedingungen hängen vom freigegebenen Produkt- und Projektumfang ab. Eine konkrete Ausgangsbasis macht MOQ, Preis, Musterweg, Qualität und Termin vergleichbar.</p></section><section className="guide-table"><table><thead><tr><th>PRÜFBEREICH</th><th>PRAKTISCHES ENTSCHEIDUNGSKRITERIUM</th></tr></thead><tbody>{item.rows.map(row => <tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td></tr>)}</tbody></table></section><LocalizedBuyerEvidence locale="de" context={context} /><section className="guide-decision"><div><p>PROJEKTVORBEREITUNG</p><h2>Bekannte Anforderungen und offene Entscheidungen trennen.</h2><p>Nicht jede Angabe muss bereits endgültig sein. Dokumentieren Sie feste Anforderungen, Präferenzen und Punkte, die der Lieferant fachlich einordnen soll.</p></div><aside><p>CHECKLISTE</p><h3>In den Projektbrief aufnehmen</h3><ul>{item.checklist.map(value => <li key={value}>{value}</li>)}</ul></aside></section><section className="guide-faq"><p>HÄUFIGE FRAGEN VON EINKÄUFERN</p><h2>Konkrete Antworten für die nächste Entscheidung.</h2><div>{item.faqs.map(([question,answer],index) => <article key={question}><b>{String(index + 1).padStart(2,"0")}</b><h3>{question}</h3><p>{answer}</p></article>)}</div></section><section className="guide-products"><p>VERBUNDENE PROJEKTWEGE</p><h2>Vom Ratgeber zum passenden Projektbrief.</h2><div><a href={item.related}>Passendes Produkt oder Lösung<Arrow /></a><a href="/de/products/">Produkte<Arrow /></a><a href="/de/solutions/">Lösungen<Arrow /></a><a href="/de/our-process/">Ablauf<Arrow /></a><a href="/de/request-a-quote/">Anfrage<Arrow /></a></div></section><GermanFooter /></main>;
}

export function GermanProjectHub({ item, context }) {
  const links = [...item.links, ["Produkte","/de/products/"], ["Lösungen","/de/solutions/"], ["Ablauf","/de/our-process/"], ["Projekt anfragen","/de/request-a-quote/"]].filter((entry,index,array) => array.findIndex(candidate => candidate[1] === entry[1]) === index);
  return <main className="zhoni-page guide-page de-page"><GermanHeader active={item.active} /><section className="guide-hero"><div><p>{item.label}</p><h1>{item.title}</h1><p>{item.intro}</p><a href="/de/request-a-quote/">PROJEKTBRIEF SENDEN <Arrow /></a></div><img src={item.image} alt={item.label} /></section><section className="guide-intro"><p>PROJEKTWEG</p><h2>Vier Schritte für eine belastbare Einkaufsentscheidung.</h2><p>Produkt, MOQ, Preis, Muster und Zeitplan werden anhand des tatsächlichen Projektumfangs bestätigt – nicht anhand pauschaler Annahmen.</p></section><section className="guide-products"><div>{item.steps.map(([number,title,copy]) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{copy}</p></article>)}</div></section><LocalizedBuyerEvidence locale="de" context={context} /><section className="guide-decision"><div><p>VORBEREITUNG</p><h2>Diese Angaben machen das nächste Gespräch konkreter.</h2><p>Ein Projektbrief ist noch keine Bestellung. Er verbindet den aktuellen Stand mit den Punkten, die technisch oder kaufmännisch geprüft werden müssen.</p></div><aside><p>CHECKLISTE</p><h3>Grundlegende Projektdaten</h3><ul>{item.checklist.map(value => <li key={value}>{value}</li>)}</ul></aside></section><section className="guide-products"><p>WEITERFÜHRENDE SEITEN</p><h2>Mit dem passenden Detailgrad fortfahren.</h2><div>{links.map(([label,href]) => <a href={href} key={href}>{label}<Arrow /></a>)}</div></section><GermanFooter /></main>;
}
