import { useState } from "react";
import { LocalizedBuyerEvidence } from "./LocalizedBuyerEvidence.jsx";
import { Arrow, GermanBuyerGuide, GermanFooter, GermanHeader } from "./GermanGuideLayout.jsx";
import { GermanProcurement } from "./GermanProcurement.jsx";

const guides = [
  ["gifts","event","GESCHENKE & EVENTS","Personalisierte Golfgeschenke als Projekt planen","/de/custom-golf-gifts/"],
  ["headcovers","product","PRODUKT & SPEZIFIKATION","Einkaufsratgeber für personalisierte Golf-Headcover","/de/guides/custom-golf-headcovers-procurement-guide/"],
  ["towels","product","PRODUKT & SPEZIFIKATION","Einkaufsratgeber für personalisierte Golfhandtücher","/de/guides/custom-golf-towels-procurement-guide/"],
  ["caps","product","PRODUKT & SPEZIFIKATION","Golfcaps und Visoren richtig spezifizieren","/de/guides/custom-golf-caps-and-visors/"],
  ["packaging","readiness","QUALITÄT & LIEFERUNG","Individuelle Golfverpackungen planen","/de/guides/custom-golf-packaging-procurement-guide/"],
  ["firstorder","procurement","MOQ & ERSTBESTELLUNG","Erste Bestellung, MOQ und Angebotsbasis","/de/first-order-guide/"],
  ["export","readiness","QUALITÄT & LIEFERUNG","Qualität, Verpackung und Exportbereitschaft","/de/quality-packaging-export-readiness/"],
  ["branding","product","BRANDING","Veredelungsmethoden für Golfartikel","/de/guides/branding-methods-for-premium-golf-merchandise/"],
  ["artwork","product","BRANDING","Logo- und Produktionsdaten vorbereiten","/de/guides/prepare-artwork-for-custom-golf-products/"],
  ["moq","procurement","MOQ & ERSTBESTELLUNG","Mindestmengen bei Golfartikeln verstehen","/de/guides/custom-golf-merchandise-moq-explained/"],
  ["quote","procurement","MOQ & ERSTBESTELLUNG","Einflussfaktoren auf ein Angebot","/de/guides/what-affects-a-custom-golf-merchandise-quote/"],
  ["quality","readiness","QUALITÄT & LIEFERUNG","Qualitätscheckliste für personalisierte Golfartikel","/de/guides/custom-golf-merchandise-quality-checklist/"],
  ["delivery","readiness","QUALITÄT & LIEFERUNG","Liefertermin rückwärts planen","/de/guides/how-to-plan-a-golf-merchandise-delivery-date/"],
  ["afterbrief","procurement","MOQ & ERSTBESTELLUNG","Was nach dem Projektbrief passiert","/de/guides/what-happens-after-a-custom-golf-project-brief/"],
  ["giftchoice","event","GESCHENKE & EVENTS","Das passende personalisierte Golfgeschenk wählen","/de/guides/how-to-choose-custom-golf-gifts/"],
  ["audience","event","GESCHENKE & EVENTS","Golfgeschenke nach Zielgruppe auswählen","/de/guides/how-to-choose-golf-gifts-by-audience/"],
  ["tournament","event","GESCHENKE & EVENTS","Player Packs für Golfturniere planen","/de/guides/golf-tournament-player-packs/"],
  ["corporate","event","GESCHENKE & EVENTS","Einkaufsratgeber für Golf-Firmengeschenke","/de/guides/corporate-golf-gifts-procurement-guide/"],
  ["headcovermaterials","product","PRODUKTENTWICKLUNG","Materialien für Headcover vergleichen","/de/guides/custom-golf-headcover-materials/"],
  ["headcovertypes","product","PRODUKTENTWICKLUNG","Headcover-Typen und Passformen","/de/guides/custom-golf-headcover-types/"],
  ["specification","product","PRODUKTENTWICKLUNG","Produktspezifikation erstellen","/de/guides/custom-golf-product-specification-sheet/"],
  ["sample","product","PRODUKTENTWICKLUNG","Muster systematisch freigeben","/de/guides/custom-golf-sample-approval-checklist/"],
  ["collection","product","PRODUKTENTWICKLUNG","Golfaccessoire-Kollektion koordinieren","/de/guides/coordinated-golf-accessory-collection/"],
  ["headcoverlogo","product","PRODUKTENTWICKLUNG","Logoanwendung auf Headcovern","/de/guides/headcover-logo-methods-and-placement/"],
  ["capmaterials","product","PRODUKTENTWICKLUNG","Gewebe für Golfcaps auswählen","/de/guides/custom-golf-cap-materials/"],
  ["caplogo","product","PRODUKTENTWICKLUNG","Logoposition und Stickerei auf Caps","/de/guides/custom-golf-cap-logo-placement/"],
  ["devbrief","product","PRODUKTENTWICKLUNG","Briefing für Produktentwicklung erstellen","/de/guides/custom-golf-product-development-brief/"],
  ["budget","event","GESCHENKE & EVENTS","Budget für Turniergeschenke planen","/de/guides/golf-tournament-gift-budget-planning/"],
  ["playerpack","event","GESCHENKE & EVENTS","Ein praktisches Player Pack zusammenstellen","/de/guides/how-to-build-a-golf-player-pack/"],
  ["roles","event","GESCHENKE & EVENTS","Geschenke für Teilnehmer, Sponsoren und Gewinner","/de/guides/tournament-gifts-sponsor-gifts-and-winner-prizes/"],
  ["premium","event","GESCHENKE & EVENTS","Ein hochwertiges Golf-Geschenkset entwickeln","/de/guides/how-to-build-a-premium-golf-gift-set/"],
  ["eventbrief","event","GESCHENKE & EVENTS","Briefing für ein Golf-Event erstellen","/de/guides/what-to-include-in-a-golf-event-brief/"],
  ["compare","procurement","MOQ & ERSTBESTELLUNG","Angebote für Golfartikel vergleichen","/de/guides/how-to-compare-custom-golf-product-quotes/"],
];

const initialGuides = {
  deHeadcoversGuide: { label:"PERSONALISIERTE GOLF-HEADCOVER", title:"Sechs Punkte, die vor dem Einkauf feststehen sollten", intro:"Schlägertyp, Passform, Material, Branding, Nummerierung und Verpackung bilden gemeinsam die Produktspezifikation.", image:"/assets/images/zhoni-product-headcovers-v3.png", related:"/de/custom-golf-headcovers/", rows:[["Schlägerserie","Mengen nach Driver, Fairwayholz, Hybrid sowie Blade- oder Mallet-Putter"],["Form & Passform","Schlägermaße, Öffnung, Länge und Haltesystem"],["Material","PU, Gewebe oder Strick nach Haptik, Haltbarkeit und Logoanwendung"],["Branding","Stickerei, Applikation, Prägung oder Patch je Panelfläche"],["Innenaufbau","Futter, Nähte, Kanten, Nummerierung und Handhabung"],["Verpackung","Einzelbeutel, Setbox, Label und Kombination mit weiteren Produkten"]], checklist:["Mengen je Schlägertyp","Form- und Materialreferenzen","Vektorlogo und Farbangaben","Verpackungswunsch","Empfangsdatum und Zielort"], faqs:[["Gilt für alle Headcover dieselbe MOQ?","Nein. Form, Material, Farben, Logoanwendung und Mengenverteilung je Typ beeinflussen die Produktionsbedingungen."],["Wann ist ein physisches Muster sinnvoll?","Bei neuer Konstruktion oder kritischer Passform ist ein Muster besonders wichtig. Der passende Freigabeweg wird projektbezogen festgelegt."],["Kann dasselbe Design auf Driver und Putter übertragen werden?","Ja, aber nicht einfach skaliert. Panelform und nutzbare Logofläche müssen je Schlägertyp angepasst werden."]] },
  deTowelsGuide: { label:"PERSONALISIERTE GOLFHANDTÜCHER", title:"Gewebe, Größe und Befestigung gemeinsam auswählen", intro:"Ein Golfhandtuch muss Feuchtigkeit aufnehmen, gut trocknen, sicher befestigt sein und das Logo lesbar tragen.", image:"/assets/images/zhoni-product-magnetic-towel-v4.png", related:"/de/custom-golf-towels/", rows:[["Einsatz","Golfbag, Cart, Player Pack oder Geschenkset"],["Gewebe","Waffelstruktur, Flächengewicht, Haptik, Saugfähigkeit und Trocknung"],["Größe","Nutzfläche, Faltvolumen und Gewicht am Befestigungspunkt"],["Befestigung","Magnet, Karabiner, Öse oder separater Clip"],["Logo","Stickgröße, Position, Garnfarbe und Einfluss auf die Rückseite"],["Verpackung","Banderole, Schutzbeutel, Karte oder Geschenkbox"]], checklist:["Gewünschte Abmessungen","Gewebe- und Farbreferenz","Magnet- oder Metallanforderung","Vektordatei für Stickerei","Weitere Artikel im Set"], faqs:[["Was ist bei einem magnetischen Golfhandtuch wichtig?","Magnetposition, Befestigung, Kontaktfläche, Handtuchgewicht und der tatsächliche Einsatz am Cart oder Schläger müssen zusammen geprüft werden."],["Sollte die Stickerei möglichst groß sein?","Nicht immer. Eine sehr große Stickfläche kann Flexibilität und Trocknung beeinflussen; Sichtbarkeit und Gebrauch müssen ausgewogen bleiben."],["Kann eine Bestellung auf mehrere Farben verteilt werden?","Das hängt von Gesamtmenge, Farbverfügbarkeit und Mengen je Farbe ab. Die Aufteilung sollte vor dem Angebot feststehen."]] },
  deCapsStyleGuide: { label:"PERSONALISIERTE GOLFCAPS & VISOREN", title:"Vor dem Stil zuerst die Tragebedingungen festlegen", intro:"Kronenform, Gewebe, Belüftung, Verschluss und Logoposition bestimmen gemeinsam Passform und Markenwirkung.", image:"/assets/images/zhoni-product-caps-v3.png", related:"/de/custom-golf-caps/", rows:[["Trägergruppe","Erwachsene, Jugendliche, Gruppenzusammensetzung und Größenbereich"],["Form","Strukturiert oder weich, niedriges oder mittleres Profil, Cap oder Visor"],["Einsatz","Heißes Klima, lange Golfrunde, Veranstaltung oder Alltag"],["Gewebe","Baumwolltwill, Polyester, Funktionsgewebe oder Mesh"],["Verschluss","Snapback, Schnalle, Klett oder Stretch-Fit"],["Branding","Frontstick, Patch sowie Seiten- und Rücklogo"]], checklist:["Referenzform für Cap oder Visor","Region und Saison","Größen- und Verschlussbedarf","Dateien je Logoposition","Menge und Veranstaltungstermin"], faqs:[["Braucht eine Golfcap immer Funktionsgewebe?","Bei Hitze und langer Tragezeit sind Leichtigkeit, Trocknung und Belüftung wichtig. Für Geschenkcharakter und Haptik kann Twill geeigneter sein."],["Ist 3D-Stick für jedes Logo geeignet?","Nein. Feine Linien, kleine Schrift und komplexe Details können als Flachstick oder Patch klarer wirken."],["Reicht eine Einheitsgröße?","Das hängt von Trägergruppe, Verschluss und tatsächlichem Verstellbereich ab. Auch Kronentiefe und Profil sollten geprüft werden."]] },
  dePackagingGuide: { label:"INDIVIDUELLE GOLFVERPACKUNG", title:"Produkt und Übergabe vor der Boxkonstruktion festlegen", intro:"Eine gute Verpackung präsentiert, fixiert, schützt beim Transport und lässt sich am Veranstaltungsort effizient ausgeben.", image:"/assets/images/zhoni-product-packaging-v3.png", related:"/de/custom-golf-packaging/", rows:[["Produktliste","Finale Zusammenstellung, Maße, Gewichte und empfindliche Komponenten"],["Boxkonstruktion","Kaschierte Box, Faltbox, Banderole und Öffnungsmechanik"],["Einsatz","Produktfixierung, Entnahmereihenfolge, Material und Austauschbarkeit"],["Branding","Druck, Folienprägung, Hoch- oder Tiefprägung, Label und Karte"],["Transportschutz","Abrieb, Druck, Feuchtigkeit und Kontakt von Metallteilen vermeiden"],["Versand","Umkarton, Stückzahl je Karton, Zielort und Übergabebedingungen"]], checklist:["Finale Produkte und Ist-Maße","Gewünschte Öffnungsfolge","Referenzen für Box und Einsatz","Druckdaten und Markenfarben","Zielland und Verteilmethode"], faqs:[["Kann die Box vor dem Produkt finalisiert werden?","Das ist nicht empfehlenswert. Änderungen an Produktmaß oder Anordnung können Einsatz und Außenmaß der Box beeinflussen."],["Ist eine kaschierte Premiumbox immer notwendig?","Nein. Bei Turnierausgabe, internationalem Transport, Lagerfläche oder Budget kann eine Faltbox oder Banderole geeigneter sein."],["Ist die Verpackungs-MOQ identisch mit der Produkt-MOQ?","Nicht zwingend. Konstruktion, Druck, Einsatz und Material können eigene Mindestmengen haben."]] },
};

function GuidesHub() {
  const [filter, setFilter] = useState("all");
  const groups = [["all","ALLE"],["product","PRODUKT & BRANDING"],["event","GESCHENKE & EVENTS"],["procurement","MOQ & ERSTBESTELLUNG"],["readiness","QUALITÄT & LIEFERUNG"]];
  return <main className="zhoni-page guides-page de-page"><GermanHeader /><section className="guides-hero"><div><p>GOLF MERCHANDISE BUYER GUIDES</p><h1>Einkaufsratgeber für personalisierte Golfartikel.</h1><p>Praktische Kriterien für Produktauswahl, Spezifikation, MOQ, Muster, Qualität, Verpackung und Lieferung.</p></div><aside><b>MIT DEM KONTEXT BEGINNEN</b><p>Wenn Empfänger, Anlass, Menge, Wunschtermin und Zielort bekannt sind, lassen sich Produkt und Projektweg realistischer eingrenzen.</p><a href="/de/request-a-quote/">PROJEKT ANFRAGEN <Arrow /></a></aside></section><section className="guide-filter" aria-label="Ratgeber filtern">{groups.map(([key,label]) => <button key={key} className={filter === key ? "active" : ""} onClick={() => setFilter(key)}>{label}</button>)}</section><section className="guide-catalog">{guides.filter(guide => filter === "all" || guide[1] === filter).map((guide,index) => <a href={guide[4]} key={guide[0]}><b>{String(index + 1).padStart(2,"0")}</b><span>{guide[2]}</span><h2>{guide[3]}</h2><p>Entscheidungskriterien, Checkliste und konkrete Fragen für den Projektbrief.</p><em>RATGEBER LESEN <Arrow /></em></a>)}</section><LocalizedBuyerEvidence locale="de" context="guides" /><section className="guide-decision"><div><p>EINKAUFSVORBEREITUNG</p><h2>Allgemeines Wissen mit dem konkreten Projekt verbinden.</h2><p>Produktidee, Menge, Markendaten, Wunschtermin und Lieferort machen MOQ, Musterweg und Angebotsumfang belastbar.</p></div><aside><p>GEMEINSAME BRIEFING-PUNKTE</p><ul>{["Empfänger und Einsatz","Produkt oder Referenzbild","Voraussichtliche Menge","Empfangsdatum und Zielort","Logo- und Verpackungsanforderungen"].map(item => <li key={item}>{item}</li>)}</ul></aside></section><GermanFooter /></main>;
}

export function GermanGuides({ routeKey }) {
  if (routeKey === "deGuides") return <GuidesHub />;
  if (initialGuides[routeKey]) return <GermanBuyerGuide item={initialGuides[routeKey]} context={`guide-${routeKey.replace("de", "").replace("Guide", "").toLowerCase()}`} />;
  return <GermanProcurement routeKey={routeKey} />;
}
