import { useState } from "react";
import { LanguageSwitcher } from "./locale.jsx";
import { LocalizedBuyerEvidence } from "./LocalizedBuyerEvidence.jsx";
import { GermanGuides } from "./GermanGuides.jsx";

const WHATSAPP_URL = import.meta.env.VITE_WHATSAPP_URL ?? "https://wa.me/8617759190848";
const Arrow = () => <span aria-hidden="true">↗</span>;

function Header({ active }) {
  const [menu, setMenu] = useState(false);
  return <header className={`zhoni-header de-header ${menu ? "zhoni-header-open" : ""}`}><a className="zhoni-wordmark" href="/de/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><button className="zhoni-menu" onClick={() => setMenu(value => !value)} aria-expanded={menu}>{menu ? "SCHLIESSEN" : "MENÜ"}</button><nav aria-label="Hauptnavigation"><a className={active === "products" ? "active" : ""} href="/de/products/">PRODUKTE</a><a className={active === "solutions" ? "active" : ""} href="/de/solutions/">LÖSUNGEN</a><a href="/de/guides/">RATGEBER</a><a href="/de/our-process/">ABLAUF</a><a href="/de/faq/">FAQ</a><a href="/de/about/">ÜBER UNS</a></nav><LanguageSwitcher /><a className="zhoni-header-cta" href="/de/request-a-quote/">ANFRAGE <Arrow /></a></header>;
}

function Footer() {
  return <footer className="site-footer"><div className="site-footer-main"><a className="zhoni-wordmark" href="/de/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><div className="site-footer-copy"><p>Personalisierte Golfartikel und Verpackungen für Clubs, Turniere, Unternehmen und Marken.</p><span>Produkt · Branding · Muster · Qualität · Verpackung · Übergabe</span><div className="site-footer-contact"><b>DIREKTER KONTAKT</b><a href="mailto:sales@zhonigolf.com">sales@zhonigolf.com</a><a href={WHATSAPP_URL}>WhatsApp +86 177 5919 0848 <Arrow /></a></div></div><nav><a href="/de/products/">Produkte</a><a href="/de/solutions/">Lösungen</a><a href="/de/guides/">Ratgeber</a><a href="/de/our-process/">Ablauf</a><a href="/de/faq/">FAQ</a><a href="/de/request-a-quote/">Anfrage <Arrow /></a></nav></div><div className="site-footer-base"><span>ZHONI · CUSTOM GOLF MERCHANDISE</span><span>Betreibergesellschaft: Xiamen Jindongyu Trading Co., Ltd.</span></div></footer>;
}

const categoryContent = {
  deHeadcovers: { eyebrow:"PERSONALISIERTE GOLF-HEADCOVER", brief:"Personalisierte Golf-Headcover", title:"Passgenauer Schutz mit klarer Markenwirkung.", intro:"Headcover für Driver, Fairwayholz, Hybrid und Putter werden nach Passform, Material, Logo, Nummerierung und Setaufbau spezifiziert.", image:"/assets/images/zhoni-product-headcovers-v3.png", alt:"Personalisiertes Golf-Headcover mit goldener Z-Stickerei", rows:[["Produkttypen","Driver · Fairwayholz · Hybrid · Blade- und Mallet-Putter"],["Materialien","PU, Kunstleder, Gewebe, Strick und kombinierte Konstruktionen"],["Logooptionen","Stickerei, Applikation, Prägung, Patch und Label"],["Prüfpunkte","Schlägerpassform, Öffnung, Futter, Nähte, Logoposition und Nummerierung"]], checklist:["Stückzahlen nach Schlägertyp","Referenz für Form, Material und Haptik","Vektorlogo und Markenfarben","Einzel- oder Setverpackung","Wunschtermin und Lieferort"] },
  deCaps: { eyebrow:"PERSONALISIERTE GOLFCAPS & VISOREN", brief:"Personalisierte Golfcaps & Visoren", title:"Markenpräsenz, die über die Runde hinaus wirkt.", intro:"Caps und Visoren für Turniere, Clubs und Firmenprogramme werden auf Trägergruppe, Klima, Gewebe, Passform und Logoanwendung abgestimmt.", image:"/assets/images/zhoni-product-caps-v3.png", alt:"Personalisierte Golfcap und Visor mit goldener Stickerei", rows:[["Formen","Strukturierte und unstrukturierte Caps · Performance-Caps · Visoren · Mesh"],["Gewebe","Baumwolltwill, Polyester, Funktionsgewebe und Mesh"],["Logooptionen","Flach- oder 3D-Stick, Web- oder Gummipatch, Seiten- und Rücklogo"],["Prüfpunkte","Krone, Schirm, Schweißband, Verschluss und Größenbereich"]], checklist:["Trägergruppe, Region und Saison","Gewünschte Cap- oder Visorform","Gewebeeigenschaften und Farben","Logoangaben für Vorderseite, Seite und Rückseite","Menge, Empfangsdatum und Zielort"] },
  deTowels: { eyebrow:"PERSONALISIERTE GOLFHANDTÜCHER", brief:"Personalisierte Golfhandtücher", title:"Praktische Platzfunktion mit durchdachtem Markendetail.", intro:"Waffelstruktur, Magnet, Karabiner, Größe und Stickerei werden gemeinsam auf die Nutzung am Bag, Cart oder im Geschenkset abgestimmt.", image:"/assets/images/zhoni-product-magnetic-towel-v4.png", alt:"Magnetisches Golfhandtuch mit goldener Stickerei", rows:[["Ausführungen","Waffel · Magnetisch · Mit Karabiner · Für Geschenksets"],["Materialien","Mikrofaser-Waffel, Baumwolle und projektspezifische Alternativen"],["Logooptionen","Stickerei, Weblabel, Druck und Verpackungskarte"],["Prüfpunkte","Größe, Flächengewicht, Kanten, Magnet oder Karabiner und Formstabilität"]], checklist:["Einsatzzweck und Wunschgröße","Gewebe- und Farbreferenz","Stickgröße und Position","Magnet- oder Karabineranforderung","Einzelverpackung oder Setzusammenstellung"] },
  deAccessories: { eyebrow:"PERSONALISIERTE GOLFACCESSOIRES", brief:"Personalisierte Golfaccessoires", title:"Kleine Produkte mit einer klaren Rolle im Projekt.", intro:"Ballmarker, Pitchgabeln, Hat Clips, Bag Tags und Taschen werden für Player Packs, Firmengeschenke und Mitgliederprogramme funktional zusammengestellt.", image:"/assets/images/zhoni-product-accessories-v3.png", alt:"Personalisierte Golfaccessoires mit goldener Z-Marke", rows:[["Produkte","Ballmarker · Pitchgabeln · Hat Clips · Bag Tags · Taschen"],["Materialien","Metall, PU, Gewebe und produktspezifische Materialkombinationen"],["Logooptionen","Gravur, Emaille, Prägung, Stickerei und Druck"],["Prüfpunkte","Größe, Metallfinish, Kanten, Teilekombination und Einzelverpackung"]], checklist:["Zielgruppe und Verwendungszweck","Produktmix und Mengen je Artikel","Material- oder Metallfinish","Logodetails, Linienbreiten und Farben","Anforderung an Setverpackung"] },
  dePackaging: { eyebrow:"INDIVIDUELLE GOLFVERPACKUNG", brief:"Individuelle Golfverpackung", title:"Nicht nur das Produkt – auch der Übergabemoment zählt.", intro:"Geschenkbox, Einsatz, Banderole, Karte und Transportschutz werden nach Produktmix, Markenwirkung und tatsächlichem Lieferweg geplant.", image:"/assets/images/zhoni-product-packaging-v3.png", alt:"Individuelle Golf-Geschenkbox mit Einsatz und goldener Z-Marke", rows:[["Konstruktion","Faltbox · Kaschierte Box · Banderole · Produktspezifischer Einsatz"],["Oberfläche","Druck, Folienprägung, Hoch- oder Tiefprägung und Label"],["Innenaufbau","EVA, Karton, Gewebe, Polsterung und sichere Produktfixierung"],["Prüfpunkte","Produktmaße, Öffnungsfolge, Schutz, Kartoneffizienz und Versandweg"]], checklist:["Finale Produktliste für die Box","Produktmaße und gewünschte Anordnung","Markenfarben und Vektorlogo","Karten-, Banderolen- oder Labelbedarf","Zielort und Anforderungen an Umkartons"] },
};

function CategoryPage({ pageKey }) {
  const content = categoryContent[pageKey];
  return <main className="zhoni-page category-page de-page"><Header active="products" /><section className="category-hero"><aside className="category-rail" aria-hidden="true"><strong>Z</strong><span>CUSTOM GOLF PRODUCTS</span></aside><div className="category-intro"><p>{content.eyebrow}</p><h1>{content.title}</h1><p>{content.intro}</p><a href={`/de/request-a-quote/?product=${encodeURIComponent(content.brief)}`}>DIESES PRODUKT ANFRAGEN <Arrow /></a><small>CLUBS · TURNIERE · UNTERNEHMEN · MARKEN</small></div><img src={content.image} alt={content.alt} /></section><section className="guide-table"><table><thead><tr><th>PRÜFBEREICH</th><th>PRAKTISCHE PRODUKTRICHTUNG</th></tr></thead><tbody>{content.rows.map(row => <tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td></tr>)}</tbody></table></section><LocalizedBuyerEvidence locale="de" context={`product-${pageKey.replace("de", "").toLowerCase()}`} /><section className="guide-decision"><div><p>PROJEKTVORBEREITUNG</p><h2>Vor dem Preisvergleich dieselbe Spezifikationsbasis schaffen.</h2><p>MOQ, Preis, Muster und Lieferzeit richten sich nach Konstruktion, Individualisierung, Menge, Verpackung und Zielort.</p></div><aside><p>EINKÄUFER-CHECKLISTE</p><h3>Diese Angaben gehören in den Projektbrief</h3><ul>{content.checklist.map(item => <li key={item}>{item}</li>)}</ul></aside></section><section className="guide-products"><p>VERBUNDENE PROJEKTWEGE</p><h2>Von der Produktprüfung zum konkreten Brief.</h2><div><a href="/de/products/">Alle Produkte<Arrow /></a><a href="/de/solutions/">Lösungen nach Anlass<Arrow /></a><a href="/de/our-process/">Unser Ablauf<Arrow /></a><a href={`/de/request-a-quote/?product=${encodeURIComponent(content.brief)}`}>Anfrage senden<Arrow /></a></div></section><section className="guide-close"><div><p>PROJEKT BEREIT ZUR PRÜFUNG?</p><h2>Teilen Sie Produkt, Menge und gewünschtes Empfangsdatum.</h2><a href={`/de/request-a-quote/?product=${encodeURIComponent(content.brief)}`}>PROJEKTBRIEF SENDEN <Arrow /></a></div><img src={content.image} alt={content.alt} /></section><Footer /></main>;
}

const solutionContent = {
  deTournamentGifts: { label:"GOLFTURNIER-GESCHENKE & PLAYER PACKS", title:"Für jede Empfängerrolle das passende Turniergeschenk.", intro:"Teilnehmer, Sponsoren, VIPs, Helfer und Gewinner brauchen nicht automatisch dieselben Produkte oder dieselbe Präsentation.", image:"/assets/images/zhoni-golf-tournament-gift-delivery-v2.png", solution:"golf-tournament-gifts", steps:[["01","Empfängergruppen trennen","Teilnehmer, Sponsoren, VIPs, Organisation und Gewinner nach ihrer Rolle aufteilen."],["02","Produkte funktional wählen","Nutzung auf dem Platz, Budgetrichtung und einfache Vor-Ort-Ausgabe berücksichtigen."],["03","Branding und Verpackung abstimmen","Turnierlogo, Sponsorensichtbarkeit, Kennzeichnung und Verteilung gemeinsam planen."],["04","Vom Turniertag rückwärts planen","Zeit für Datenfreigabe, Muster, Produktion, Verpackung und Transport einrechnen."]], products:"Magnetische Handtücher, Caps, Ballmarker, Pitchgabeln, Taschen und Geschenkboxen können je Empfängergruppe kombiniert werden.", faqs:[["Brauchen alle Teilnehmer dasselbe Geschenk?","Nein. Ein gemeinsamer Grundartikel kann das Turnier verbinden, während VIPs oder Gewinner über Produktwahl oder Verpackung differenziert werden."],["Wie viele Artikel gehören in ein Player Pack?","Nicht die Anzahl, sondern die Funktion entscheidet. Ein starkes Hauptprodukt und ein sinnvoller Begleiter können bereits ein geschlossenes Pack bilden."],["Kann direkt zum Veranstaltungsort geliefert werden?","Zieladresse, Ansprechpartner, Annahmezeit, Lagerung, Verteilung und Reservemenge sollten früh bestätigt werden."]] },
  deCorporateGifts: { label:"GOLF-FIRMENGESCHENKE", title:"Firmengeschenke passend zu Beziehung und Übergabemoment.", intro:"Für Kunden, Führungskräfte, Mitarbeitende und Partner werden Wertigkeit, Markenpräsenz und Präsentation zuerst definiert.", image:"/assets/images/zhoni-custom-golf-packaging-v2.png", solution:"corporate-golf-gifts", steps:[["01","Empfänger definieren","Kunden, Führungskräfte, Teams, Partner und Veranstaltungsgäste unterscheiden."],["02","Geschenkniveau festlegen","Praktisches Einzelprodukt oder hochwertig inszeniertes Set auswählen."],["03","Markenwirkung dosieren","Logogröße und Veredelung nach Beziehung, Produkt und Nutzung wählen."],["04","Übergabe vorbereiten","Karte, Einzelverpackung, Lieferadressen und Empfangsdatum bestätigen."]], products:"Headcover, Caps, Handtücher, Metallaccessoires und individuelle Boxen lassen sich zu einem abgestimmten Firmengeschenk verbinden.", faqs:[["Soll das Firmenlogo möglichst groß sein?","Bei hochwertigen Geschenken kann eine kleinere, präzise Ausführung überzeugender wirken. Die passende Sichtbarkeit hängt von Empfänger und Nutzung ab."],["Sind Lieferungen an mehrere Adressen möglich?","Adressanzahl, Einzelverpackung, Datenformat und Zielländer müssen vorab als Projektumfang geklärt werden."],["Was eignet sich für Empfänger, die nicht aktiv Golf spielen?","Alltagstaugliche Caps, Taschen, Handtücher und präsentationsstarke Accessoires können breiter nutzbar sein."]] },
  deClubMemberPrograms: { label:"MITGLIEDERPROGRAMME FÜR GOLFCLUBS", title:"Von einzelnen Präsenten zu einem wiederholbaren Mitgliederprogramm.", intro:"Eintritt, Verlängerung, Jubiläum und Mitgliederturnier werden über gemeinsame Produkt- und Markenregeln verbunden.", image:"/assets/images/zhoni-golf-product-development-v2.png", solution:"club-member-programs", steps:[["01","Mitgliedermomente definieren","Eintritt, Verlängerung, Jubiläum, Clubturnier und besondere Statusstufen trennen."],["02","Gruppen und Mengen planen","Neue, bestehende, junge und veranstaltungsbezogene Mitglieder erfassen."],["03","Produktsystem aufbauen","Hauptprodukt, ergänzende Artikel und wiederverwendbare Markenregeln festlegen."],["04","Freigabedaten sichern","Logo, Farben, Spezifikation, Verpackung und Freigabestand für Folgerunden dokumentieren."]], products:"Caps, Visoren, Headcover, magnetische Handtücher, Bag Tags, Taschen und Mitgliederverpackungen können nach Anlass gestaffelt werden.", faqs:[["Kann ein Programm mehrere Mitgliedermomente abdecken?","Ja. Eine gemeinsame Markenlogik bleibt bestehen, während Produkt, Karte oder Verpackungsniveau Eintritt, Jubiläum und Veranstaltung unterscheiden."],["Muss jedes Jahr dasselbe Produkt nachbestellt werden?","Nein. Kernprodukte können beibehalten und saisonal oder nach Mitgliederstufe ergänzt werden."],["Können Pro-Shop-Produkte mitgeplant werden?","Ja, wenn Verkaufsware und Mitgliederartikel bei Menge, Kennzeichnung, Verpackung und kaufmännischen Bedingungen getrennt beschrieben werden."]] },
  dePrivateLabelCollections: { label:"PRIVATE-LABEL-GOLFKOLLEKTIONEN", title:"Nicht nur ein Produkt mit Logo, sondern ein erweiterbares Sortiment.", intro:"Produktarchitektur, Spezifikation, Markenregeln, Verpackung und Freigabedaten schaffen die Basis für Erweiterungen und Nachbestellungen.", image:"/assets/images/zhoni-golf-collection-hero-v2.png", solution:"private-label-collections", steps:[["01","Sortimentsrollen bestimmen","Leitprodukt, dauerhafte Kernartikel und ergänzende Accessoires definieren."],["02","Spezifikationen dokumentieren","Material, Maße, Komponenten, Farben und Qualitätsmerkmale je Produkt festhalten."],["03","Markenregeln anwenden","Logoposition, Größe, Label, Metallfinish und Verpackung als System planen."],["04","Freigaben und Erweiterung steuern","Finale Daten, Musterkommentare und freigegebene Versionen für Folgeprodukte nutzen."]], products:"Headcover, Caps, Handtücher, Taschen, Metallaccessoires und Verpackungen können schrittweise unter einer gemeinsamen Markenlogik entwickelt werden.", faqs:[["Kann die Kollektion mit einem Leitprodukt starten?","Ja. Ein erstes Produkt kann Material-, Farb-, Logo- und Verpackungsregeln definieren, die spätere Erweiterungen erleichtern."],["Müssen alle Produkte dasselbe Material verwenden?","Nein. Produktspezifische Materialien lassen sich über Farbe, Logohierarchie, Label und Finish visuell verbinden."],["Welche Daten sind für Nachbestellungen wichtig?","Freigegebene Spezifikation, finale Artwork-Dateien, Farbstandard, Komponenten, Verpackungsdaten und Änderungshistorie sollten je Produkt geführt werden."]] },
};

function SolutionPage({ pageKey }) {
  const content = solutionContent[pageKey];
  return <main className="zhoni-page corporate-page de-page"><Header active="solutions" /><section className="corporate-hero"><aside className="corporate-rail" aria-hidden="true"><strong>Z</strong><span>GOLF GIFT SOLUTIONS</span></aside><div><p>{content.label}</p><h1>{content.title}</h1><p>{content.intro}</p><a href={`/de/request-a-quote/?solution=${content.solution}&source=${content.solution}`}>PROJEKT ANFRAGEN <Arrow /></a></div><img src={content.image} alt={content.label} /></section><section className="corporate-ledger"><div><p>PLANUNGSWEG</p>{content.steps.map(([number,title,copy]) => <article key={number}><b>{number}</b><h2>{title}</h2><p>{copy}</p><span>→</span></article>)}</div><aside><p>WICHTIGE AUSGANGSDATEN</p><ul><li><b>Empfänger</b><span>Wer erhält die Artikel und wie viele Personen sind es?</span></li><li><b>Termin</b><span>Veranstaltungs- oder gewünschtes Empfangsdatum</span></li><li><b>Zielort</b><span>Land, Stadt und Verteilpunkte</span></li><li><b>Markendaten</b><span>Logo, Farben und Referenzbilder</span></li><li><b>Verpackung</b><span>Einzelpräsentation oder Setaufbau</span></li></ul></aside></section><LocalizedBuyerEvidence locale="de" context={content.solution} /><section className="corporate-closing"><img src="/assets/images/zhoni-golf-product-development-v2.png" alt="Prüfung der Markenanwendung auf personalisierten Golfartikeln" /><div><p>COORDINATED GOLF MERCHANDISE</p><h2>Die Rolle des Geschenks vor der Produktwahl definieren.</h2><p>{content.products}</p><a href="/de/products/">PRODUKTE ENTDECKEN <Arrow /></a></div></section><section className="guide-faq"><p>HÄUFIGE FRAGEN VON EINKÄUFERN</p><h2>Antworten für eine konkretere Projektentscheidung.</h2><div>{content.faqs.map(([question,answer],index) => <article key={question}><b>{String(index + 1).padStart(2,"0")}</b><h3>{question}</h3><p>{answer}</p></article>)}</div></section><section className="guide-products"><p>VERBUNDENE PROJEKTWEGE</p><h2>Mit dem passenden Detailgrad fortfahren.</h2><div><a href="/de/products/">Personalisierte Produkte<Arrow /></a><a href="/de/custom-golf-packaging/">Individuelle Verpackung<Arrow /></a><a href="/de/our-process/">Unser Ablauf<Arrow /></a><a href={`/de/request-a-quote/?solution=${content.solution}&source=${content.solution}`}>Anfrage senden<Arrow /></a></div></section><Footer /></main>;
}

export function GermanExpansion({ routeKey }) {
  if (categoryContent[routeKey]) return <CategoryPage pageKey={routeKey} />;
  if (solutionContent[routeKey]) return <SolutionPage pageKey={routeKey} />;
  return <GermanGuides routeKey={routeKey} />;
}
