import { useState } from "react";
import { LanguageSwitcher } from "./locale.jsx";
import { LocalizedBuyerEvidence } from "./LocalizedBuyerEvidence.jsx";

const Arrow = () => <span aria-hidden="true">↗</span>;
const WHATSAPP_URL = import.meta.env.VITE_WHATSAPP_URL ?? "https://wa.me/8617759190848";

function Header() {
  const [menu,setMenu] = useState(false);
  return <header className={`zhoni-header ja-header ${menu ? "zhoni-header-open" : ""}`}><a className="zhoni-wordmark" href="/ja/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><button className="zhoni-menu" onClick={() => setMenu(value => !value)} aria-expanded={menu}>{menu ? "閉じる" : "メニュー"}</button><nav aria-label="メインナビゲーション"><a href="/ja/products/">製品</a><a href="/ja/solutions/">ソリューション</a><a className="active" href="/ja/guides/">購入ガイド</a><a href="/ja/our-process/">進め方</a><a href="/ja/faq/">FAQ</a><a href="/ja/about/">会社情報</a></nav><LanguageSwitcher /><a className="zhoni-header-cta" href="/ja/request-a-quote/">プロジェクト相談 <Arrow /></a></header>;
}

function Footer() {
  return <footer className="site-footer"><div className="site-footer-main"><a className="zhoni-wordmark" href="/ja/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><div className="site-footer-copy"><p>クラブ、大会、企業、ブランド向けのカスタムゴルフ用品プロジェクト。</p><span>製品開発 · ロゴ · ギフト · 品質 · パッケージ · 納品</span><div className="site-footer-contact"><b>直接のお問い合わせ</b><a href="mailto:sales@zhonigolf.com">sales@zhonigolf.com</a><a href={WHATSAPP_URL}>WhatsApp +86 177 5919 0848 <Arrow /></a></div></div><nav><a href="/ja/products/">製品</a><a href="/ja/solutions/">ソリューション</a><a href="/ja/guides/">購入ガイド</a><a href="/ja/capabilities/">対応範囲</a><a href="/ja/first-order-guide/">初回注文</a><a href="/ja/our-process/">進め方</a><a href="/ja/request-a-quote/">お問い合わせ <Arrow /></a></nav></div><div className="site-footer-base"><span>ZHONI · CUSTOM GOLF MERCHANDISE</span><span>運営法人: Xiamen Jindongyu Trading Co., Ltd.</span></div></footer>;
}

const content = {
  jaGolfGiftGuide: { group:"ギフト選定", title:"カスタムゴルフギフトは、製品より目的から選ぶ", intro:"良いゴルフギフトはロゴ入りの商品ではなく、受取人、使用場面、手渡す瞬間に合う製品です。", image:"/assets/images/zhoni-product-gift-sets-v3.png", rows:[["受取人","顧客、会員、選手、社員、スポンサー、VIP"],["贈る目的","感謝、歓迎、記念、表彰、ブランド体験"],["製品方向","実用的な単品、または役割のある複数製品セット"],["ブランドの強さ","目立つイベントロゴ、または控えめな企業表現"],["渡し方","現地配布、個別配送、プレミアムパッケージ"]], check:["受取人と人数","イベント・プログラムの目的","予定数量と予算の方向","希望受取日と納品先","ロゴとパッケージ要件"], faq:[["一つの製品でも良いギフトになりますか？","はい。使用価値が高く、適切にブランド表現された主力製品一つが、役割のない多数の製品より効果的な場合があります。"],["予算は最初に伝えるべきですか？","正確な金額でなくても、製品とパッケージの水準を判断できる範囲があると検討しやすくなります。"]], related:"/ja/custom-golf-gifts/" },
  jaAudienceGiftGuide: { group:"ギフト選定", title:"受取人によって、ゴルフギフトの役割は変わる", intro:"顧客、大会参加者、クラブ会員、VIPでは、同じゴルフ用品でも期待される実用性と表現水準が異なります。", image:"/assets/images/zhoni-golf-tournament-gift-delivery-v2.png", rows:[["顧客・パートナー","関係性とブランドの品位を示す控えめな構成"],["大会参加者","現場ですぐ使え、携帯しやすい製品"],["クラブ会員","反復使用と所属感を考えた一貫した製品"],["VIP・役員","素材、仕上げ、開封体験が明確なセット"],["運営・ボランティア","識別性、実用性、配布効率を優先"]], check:["受取グループ別の人数","各グループにおけるギフトの役割","共通製品と差別化製品","ロゴ露出の水準","配布・配送方法"], faq:[["すべての受取人に同じギフトが必要ですか？","イベントの一貫性を保ちながら、製品、包装、メッセージカードでグループごとの役割を分けられます。"],["ゴルフをしない受取人も考慮できますか？","日常でも使える帽子、ポーチ、タオル、ギフト向けアクセサリーを検討できます。"]], related:"/ja/solutions/" },
  jaTournamentGuide: { group:"ゴルフ大会", title:"Player Packは参加者の一日を基準に構成する", intro:"受付からラウンド、表彰、帰宅まで、参加者がいつ製品を受け取り使うかを考えると構成が明確になります。", image:"/assets/images/zhoni-golf-tournament-gift-delivery-v2.png", rows:[["受付・歓迎","配布しやすく、その場で内容を確認できる包装"],["ラウンド前","帽子、タオル、ボールマーカーなどすぐ使える製品"],["プレー中","携帯性、天候、ゴルフバッグへの取り付けを考慮"],["表彰・交流","受賞者、スポンサー、VIP向けに別の水準を設定"],["イベント後","繰り返し使い、イベントとブランドを思い出せる製品"]], check:["参加人数とグループ","イベント形式と日程","現地配布場所","スポンサーLogoのルール","配送・保管スペース"], faq:[["Player Packには何点が適切ですか？","点数より各製品の役割が重要です。主力製品一つと補助アクセサリーでも一貫した構成になります。"],["大会当日にセットを組んでもよいですか？","不足や配布遅延を減らすため、事前にセット組みと数量確認を完了する方が安全です。"]], related:"/ja/solutions/golf-tournament-gifts/" },
  jaCorporateGuide: { group:"企業ギフト", title:"企業向けゴルフギフトは、関係性とブランドの強さを調整する", intro:"顧客への感謝と社員向けギフトでは、同じ製品でもロゴサイズ、素材、パッケージの適切な水準が異なります。", image:"/assets/images/zhoni-custom-golf-packaging-v2.png", rows:[["関係性","新規顧客、長期パートナー、役員、社内チーム"],["場面","感謝、契約記念、イベント、表彰、季節の贈り物"],["製品水準","実用的な単品、組み合わせセット、プレミアムボックス"],["ブランド表現","企業ロゴ、共同ブランド、個別メッセージ"],["引き渡し","イベント、オフィス一括、複数住所への配送"]], check:["受取人の役職と関係","企業ブランドガイド","製品と包装の水準","カード文言と個別対応","納品先数と日程"], faq:[["企業ロゴは大きく入れる方が良いですか？","高級ギフトでは小さく精度の高い表現が適する場合があります。使用場面と関係性から判断してください。"],["複数住所へ配送できますか？","可否、包装、住所データ形式は、数量、目的地、プロジェクト範囲に基づいて事前確認が必要です。"]], related:"/ja/solutions/corporate-golf-gifts/" },
  jaHeadcoverMaterialsGuide: { group:"ヘッドカバー開発", title:"素材は触感だけでなく、構造とロゴ表現も決める", intro:"見た目だけで比べず、保護性、形状保持、縫製、ロゴ方法に与える影響を確認します。", image:"/assets/images/zhoni-product-headcovers-v3.png", rows:[["PU・合成皮革","輪郭を出しやすく、刺繍、型押し、アップリケなどの選択肢が広い"],["織物","色と触感の幅が広く、カジュアルまたはスポーティな表現に向く"],["ニット","柔らかく伝統的な印象。番手表示、リブ、ポンポン構造を確認"],["複合素材","パネルごとの役割と視覚的なコントラストを作れる"],["裏地・中材","クラブ保護、フィット、厚み、着脱感に直接影響"]], check:["希望する触感と形状","使用頻度と環境","ロゴ方法","クラブ別のフィット","お手入れと包装条件"], faq:[["天然皮革は常に最良ですか？","高級感はありますが、管理、色の一貫性、価格、数量、使用環境を一緒に検討する必要があります。"],["写真だけで素材を確定できますか？","質感、厚み、柔軟性が重要な場合は、素材スワッチまたは実物サンプルの確認がより安全です。"]], related:"/ja/custom-golf-headcovers/" },
  jaHeadcoverTypesGuide: { group:"ヘッドカバー開発", title:"クラブタイプごとに、必要な構造とフィットは異なる", intro:"ドライバー、フェアウェイ、ハイブリッド、パターの外観を揃えても、型紙と使用方法は個別に検討します。", image:"/assets/images/zhoni-product-headcovers-v3.png", rows:[["ドライバー","大きなヘッド、広いロゴ面、安定した開口部"],["フェアウェイ","番手表示とドライバーとの差が分かるサイズ設計"],["ハイブリッド","小さな形状、クラブ識別、シリーズとしての統一性"],["ブレードパター","細身のフィット、開閉、保護構造"],["マレットパター","形状別パターン、ネック方向、マグネット位置"]], check:["クラブタイプ別の数量","右用・左用の方向","番手またはラベル","開閉方法","セットパッケージ"], faq:[["一つの型で全ブランドのクラブに合いますか？","ある程度の汎用設計は可能ですが、特にパターは形状差が大きいため、対象モデルと寸法の確認が必要です。"],["タイプごとに色を変えられますか？","可能性はありますが、素材色の条件とタイプ別数量配分がMOQに与える影響を確認します。"]], related:"/ja/custom-golf-headcovers/" },
  jaProductSpecificationGuide: { group:"製品開発", title:"仕様書は参考画像を、製造可能な基準に変える", intro:"製品名だけでは同じ見積もりやサンプルを作れません。寸法、素材、部品、ロゴ、包装の基準を文書化します。", image:"/assets/images/zhoni-material-direction-v1.png", rows:[["基本情報","製品名、用途、版番号、担当者、更新日"],["寸法・許容範囲","測定位置、単位、重要寸法、機能に関わる許容差"],["素材・色","材質、目付・厚み、表面、色基準"],["構造・部品","パネル、縫製、マグネット、ファスナー、バックル、金属部品"],["ロゴ・包装","ファイル、位置、サイズ、加工方法、個装、外装"]], check:["寸法図","素材の参考","部品一覧","ロゴ配置図","品質と包装の基準"], faq:[["仕様書は誰が作成しますか？","購入者が目的と必須条件を示し、供給側と一緒に製造可能な詳細へ整理する方法が実務的です。"],["すべての寸法に許容差が必要ですか？","まず機能、フィット、外観に影響する重要寸法を優先して定義します。"]], related:"/ja/first-order-guide/" },
  jaSampleApprovalGuide: { group:"製品開発", title:"サンプル承認は「見た目が良い」より具体的に", intro:"承認サンプルは量産時の基準になります。寸法、機能、素材、ロゴ、包装まで記録します。", image:"/assets/images/zhoni-quality-inspection-v1.png", rows:[["形状・寸法","仕様書、測定位置、フィット、対称性"],["素材・色","触感、厚み、光沢、承認色との比較"],["機能","開閉、マグネット、クリップ、着用、実使用"],["ロゴ・仕上げ","サイズ、位置、鮮明さ、縫製、端部"],["パッケージ","構成、ラベル、インサート、保護状態"]], check:["承認・修正・保留を明記","写真と測定値を記録","修正項目を番号化","再確認が必要な項目","承認者と日付"], faq:[["サンプル写真だけで承認できますか？","色、触感、フィット、機能が重要な製品では実物確認の方が適切な場合があります。"],["修正後に再度サンプルを確認すべきですか？","機能や外観に重要な変更であれば、変更箇所を再確認する方が安全です。"]], related:"/ja/our-process/" },
  jaCollectionPlanningGuide: { group:"コレクション開発", title:"製品数を増やすより、共通のデザインルールを作る", intro:"同じロゴを付けるだけではコレクションになりません。対象、製品の役割、共通のデザインシステムを定めます。", image:"/assets/images/zhoni-golf-collection-hero-v2.png", rows:[["共通目的","大会、会員プログラム、企業ギフト、販売コレクション"],["主力製品","プロジェクトの価値と印象を担う中心製品"],["補助製品","使用場面を広げる実用アクセサリー"],["デザインシステム","色、ロゴサイズ、素材、金属仕上げのルール"],["パッケージ","製品の順序と手渡す瞬間を整える構造"]], check:["受取人と目的","主力製品の選定","製品ごとの役割","共通要素と個別要素","目標価格帯と数量"], faq:[["すべての製品を同じ色にすべきですか？","同色だけでなく、補色や繰り返す金属仕上げ、ロゴ階層でも統一感を作れます。"],["製品数は多いほど良いですか？","いいえ。役割が不明な構成品より、用途が明確な少数の製品の方が強い体験になります。"]], related:"/ja/solutions/golf-club-member-programs/" },
  jaHeadcoverLogoGuide: { group:"ヘッドカバー開発", title:"ロゴ位置は平面図ではなく、クラブ装着時に判断する", intro:"曲面、縫い目、開口部は実際の視認性に影響します。素材とパネル構造を先に確認します。", image:"/assets/images/zhoni-product-headcovers-v3.png", rows:[["前面パネル","視認性が高い。曲面による歪みと中心線を確認"],["側面パネル","補助ロゴ、番手、製品区分に利用"],["上面・ネック","小さなシンボルや反復ディテールに適する"],["刺繍・アップリケ","質感と色表現、最小線幅の制約を確認"],["型押し・パッチ","控えめな表現、または複雑なロゴの代替"]], check:["完成サイズ","パネル別の位置図","最小線幅と文字","糸色と素材色","左右方向の確認"], faq:[["大きなロゴほど鮮明ですか？","曲面やパネル境界を越えると歪むため、使用できる面の中で比率を調整する必要があります。"],["パターカバーも同じ位置を使えますか？","形状と開閉方向が異なるため、別途配置を確認します。"]], related:"/ja/custom-golf-headcovers/" },
  jaCapsMaterialsGuide: { group:"ゴルフ帽子開発", title:"帽子の生地は気候と着用時間から選ぶ", intro:"コットンの触感、機能素材の速乾性、メッシュの通気性は、それぞれ異なる使用場面に向きます。", image:"/assets/images/zhoni-product-caps-v3.png", rows:[["コットンツイル","馴染みのある触感と形状。日常使用やギフト向け"],["機能性ポリエステル","軽量、速乾、長時間のラウンド向け"],["メッシュ","通気性。パネル構造とロゴ面積を確認"],["混紡","触感、形状保持、お手入れのバランス"],["汗止め・内側","着用感、吸汗性、全体の品質印象"]], check:["使用地域と季節","想定着用時間","希望するクラウン形状","洗濯・管理条件","刺繍またはパッチ方法"], faq:[["暑い地域では常にメッシュが最適ですか？","通気性は高いですが、イベントの雰囲気、ロゴ面積、日射への対応も一緒に考えます。"],["生地色をPantoneに合わせられますか？","既存色か別注染色かによって、再現範囲、数量条件、日程が変わります。"]], related:"/ja/custom-golf-caps/" },
  jaCapsBrandingGuide: { group:"ゴルフ帽子開発", title:"帽子のロゴは前面だけでなく、着用時の全体バランスを見る", intro:"前面刺繍、側面スポンサー、背面文字、パッチは、クラウン構造と縫い目の範囲で計画します。", image:"/assets/images/zhoni-product-caps-v3.png", rows:[["前面中央","主ロゴ。クラウンの縫い目と高さを確認"],["前面オフセット","小さなシンボルや非対称の表現"],["側面","スポンサー、イベント名、補助マーク"],["背面","短い文字、URL、小さなロゴ"],["刺繍・パッチ","平面、3D、織り、ラバーの再現性を比較"]], check:["位置別のロゴファイル","完成サイズ","平面・3Dの指定","糸色と生地のコントラスト","背面アジャスターの種類"], faq:[["3D刺繍に小さな文字を入れられますか？","細い線や小さな文字は潰れる可能性があるため、平面刺繍や織りパッチが適する場合があります。"],["側面ロゴはどこにでも配置できますか？","パネルの縫い目、通気穴、内側テープを避けて配置する必要があります。"]], related:"/ja/custom-golf-caps/" },
  jaProductDevelopmentBriefGuide: { group:"製品開発", title:"製品開発ブリーフには、アイデアと制約条件の両方を書く", intro:"希望する外観だけでなく、対象、使用環境、数量、日程、必ず守る基準を共有します。", image:"/assets/images/zhoni-golf-product-development-v2.png", rows:[["目的と使用者","誰が、どこで、なぜ使用するか"],["製品方向","既存製品の変更か、新規構造の開発か"],["必須仕様","寸法、素材、機能、品質基準"],["ブランド資料","ロゴ、色、位置、参考画像"],["商業条件","予定数量、希望日、パッケージ、納品先"]], check:["一文で表すプロジェクト目的","必須条件と希望条件を区別","参考画像への説明","予定数量の範囲","意思決定者と承認日程"], faq:[["スケッチがなくても開発を始められますか？","用途と参考画像が明確なら初期方向を検討できますが、構造が複雑になるほど寸法や図面が必要です。"],["予算を共有する必要がありますか？","必須ではありませんが、目標水準と合わない方向を減らすため、おおよその範囲が役立つ場合があります。"]], related:"/ja/solutions/private-label-golf-collections/" },
  jaTournamentGiftBudgetGuide: { group:"ゴルフ大会", title:"大会ギフト予算は、製品単価だけで計画しない", intro:"ロゴ、サンプル、パッケージ、セット組み、輸送、現場配布まで含めて初めて実際のプロジェクト予算が見えます。", image:"/assets/images/zhoni-golf-tournament-gift-delivery-v2.png", rows:[["受取グループ","参加者、スポンサー、VIP、受賞者別の人数"],["製品費用","主力製品と補助構成品"],["ロゴ・サンプル","加工方法、校正、確認費用"],["包装・セット組み","箱、インサート、カード、組み立て"],["輸送・現場","国際配送、保管、仕分け、配布準備"]], check:["グループ別人数","総予算と優先順位","必須製品","パッケージ水準","予備数量と日程"], faq:[["すべての参加者に同じ予算を使うべきですか？","イベントの一貫性を保ちながら、VIPや受賞者は製品または包装水準で区分できます。"],["予備数量も注文すべきですか？","登録変更、破損、現地での不足を考え、合理的な予備数量を検討することが有効です。"]], related:"/ja/solutions/golf-tournament-gifts/" },
  jaPlayerPackGuide: { group:"ゴルフ大会", title:"良いPlayer Packは、現場ですぐ使える", intro:"参加者がゴルフバッグに入れて移動する流れ、天候、ラウンド中の必要性から製品を選びます。", image:"/assets/images/zhoni-product-gift-sets-v3.png", rows:[["主力製品","帽子、タオル、ヘッドカバーから大会に合う中心製品"],["フィールド用品","ボールマーカー、グリーンフォーク、ポーチ"],["情報要素","日程カード、スポンサーMessage、ネームタグ"],["パッケージ","携帯性、受付配布、廃棄しやすさ"],["予備構成","現地変更や不足に対応する数量"]], check:["参加者プロフィール","ラウンド環境","配布時間と場所","スポンサーLogo","セット組みと保管計画"], faq:[["箱は必ず必要ですか？","現地移動が多い場合は、ポーチ、スリーブ、簡潔な包装の方が実用的なことがあります。"],["ゴルフボールを含めるべきですか？","ブランド、規格、選手の好みが分かれるため、大会目的と製品方針から判断してください。"]], related:"/ja/solutions/golf-tournament-gifts/" },
  jaRecipientRolesGuide: { group:"ゴルフ大会", title:"参加者、スポンサー、受賞者ではギフトの役割が異なる", intro:"受取人の役割を先に分けると、製品水準、ブランド露出、渡す時点を正確に計画できます。", image:"/assets/images/zhoni-golf-tournament-gift-delivery-v2.png", rows:[["参加者","歓迎、実用性、イベントの一体感"],["スポンサー","関係への感謝と共同ブランドの視認性"],["VIP・招待客","控えめなロゴ、高い素材・包装水準"],["受賞者","達成と記念性が分かる差別化構成"],["運営チーム","識別性、実用性、現場効率"]], check:["役割別の人数","共通製品と差別化製品","ロゴの優先順位","引き渡し時点","包装・ラベルによる区分"], faq:[["受賞者ギフトを参加者パックと同じデザインにできますか？","共通デザインを保ち、主力製品、色、包装で受賞者体験を区別できます。"],["スポンサーLogoはいくつまで入れられますか？","製品面積と可読性によります。多数の場合はカードやパッケージに分ける方が適切なことがあります。"]], related:"/ja/solutions/golf-tournament-gifts/" },
  jaPremiumGiftSetGuide: { group:"ギフト選定", title:"Premium Gift Setは製品数より、価値の階層が重要", intro:"主役となる製品、役割のある補助製品、整ったパッケージが明確なセットを作ります。", image:"/assets/images/zhoni-product-gift-sets-v3.png", rows:[["主力製品","価値とブランド印象を担う中心製品"],["補助製品","主力製品の使用場面を広げるアクセサリー"],["素材・仕上げ","製品間の色、触感、金属仕上げのつながり"],["ブランド表現","サイズと位置を管理した一貫した表現"],["開封体験","製品の順番、インサート、カード、保護"]], check:["受取人と関係","主力製品の選定","製品ごとの役割","共通デザイン規則","包装と配送方法"], faq:[["Premium Setには製品が多く必要ですか？","いいえ。選び抜いた2〜3製品と良いパッケージの方が明確な価値を作れる場合があります。"],["個人名を入れられますか？","製品と加工方法によります。データ管理、追加費用、日程、誤り確認の手順が必要です。"]], related:"/ja/solutions/corporate-golf-gifts/" },
  jaEventBriefGuide: { group:"ゴルフ大会", title:"イベントブリーフには、行事情報と製品条件の両方を書く", intro:"イベント名と日付だけでは適切な製品と見積もりを判断できません。受取人、数量、配布、納品まで整理します。", image:"/assets/images/zhoni-material-direction-v1.png", rows:[["イベント背景","形式、場所、日付、ブランド目標"],["受取人","グループ別人数とゴルフ経験"],["製品方向","必須製品、参考画像、除外事項"],["ロゴ・包装","大会・スポンサーLogo、カード、配布方法"],["日程・納品","希望受取日、納品先、現場準備"]], check:["イベント日程","グループ別数量","ブランド・スポンサー資料","予算の優先順位","承認担当者"], faq:[["製品が決まっていなくても問い合わせできますか？","はい。対象、数量、日程、目的を共有すれば、適した製品経路を検討できます。"],["イベント日と希望受取日を分ける理由は？","社内確認、仕分け、現地搬入のため、イベント前に実物を受け取る必要があるからです。"]], related:"/ja/solutions/golf-tournament-gifts/" },
  jaQuoteComparisonGuide: { group:"初回注文・見積もり", title:"見積もりは、同じ仕様と条件で比較する", intro:"数字だけを比べると、素材、ロゴ、サンプル、包装、納品範囲の差を見落とす可能性があります。", image:"/assets/images/zhoni-product-gift-sets-v3.png", rows:[["製品仕様","寸法、素材、部品、品質基準が同じか"],["MOQ・数量","総数量と色・サイズ別の配分条件"],["ブランド表現","位置、サイズ、方法、色数が含まれるか"],["サンプル・承認","費用、修正回数、生産前の確認段階"],["包装・納品","個装、カートン、輸送、税金の範囲"]], check:["同一仕様書を配布","含む・含まない項目表","サンプル条件","支払・引き渡し条件","有効期限と日程前提"], faq:[["単価が低い供給先ほど競争力がありますか？","同じ品質、範囲、引き渡し条件かを確認するまでは判断できません。"],["関税と税金は見積もりに含まれますか？","引き渡し条件と納品先によります。輸送、通関、関税、税金の責任者を明確に確認してください。"]], related:"/ja/guides/what-affects-a-custom-golf-merchandise-quote/" },
};

function Guide({ pageKey }) {
  const item = content[pageKey];
  return <main className="zhoni-page guide-page ja-page"><Header /><section className="guide-hero"><div><p>{item.group} · 購入ガイド</p><h1>{item.title}</h1><p>{item.intro}</p><small>判断基準 · チェックリスト · 購入担当者の質問</small></div><img src={item.image} alt={item.title} /></section><section className="guide-intro"><p>PRACTICAL BUYER REVIEW</p><h2>実際のプロジェクト前に確認する項目。</h2><p>以下は初期ブリーフと供給先の検討に使う基準です。最終製品、MOQ、価格、サンプル、品質、日程は合意したプロジェクト範囲に基づいて確認します。</p></section><section className="guide-table"><table><thead><tr><th>確認領域</th><th>購入判断の基準</th></tr></thead><tbody>{item.rows.map(row => <tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td></tr>)}</tbody></table></section><LocalizedBuyerEvidence locale="ja" context={`guide-${pageKey.replace("ja", "").replace("Guide", "").toLowerCase()}`} /><section className="guide-decision"><div><p>購入担当者の準備</p><h2>具体的な情報が不要な推測を減らす。</h2><p>すべてを最初から確定する必要はありません。分かっている内容、希望条件、必ず守る基準を分けて共有してください。</p></div><aside><p>CHECKLIST</p><h3>ブリーフに含める内容</h3><ul>{item.check.map(value => <li key={value}>{value}</li>)}</ul></aside></section><section className="guide-faq"><p>よくある質問</p><h2>次の判断に使える現実的な回答。</h2><div>{item.faq.map(([question,answer],index) => <article key={question}><b>{String(index + 1).padStart(2,"0")}</b><h3>{question}</h3><p>{answer}</p></article>)}</div></section><section className="guide-products"><p>関連するプロジェクト経路</p><h2>読んだ内容を実際のブリーフにつなげる。</h2><div><a href={item.related}>関連製品・ソリューション<Arrow /></a><a href="/ja/products/">製品カテゴリー<Arrow /></a><a href="/ja/solutions/">Solutions<Arrow /></a><a href="/ja/our-process/">進め方<Arrow /></a><a href="/ja/request-a-quote/">プロジェクト相談<Arrow /></a></div></section><Footer /></main>;
}

function Capabilities() {
  const items = [["製品方向","ヘッドカバー、帽子、タオル、アクセサリー、パッケージを目的に合わせて検討します。"],["ブランド適用","刺繍、印刷、型押し、パッチ、金属仕上げを素材とロゴに合わせます。"],["ギフトセット","受取人と渡す場面を基準に、製品構成とパッケージを組み立てます。"],["サンプル・品質","製品別の確認段階、承認基準、生産前後の品質項目を整理します。"],["包装・出荷","個装、ギフトボックス、カートン、納品先、引き渡し条件を確認します。"]];
  return <main className="zhoni-page capabilities-page ja-page"><Header /><section className="capability-hero"><img src="/assets/images/zhoni-golf-collection-hero-v2.png" alt="ZHONIカスタムゴルフ用品コレクション" /></section><section className="capability-intro"><div><p>CAPABILITIES</p><h1>製品から引き渡しまでをつなぐ、カスタムゴルフプロジェクト。</h1><p>ZHONIは単品または組み合わせギフトにおいて、製品方向、ブランド表現、確認手順、パッケージ、納品準備を一緒に検討します。</p><div className="capability-list">{items.map(([title,copy]) => <article key={title}><h2>{title}</h2><p>{copy}</p></article>)}</div></div><aside><p>プロジェクト適合性</p><h2>お問い合わせ前に役立つ情報</h2><ul><li>受取人と使用目的</li><li>製品または参考画像</li><li>予定数量と希望受取日</li><li>ロゴとブランドガイド</li><li>パッケージと納品先</li></ul><small>MOQ、価格、サンプル、日程、引き渡し条件は、製品と合意した範囲に基づいて確認します。</small></aside></section><LocalizedBuyerEvidence locale="ja" context="capabilities" /><section className="guide-products"><p>関連するプロジェクト経路</p><h2>必要な情報から次の段階へ。</h2><div><a href="/ja/products/">製品カテゴリー<Arrow /></a><a href="/ja/solutions/">Solutions<Arrow /></a><a href="/ja/guides/">購入ガイド<Arrow /></a><a href="/ja/our-process/">進め方<Arrow /></a><a href="/ja/request-a-quote/">プロジェクト相談<Arrow /></a></div></section><section className="capability-cta"><img src="/assets/golf-flag-cta.png" alt="ゴルフコースの旗" /><div><p>READY TO REVIEW YOUR PROJECT?</p><a href="/ja/request-a-quote/">プロジェクト概要を送る <Arrow /></a></div></section><Footer /></main>;
}

export function JapaneseFinalGuides({ routeKey }) {
  if (routeKey === "jaCapabilities") return <Capabilities />;
  if (content[routeKey]) return <Guide pageKey={routeKey} />;
  return null;
}
