import { useState } from "react";
import { LanguageSwitcher } from "./locale.jsx";
import { LocalizedBuyerEvidence } from "./LocalizedBuyerEvidence.jsx";

const Arrow = () => <span aria-hidden="true">↗</span>;
const WHATSAPP_URL = import.meta.env.VITE_WHATSAPP_URL ?? "https://wa.me/8617759190848";

function Header() {
  const [menu,setMenu] = useState(false);
  return <header className={`zhoni-header ja-header ${menu ? "zhoni-header-open" : ""}`}><a className="zhoni-wordmark" href="/ja/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><button className="zhoni-menu" onClick={() => setMenu(value => !value)} aria-expanded={menu}>{menu ? "閉じる" : "メニュー"}</button><nav aria-label="メインナビゲーション"><a href="/ja/products/">製品</a><a href="/ja/solutions/">ソリューション</a><a className="active" href="/ja/guides/">購入ガイド</a><a href="/ja/our-process/">進め方</a><a href="/ja/faq/">FAQ</a><a href="/ja/about/">会社情報</a></nav><LanguageSwitcher /><a className="zhoni-header-cta" href="/ja/request-a-quote/">プロジェクト相談 <Arrow /></a></header>;
}

function Footer() {
  return <footer className="site-footer"><div className="site-footer-main"><a className="zhoni-wordmark" href="/ja/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><div className="site-footer-copy"><p>クラブ、大会、企業、ブランド向けのカスタムゴルフ用品プロジェクト。</p><span>製品開発 · ロゴ · ギフト · 品質 · パッケージ · 納品</span><div className="site-footer-contact"><b>直接のお問い合わせ</b><a href="mailto:sales@zhonigolf.com">sales@zhonigolf.com</a><a href={WHATSAPP_URL}>WhatsApp +86 177 5919 0848 <Arrow /></a></div></div><nav><a href="/ja/products/">製品</a><a href="/ja/solutions/">ソリューション</a><a href="/ja/guides/">購入ガイド</a><a href="/ja/first-order-guide/">初回注文</a><a href="/ja/our-process/">進め方</a><a href="/ja/request-a-quote/">お問い合わせ <Arrow /></a></nav></div><div className="site-footer-base"><span>ZHONI · CUSTOM GOLF MERCHANDISE</span><span>運営法人: Xiamen Jindongyu Trading Co., Ltd.</span></div></footer>;
}

const content = {
  jaHeadcoverMaterialsGuide: { group:"ヘッドカバー開発", title:"素材は触感だけでなく、構造とロゴ表現も決める", intro:"見た目だけで比べず、保護性、形状保持、縫製、ロゴ方法に与える影響を確認します。", image:"/assets/images/zhoni-product-headcovers-v3.png", rows:[["PU・合成皮革","輪郭を出しやすく、刺繍、型押し、アップリケなどの選択肢が広い"],["織物","色と触感の幅が広く、カジュアルまたはスポーティな表現に向く"],["ニット","柔らかく伝統的な印象。番手表示、リブ、ポンポン構造を確認"],["複合素材","パネルごとの役割と視覚的なコントラストを作れる"],["裏地・中材","クラブ保護、フィット、厚み、着脱感に直接影響"]], check:["希望する触感と形状","使用頻度と環境","ロゴ方法","クラブ別のフィット","お手入れと包装条件"], faq:[["天然皮革は常に最良ですか？","高級感はありますが、管理、色の一貫性、価格、数量、使用環境を一緒に検討する必要があります。"],["写真だけで素材を確定できますか？","質感、厚み、柔軟性が重要な場合は、素材スワッチまたは実物サンプルの確認がより安全です。"]], related:"/ja/custom-golf-headcovers/" },
  jaHeadcoverTypesGuide: { group:"ヘッドカバー開発", title:"クラブタイプごとに、必要な構造とフィットは異なる", intro:"ドライバー、フェアウェイ、ハイブリッド、パターの外観を揃えても、型紙と使用方法は個別に検討します。", image:"/assets/images/zhoni-product-headcovers-v3.png", rows:[["ドライバー","大きなヘッド、広いロゴ面、安定した開口部"],["フェアウェイ","番手表示とドライバーとの差が分かるサイズ設計"],["ハイブリッド","小さな形状、クラブ識別、シリーズとしての統一性"],["ブレードパター","細身のフィット、開閉、保護構造"],["マレットパター","形状別パターン、ネック方向、マグネット位置"]], check:["クラブタイプ別の数量","右用・左用の方向","番手またはラベル","開閉方法","セットパッケージ"], faq:[["一つの型で全ブランドのクラブに合いますか？","ある程度の汎用設計は可能ですが、特にパターは形状差が大きいため、対象モデルと寸法の確認が必要です。"],["タイプごとに色を変えられますか？","可能性はありますが、素材色の条件とタイプ別数量配分がMOQに与える影響を確認します。"]], related:"/ja/custom-golf-headcovers/" },
  jaProductSpecificationGuide: { group:"製品開発", title:"仕様書は参考画像を、製造可能な基準に変える", intro:"製品名だけでは同じ見積もりやサンプルを作れません。寸法、素材、部品、ロゴ、包装の基準を文書化します。", image:"/assets/images/zhoni-material-direction-v1.png", rows:[["基本情報","製品名、用途、版番号、担当者、更新日"],["寸法・許容範囲","測定位置、単位、重要寸法、機能に関わる許容差"],["素材・色","材質、目付・厚み、表面、色基準"],["構造・部品","パネル、縫製、マグネット、ファスナー、バックル、金属部品"],["ロゴ・包装","ファイル、位置、サイズ、加工方法、個装、外装"]], check:["寸法図","素材の参考","部品一覧","ロゴ配置図","品質と包装の基準"], faq:[["仕様書は誰が作成しますか？","購入者が目的と必須条件を示し、供給側と一緒に製造可能な詳細へ整理する方法が実務的です。"],["すべての寸法に許容差が必要ですか？","まず機能、フィット、外観に影響する重要寸法を優先して定義します。"]], related:"/ja/first-order-guide/" },
  jaSampleApprovalGuide: { group:"製品開発", title:"サンプル承認は「見た目が良い」より具体的に", intro:"承認サンプルは量産時の基準になります。寸法、機能、素材、ロゴ、包装まで記録します。", image:"/assets/images/zhoni-quality-inspection-v1.png", rows:[["形状・寸法","仕様書、測定位置、フィット、対称性"],["素材・色","触感、厚み、光沢、承認色との比較"],["機能","開閉、マグネット、クリップ、着用、実使用"],["ロゴ・仕上げ","サイズ、位置、鮮明さ、縫製、端部"],["パッケージ","構成、ラベル、インサート、保護状態"]], check:["承認・修正・保留を明記","写真と測定値を記録","修正項目を番号化","再確認が必要な項目","承認者と日付"], faq:[["サンプル写真だけで承認できますか？","色、触感、フィット、機能が重要な製品では実物確認の方が適切な場合があります。"],["修正後に再度サンプルを確認すべきですか？","機能や外観に重要な変更であれば、変更箇所を再確認する方が安全です。"]], related:"/ja/our-process/" },
  jaCollectionPlanningGuide: { group:"コレクション開発", title:"製品数を増やすより、共通のデザインルールを作る", intro:"同じロゴを付けるだけではコレクションになりません。対象、製品の役割、共通のデザインシステムを定めます。", image:"/assets/images/zhoni-golf-collection-hero-v2.png", rows:[["共通目的","大会、会員プログラム、企業ギフト、販売コレクション"],["主力製品","プロジェクトの価値と印象を担う中心製品"],["補助製品","使用場面を広げる実用アクセサリー"],["デザインシステム","色、ロゴサイズ、素材、金属仕上げのルール"],["パッケージ","製品の順序と手渡す瞬間を整える構造"]], check:["受取人と目的","主力製品の選定","製品ごとの役割","共通要素と個別要素","目標価格帯と数量"], faq:[["すべての製品を同じ色にすべきですか？","同色だけでなく、補色や繰り返す金属仕上げ、ロゴ階層でも統一感を作れます。"],["製品数は多いほど良いですか？","いいえ。役割が不明な構成品より、用途が明確な少数の製品の方が強い体験になります。"]], related:"/ja/solutions/golf-club-member-programs/" },
  jaHeadcoverLogoGuide: { group:"ヘッドカバー開発", title:"ロゴ位置は平面図ではなく、クラブ装着時に判断する", intro:"曲面、縫い目、開口部は実際の視認性に影響します。素材とパネル構造を先に確認します。", image:"/assets/images/zhoni-product-headcovers-v3.png", rows:[["前面パネル","視認性が高い。曲面による歪みと中心線を確認"],["側面パネル","補助ロゴ、番手、製品区分に利用"],["上面・ネック","小さなシンボルや反復ディテールに適する"],["刺繍・アップリケ","質感と色表現、最小線幅の制約を確認"],["型押し・パッチ","控えめな表現、または複雑なロゴの代替"]], check:["完成サイズ","パネル別の位置図","最小線幅と文字","糸色と素材色","左右方向の確認"], faq:[["大きなロゴほど鮮明ですか？","曲面やパネル境界を越えると歪むため、使用できる面の中で比率を調整する必要があります。"],["パターカバーも同じ位置を使えますか？","形状と開閉方向が異なるため、別途配置を確認します。"]], related:"/ja/custom-golf-headcovers/" },
  jaCapsMaterialsGuide: { group:"ゴルフ帽子開発", title:"帽子の生地は気候と着用時間から選ぶ", intro:"コットンの触感、機能素材の速乾性、メッシュの通気性は、それぞれ異なる使用場面に向きます。", image:"/assets/images/zhoni-product-caps-v3.png", rows:[["コットンツイル","馴染みのある触感と形状。日常使用やギフト向け"],["機能性ポリエステル","軽量、速乾、長時間のラウンド向け"],["メッシュ","通気性。パネル構造とロゴ面積を確認"],["混紡","触感、形状保持、お手入れのバランス"],["汗止め・内側","着用感、吸汗性、全体の品質印象"]], check:["使用地域と季節","想定着用時間","希望するクラウン形状","洗濯・管理条件","刺繍またはパッチ方法"], faq:[["暑い地域では常にメッシュが最適ですか？","通気性は高いですが、イベントの雰囲気、ロゴ面積、日射への対応も一緒に考えます。"],["生地色をPantoneに合わせられますか？","既存色か別注染色かによって、再現範囲、数量条件、日程が変わります。"]], related:"/ja/custom-golf-caps/" },
  jaCapsBrandingGuide: { group:"ゴルフ帽子開発", title:"帽子のロゴは前面だけでなく、着用時の全体バランスを見る", intro:"前面刺繍、側面スポンサー、背面文字、パッチは、クラウン構造と縫い目の範囲で計画します。", image:"/assets/images/zhoni-product-caps-v3.png", rows:[["前面中央","主ロゴ。クラウンの縫い目と高さを確認"],["前面オフセット","小さなシンボルや非対称の表現"],["側面","スポンサー、イベント名、補助マーク"],["背面","短い文字、URL、小さなロゴ"],["刺繍・パッチ","平面、3D、織り、ラバーの再現性を比較"]], check:["位置別のロゴファイル","完成サイズ","平面・3Dの指定","糸色と生地のコントラスト","背面アジャスターの種類"], faq:[["3D刺繍に小さな文字を入れられますか？","細い線や小さな文字は潰れる可能性があるため、平面刺繍や織りパッチが適する場合があります。"],["側面ロゴはどこにでも配置できますか？","パネルの縫い目、通気穴、内側テープを避けて配置する必要があります。"]], related:"/ja/custom-golf-caps/" },
  jaProductDevelopmentBriefGuide: { group:"製品開発", title:"製品開発ブリーフには、アイデアと制約条件の両方を書く", intro:"希望する外観だけでなく、対象、使用環境、数量、日程、必ず守る基準を共有します。", image:"/assets/images/zhoni-golf-product-development-v2.png", rows:[["目的と使用者","誰が、どこで、なぜ使用するか"],["製品方向","既存製品の変更か、新規構造の開発か"],["必須仕様","寸法、素材、機能、品質基準"],["ブランド資料","ロゴ、色、位置、参考画像"],["商業条件","予定数量、希望日、パッケージ、納品先"]], check:["一文で表すプロジェクト目的","必須条件と希望条件を区別","参考画像への説明","予定数量の範囲","意思決定者と承認日程"], faq:[["スケッチがなくても開発を始められますか？","用途と参考画像が明確なら初期方向を検討できますが、構造が複雑になるほど寸法や図面が必要です。"],["予算を共有する必要がありますか？","必須ではありませんが、目標水準と合わない方向を減らすため、おおよその範囲が役立つ場合があります。"]], related:"/ja/solutions/private-label-golf-collections/" },
};

function Guide({ pageKey }) {
  const item = content[pageKey];
  return <main className="zhoni-page guide-page ja-page"><Header /><section className="guide-hero"><div><p>{item.group} · 購入ガイド</p><h1>{item.title}</h1><p>{item.intro}</p><small>判断基準 · チェックリスト · 購入担当者の質問</small></div><img src={item.image} alt={item.title} /></section><section className="guide-intro"><p>PRACTICAL BUYER REVIEW</p><h2>実際のプロジェクト前に確認する項目。</h2><p>以下は初期ブリーフと供給先の検討に使う基準です。最終製品、MOQ、価格、サンプル、品質、日程は合意したプロジェクト範囲に基づいて確認します。</p></section><section className="guide-table"><table><thead><tr><th>確認領域</th><th>購入判断の基準</th></tr></thead><tbody>{item.rows.map(row => <tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td></tr>)}</tbody></table></section><LocalizedBuyerEvidence locale="ja" context={`development-${pageKey.replace("ja", "").replace("Guide", "").toLowerCase()}`} /><section className="guide-decision"><div><p>購入担当者の準備</p><h2>具体的な情報が不要な推測を減らす。</h2><p>すべてを最初から確定する必要はありません。分かっている内容、希望条件、必ず守る基準を分けて共有してください。</p></div><aside><p>CHECKLIST</p><h3>ブリーフに含める内容</h3><ul>{item.check.map(value => <li key={value}>{value}</li>)}</ul></aside></section><section className="guide-faq"><p>よくある質問</p><h2>次の判断に使える現実的な回答。</h2><div>{item.faq.map(([question,answer],index) => <article key={question}><b>{String(index + 1).padStart(2,"0")}</b><h3>{question}</h3><p>{answer}</p></article>)}</div></section><section className="guide-products"><p>関連するプロジェクト経路</p><h2>読んだ内容を実際のブリーフにつなげる。</h2><div><a href={item.related}>関連製品・ソリューション<Arrow /></a><a href="/ja/products/">製品カテゴリー<Arrow /></a><a href="/ja/solutions/">Solutions<Arrow /></a><a href="/ja/our-process/">進め方<Arrow /></a><a href="/ja/request-a-quote/">プロジェクト相談<Arrow /></a></div></section><Footer /></main>;
}

export function JapaneseFinalGuides({ routeKey }) {
  if (content[routeKey]) return <Guide pageKey={routeKey} />;
  return null;
}
