import { useState } from "react";
import { LanguageSwitcher } from "./locale.jsx";
import { TurnstileField } from "./turnstile.jsx";
import { trackAnalytics } from "./analytics.jsx";
import { inquirySourceForLocation } from "./seo.js";
import { LocalizedBuyerEvidence } from "./LocalizedBuyerEvidence.jsx";

const WHATSAPP_URL = import.meta.env.VITE_WHATSAPP_URL ?? "https://wa.me/8617759190848";
const Arrow = () => <span aria-hidden="true">↗</span>;

function Header({ active }) {
  const [menu, setMenu] = useState(false);
  return <header className={`zhoni-header ja-header ${menu ? "zhoni-header-open" : ""}`}>
    <a className="zhoni-wordmark" href="/ja/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a>
    <button className="zhoni-menu" onClick={() => setMenu(value => !value)} aria-expanded={menu}>{menu ? "閉じる" : "メニュー"}</button>
    <nav aria-label="メインナビゲーション"><a className={active === "products" ? "active" : ""} href="/ja/products/">製品</a><a className={active === "solutions" ? "active" : ""} href="/ja/solutions/">ソリューション</a><a className={active === "process" ? "active" : ""} href="/ja/our-process/">進め方</a><a className={active === "faq" ? "active" : ""} href="/ja/faq/">FAQ</a><a className={active === "about" ? "active" : ""} href="/ja/about/">会社情報</a></nav>
    <LanguageSwitcher />
    <a className="zhoni-header-cta" href="/ja/request-a-quote/">プロジェクト相談 <Arrow /></a>
  </header>;
}

function Footer() {
  return <footer className="site-footer"><div className="site-footer-main"><a className="zhoni-wordmark" href="/ja/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><div className="site-footer-copy"><p>クラブ、大会、企業、ブランド向けのカスタムゴルフ用品とパッケージ。</p><span>ギフトセット · ヘッドカバー · キャップ · タオル · アクセサリー · パッケージ</span><div className="site-footer-contact"><b>直接のお問い合わせ</b><a href="mailto:sales@zhonigolf.com">sales@zhonigolf.com</a><a href={WHATSAPP_URL}>WhatsApp +86 177 5919 0848 <Arrow /></a></div></div><nav aria-label="フッターナビゲーション"><a href="/ja/products/">製品</a><a href="/ja/solutions/">ソリューション</a><a href="/ja/our-process/">進め方</a><a href="/ja/faq/">FAQ</a><a href="/ja/about/">会社情報</a><a href="/ja/request-a-quote/">お問い合わせ <Arrow /></a></nav></div><div className="site-footer-base"><span>ZHONI · CUSTOM GOLF MERCHANDISE</span><span>運営法人: Xiamen Jindongyu Trading Co., Ltd.</span></div></footer>;
}

const productFamilies = [
  ["ヘッドカバー", "クラブ保護、フィット、素材、ロゴ表現を一体で検討します。", "/assets/images/zhoni-product-headcovers-v3.png", "カスタムゴルフヘッドカバー"],
  ["キャップ＆バイザー", "着用環境、フィット、生地、刺繍位置に合わせて設計します。", "/assets/images/zhoni-product-caps-v3.png", "カスタムゴルフキャップ＆バイザー"],
  ["マグネットタオル", "コースでの使いやすさと刺繍、マグネット構造を確認します。", "/assets/images/zhoni-product-magnetic-towel-v4.png", "カスタムゴルフタオル"],
  ["アクセサリー", "ボールマーカー、グリーンフォーク、バッグタグ、ポーチを用途別に構成します。", "/assets/images/zhoni-product-accessories-v3.png", "カスタムゴルフアクセサリー"],
  ["ギフトセット", "受け取る人、贈る場面、製品の役割を一つの体験にまとめます。", "/assets/images/zhoni-product-gift-sets-v3.png", "カスタムゴルフギフトセット"],
  ["パッケージ", "箱、インサート、カード、保護梱包を製品と納品条件に合わせます。", "/assets/images/zhoni-product-packaging-v3.png", "カスタムゴルフパッケージ"],
];

function Home() {
  return <main className="home-page ja-page"><Header /><section className="zhoni-hero"><div className="zhoni-hero-copy"><p>CUSTOM GOLF MERCHANDISE</p><h1>製品を並べるだけでなく、<br />目的に合うゴルフ体験へ。</h1><p>クラブ、大会、企業、ブランドのために、製品選定、ロゴ表現、ギフト構成、パッケージ、納品準備を一つのプロジェクトとして検討します。</p><div><a href="/ja/products/">製品を見る <Arrow /></a><a href="/ja/request-a-quote/">相談を始める <Arrow /></a></div></div><img src="/assets/images/zhoni-golf-collection-hero-v2.png" alt="ZHONIのカスタムゴルフ用品コレクション" /></section><section className="gift-atlas"><p>ZHONI PROJECT ROUTE</p><h2>一つの製品から、統一されたコレクションまで。</h2><p className="atlas-intro">誰が、いつ、何のために受け取るかを確認し、製品、ブランド表現、パッケージの方向を整理します。</p>{[["01","製品を選ぶ","ヘッドカバー、キャップ、タオル、アクセサリー、ギフトセットから検討します。","製品を見る","/ja/products/"],["02","用途を整理する","大会、企業ギフト、クラブ会員、プライベートブランドの目的を定めます。","ソリューション","/ja/solutions/"],["03","仕様と承認を確認する","素材、ロゴ、色、パッケージ、必要な確認段階を整理します。","進め方","/ja/our-process/"],["04","概要を共有する","数量、希望日、納品先、ブランド資料をお送りください。","相談する","/ja/request-a-quote/"]].map(([number,title,copy,label,href]) => <article key={number}><b>{number}</b><div><h3>{title}</h3><p>{copy}</p></div><a href={href}>{label} <Arrow /></a></article>)}</section><Footer /></main>;
}

function Products() {
  return <main className="products-hub ja-page"><Header active="products" /><section className="products-hero"><img src="/assets/images/zhoni-golf-collection-hero-v2.png" alt="ZHONIカスタムゴルフ用品" /><div className="products-hero-copy"><p className="products-kicker">カスタムゴルフ用品</p><h1>単品ではなく、<br />つながるコレクションへ。</h1><p>用途、受け取る人、ブランド表現、渡し方に合わせて製品を組み立てます。</p><a href="/ja/request-a-quote/">プロジェクト相談 <Arrow /></a></div></section><section className="family-index"><div className="family-heading"><p className="products-kicker">製品カテゴリー</p><h2>Product Families</h2><p>製品が違っても、<br />ブランド体験は一つに。</p></div><div className="family-grid">{productFamilies.map(([title,copy,image,brief]) => <a className="family-card" href={`/ja/request-a-quote/?product=${encodeURIComponent(brief)}`} key={title}><img src={image} alt={title} /><h3>{title}</h3><p>{copy}</p><span>— &nbsp; <Arrow /></span></a>)}</div></section><LocalizedBuyerEvidence locale="ja" context="products" /><section className="products-intro"><p className="products-kicker">COORDINATED APPROACH</p><h2>製品、ブランド表現、パッケージを同じ基準で確認。</h2><p>MOQ、価格、サンプル、納期は製品構造、カスタム範囲、数量、パッケージ、納品先によって変わります。</p><a href="/ja/our-process/">進行プロセスを見る <Arrow /></a></section><Footer /></main>;
}

function Solutions() {
  const programs = [["01","ゴルフ大会・プレーヤーパック","参加者、スポンサー、VIP、受賞者ごとに役割を分けます。","/assets/images/zhoni-golf-tournament-gift-delivery-v2.png","golf-tournament-gifts"],["02","企業向けゴルフギフト","顧客、社員、パートナーとの関係と贈呈場面から設計します。","/assets/images/zhoni-custom-golf-packaging-v2.png","corporate-golf-gifts"],["03","クラブ会員プログラム","入会、更新、記念日、会員イベントを継続可能な体系にします。","/assets/images/zhoni-golf-product-development-v2.png","club-member-programs"],["04","プライベートブランド","製品構成、仕様、ロゴ、パッケージ、承認記録を体系化します。","/assets/images/zhoni-golf-collection-hero-v2.png","private-label-collections"]];
  return <main className="zhoni-page solutions-page ja-page"><Header active="solutions" /><section className="solutions-index-hero"><div className="solutions-rail" aria-hidden="true"><strong>Z</strong><span>SOLUTIONS</span><i>PEOPLE · GOLF · BRANDS</i></div><div className="solutions-index-intro"><p>プロジェクト別ソリューション</p><h1>製品より先に、<br />受け取る人と目的を。</h1><p>対象、場面、数量、渡し方を整理してから、適切な製品構成を検討します。</p></div><figure><img src="/assets/images/zhoni-custom-golf-packaging-v2.png" alt="カスタムゴルフギフトとパッケージ" /><figcaption>MORE THAN PRODUCTS.<br />A MORE THOUGHTFUL APPROACH.</figcaption></figure></section><section className="solutions-program-index">{programs.map(([number,title,copy,image,solution]) => <a className="solutions-program" href={`/ja/request-a-quote/?solution=${solution}&source=${solution}`} key={number}><b>{number}</b><img src={image} alt={title} /><div><h2>{title}</h2><p><strong>適した用途</strong>{copy}</p></div><span>→</span></a>)}</section><LocalizedBuyerEvidence locale="ja" context="solutions" /><section className="solutions-brief-bridge"><div><p>概要から始める</p><h2>目的を定めてから、<br />製品構成を考えます。</h2><p>対象、数量、希望納期、納品国、製品の方向を共有いただければ、次に確認すべき内容をご案内します。</p><a href="/ja/request-a-quote/">プロジェクト概要を送る <Arrow /></a></div><aside><p>最初に役立つ情報</p><ul><li>誰が受け取りますか？</li><li>どのような大会・プログラムですか？</li><li>予定数量はどのくらいですか？</li><li>いつ、どこで必要ですか？</li><li>ロゴや参考画像はありますか？</li></ul></aside></section><Footer /></main>;
}

function Process() {
  const steps = [["01","概要共有","目的、対象、数量、希望日、納品先を共有します。","/assets/images/zhoni-material-direction-v1.png"],["02","製品方向","用途に合う製品、素材、ロゴ、パッケージを検討します。","/assets/images/zhoni-embroidery-sample-v1.png"],["03","仕様確認","アートワーク、校正、サンプル、仕様書など必要な承認方法を決めます。","/assets/images/zhoni-gift-packaging-process-v1.png"],["04","生産準備","合意した範囲と品質確認項目に基づいて生産を準備します。","/assets/images/zhoni-quality-inspection-v1.png"],["05","梱包・納品","個装、外装カートン、納品先、配送条件を確認します。","/assets/images/zhoni-carton-packing-v1.png"]];
  return <main className="zhoni-page process-page ja-page"><Header active="process" /><section className="process-hero"><div><p>進行プロセス</p><h1>概要から納品まで、<br />確認できる段階で。</h1><p>製品、ロゴ、パッケージ、納期を別々に扱わず、一つのプロジェクトとして管理します。</p><a href="/ja/request-a-quote/">概要を送る <Arrow /></a></div><img src="/assets/images/zhoni-material-direction-v1.png" alt="カスタムゴルフ用品の素材と色の確認" /></section><section className="process-ledger"><p>THE PROCESS</p><span>5つの確認段階</span><div>{steps.map(([number,title,copy,image]) => <article key={number}><b>{number}</b><h2>{title}</h2><p>{copy}</p><img src={image} alt={title} /></article>)}</div></section><LocalizedBuyerEvidence locale="ja" context="process" /><section className="project-input"><div><p>ご用意いただく情報</p><h2>正確な検討は、<br />具体的な背景から。</h2><p>最初から全仕様を確定する必要はありません。分かっている内容と参考資料から共有してください。</p></div><ul><li><b>用途</b><span>クラブ、大会、企業ギフト、ブランド商品</span></li><li><b>予定数量</b><span>おおよその範囲で開始可能</span></li><li><b>希望日と納品先</b><span>必要日、国、都市</span></li><li><b>ブランド資料</b><span>ロゴ、カラー規定、参考画像</span></li><li><b>パッケージ</b><span>箱、インサート、カード、個装</span></li></ul><aside>MOQ、価格、サンプル、納期、配送条件は合意したプロジェクト範囲に基づいて確認します。</aside></section><Footer /></main>;
}

function Faq() {
  const [open, setOpen] = useState(0);
  const items = [["どのようなゴルフ用品をカスタムできますか？","ヘッドカバー、キャップ、バイザー、タオル、ポーチ、バッグタグ、ボールマーカー、グリーンフォーク、ギフトセット、パッケージなどをプロジェクトに応じて検討できます。"],["MOQはどのくらいですか？","最小注文数量は製品構造、素材、色、ロゴ方法、パッケージ、カスタム範囲によって異なります。製品と予定数量をお知らせください。"],["サンプルと承認はどのように進みますか？","製品により、アートワーク、校正、既存サンプル、新規サンプル、仕様書など適切な確認方法が異なります。"],["見積もりに必要な情報は何ですか？","製品方向、予定数量、ロゴ、パッケージ、希望納期、納品先の国と都市を共有してください。"],["生産と配送にはどのくらいかかりますか？","ファイルの準備状況、製品、サンプル確認、数量、パッケージ、納品先によって変わります。希望受取日を必ずお知らせください。"],["複数製品をギフトセットにできますか？","可能です。対象と目的に合わせて製品、ロゴ表現、パッケージを一つの受け取り体験として構成します。"]];
  return <main className="zhoni-page faq-page ja-page"><Header active="faq" /><section className="faq-ledger-hero"><div><p>FAQ · 購入検討ガイド</p><h1>カスタムゴルフプロジェクトの<br />よくある質問。</h1><p>製品、数量、ロゴ、パッケージ、希望日、納品先を一緒に確認することで、より適切な次の段階を決められます。</p></div><aside><p>お問い合わせ前の準備</p><h2>概要に含めるとよい情報</h2><ol><li>対象と使用目的</li><li>製品方向または参考画像</li><li>予定数量と希望受取日</li><li>ロゴとパッケージ要件</li><li>納品国と都市</li></ol></aside></section><section className="capability-faq"><div><p>よくある質問</p><h2>購入判断に役立つ回答。</h2></div><div>{items.map(([question,answer],index) => <article key={question}><button onClick={() => setOpen(open === index ? -1 : index)} aria-expanded={open === index}><span>{question}</span><b>{open === index ? "−" : "+"}</b></button><p hidden={open !== index}>{answer}</p></article>)}</div></section><section className="faq-path"><p>次のステップ</p><div><a href="/ja/products/"><b>01</b><span>製品を見る</span><Arrow /></a><a href="/ja/solutions/"><b>02</b><span>用途を選ぶ</span><Arrow /></a><a href="/ja/request-a-quote/"><b>03</b><span>概要を送る</span><Arrow /></a></div></section><Footer /></main>;
}

function About() {
  return <main className="zhoni-page about-page ja-page"><Header active="about" /><section className="zhoni-about-hero"><img src="/assets/images/zhoni-golf-collection-hero-v2.png" alt="ZHONIカスタムゴルフギフトコレクション" /><div><p>ABOUT ZHONI</p><h1>目的が明確な<br />ゴルフプロジェクトのために。</h1><p>ZHONIは、クラブ、大会、企業、ブランド向けのカスタムゴルフ用品、ギフトセット、パッケージプロジェクトを支援します。</p><a href="/ja/request-a-quote/">プロジェクト相談 <Arrow /></a></div></section><section className="relationship"><div><p>運営体制</p><h2>明確な運営主体と、<br />一貫したプロジェクト管理。</h2></div><div className="relationship-copy"><p>ZHONIはXiamen Jindongyu Trading Co., Ltd.が運営するカスタムゴルフ用品ブランドです。製品方向、カスタム仕様、パッケージ、商業条件をプロジェクト単位で調整します。</p><p>すべての案件に同じ回答を当てはめません。製品範囲、MOQ、スケジュール、必要書類は、実際の概要に基づいて確認します。</p></div><div className="relationship-map"><article><b>ZHONI</b><span>カスタムゴルフ用品ブランド</span><small>製品方向 · カスタム仕様 · 顧客プロジェクト</small></article><i>運営法人</i><article><b>Xiamen Jindongyu<br />Trading Co., Ltd.</b><span>法的運営主体</span><small>商取引 · 契約 · 運営体制</small></article></div></section><Footer /></main>;
}

function Quote() {
  const [status, setStatus] = useState("idle");
  const [message, setMessage] = useState("");
  const params = typeof window === "undefined" ? new URLSearchParams() : new URLSearchParams(window.location.search);
  const aliases = { "golf-tournament-gifts":"ゴルフ大会用品", "corporate-golf-gifts":"企業向けゴルフギフト", "club-member-programs":"クラブ会員プログラム", "private-label-collections":"プライベートブランド" };
  const selected = params.get("product") ?? aliases[params.get("solution")] ?? "";
  const options = ["カスタムゴルフヘッドカバー","カスタムゴルフキャップ＆バイザー","カスタムゴルフタオル","カスタムゴルフアクセサリー","カスタムゴルフギフトセット","ゴルフ大会用品","企業向けゴルフギフト","クラブ会員プログラム","プライベートブランド","カスタムゴルフパッケージ"];
  const submit = async event => { event.preventDefault(); if (status === "submitting") return; const form = event.currentTarget; const data = new FormData(form); data.set("source", inquirySourceForLocation()); data.set("page_language", "ja"); data.set("page_path", window.location.pathname); data.set("page_url", window.location.href); if (data.get("company_website")) { form.reset(); setStatus("success"); setMessage("プロジェクト概要を受け付けました。"); return; } setStatus("submitting"); setMessage("送信しています…"); try { const response = await fetch(import.meta.env.VITE_INQUIRY_ENDPOINT ?? "/api/inquiry", { method:"POST", body:data, headers:{ Accept:"application/json" } }); const result = await response.json().catch(() => ({})); if (!response.ok || !result.ok) throw new Error(); form.reset(); setStatus("success"); setMessage("ありがとうございます。内容を確認し、適切な次のステップをご連絡します。"); trackAnalytics("generate_lead", { form_name:"ja_quote_page_project_brief", form_source:inquirySourceForLocation(), page_language:"ja", page_path:window.location.pathname }); } catch { setStatus("error"); setMessage("送信できませんでした。再度お試しいただくか、メールまたはWhatsAppでご連絡ください。"); } };
  return <main className="zhoni-page quote-page ja-page"><Header /><section className="quote-ledger-hero"><div className="quote-rail" aria-hidden="true"><strong>Z</strong><span>CUSTOM GOLF MERCHANDISE</span><i>BRANDED FOR A HIGHER STANDARD</i></div><div className="quote-ledger-main"><div className="quote-ledger-intro"><p>プロジェクト相談</p><h1>まず概要を<br />お聞かせください。</h1><p>単品からギフトセットまで、現時点で分かっている情報から確認します。</p></div><form className="quote-ledger-form" onSubmit={submit}><fieldset><legend><b>01</b><span>ご連絡先<small>ご返信先の担当者情報をご入力ください。</small></span></legend><div className="quote-form-row"><label>お名前<input required name="name" autoComplete="name" placeholder="ご担当者名" /></label><label>業務用メール<input required type="email" name="email" autoComplete="email" placeholder="you@company.com" /></label></div></fieldset><fieldset><legend><b>02</b><span>プロジェクト<small>重要な情報を共有いただければ、次の確認事項をご案内します。</small></span></legend><div className="quote-form-row"><label>製品またはプロジェクト<select required name="project_type" defaultValue={options.includes(selected) ? selected : ""}><option value="" disabled>製品またはカテゴリーを選択</option>{options.map(option => <option key={option}>{option}</option>)}</select></label><label>予定数量<input name="quantity_range" placeholder="例：200個" /></label></div><label className="quote-project-details">プロジェクト詳細<textarea required name="message" rows="5" placeholder="製品、カスタム内容、イベント日、納品国、パッケージ要件などをご記入ください。" /></label></fieldset><label className="honeypot" aria-hidden="true">Website<input name="company_website" tabIndex="-1" autoComplete="off" /></label><TurnstileField /><button className="quote-submit" type="submit" disabled={status === "submitting"}>{status === "submitting" ? "送信中…" : "プロジェクト概要を送信"} <Arrow /></button><div className={`quote-form-status ${status}`} role="status">{message}{status === "error" && <> <a href="mailto:sales@zhonigolf.com">メール</a><a href={WHATSAPP_URL}>WhatsApp</a></>}</div><small>入力情報はプロジェクトの確認と返信のためにのみ使用します。</small></form></div></section><LocalizedBuyerEvidence locale="ja" context="inquiry" /><section className="quote-after-inquiry"><div><p>直接のお問い合わせ</p><h2>メールまたはWhatsAppでも<br />概要をお送りいただけます。</h2><div className="after-inquiry-actions"><a href="mailto:sales@zhonigolf.com"><span>EMAIL</span><strong>sales@zhonigolf.com</strong><Arrow /></a><a href={WHATSAPP_URL}><span>WHATSAPP</span><strong>+86 177 5919 0848</strong><Arrow /></a></div></div></section><Footer /></main>;
}

export function JapaneseSite({ routeKey }) {
  const pages = { jaHome:<Home />, jaProducts:<Products />, jaSolutions:<Solutions />, jaProcess:<Process />, jaFaq:<Faq />, jaAbout:<About />, jaQuote:<Quote /> };
  return pages[routeKey] ?? null;
}
