import { useState } from "react";
import { LanguageSwitcher } from "./locale.jsx";
import { LocalizedBuyerEvidence } from "./LocalizedBuyerEvidence.jsx";
import { JapaneseFinalGuides } from "./JapaneseFinalGuides.jsx";

const WHATSAPP_URL = import.meta.env.VITE_WHATSAPP_URL ?? "https://wa.me/8617759190848";
const Arrow = () => <span aria-hidden="true">↗</span>;

function Header({ active = "guides" }) {
  const [menu,setMenu] = useState(false);
  return <header className={`zhoni-header ja-header ${menu ? "zhoni-header-open" : ""}`}><a className="zhoni-wordmark" href="/ja/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><button className="zhoni-menu" onClick={() => setMenu(value => !value)} aria-expanded={menu}>{menu ? "閉じる" : "メニュー"}</button><nav aria-label="メインナビゲーション"><a href="/ja/products/">製品</a><a className={active === "solutions" ? "active" : ""} href="/ja/solutions/">ソリューション</a><a className={active === "guides" ? "active" : ""} href="/ja/guides/">購入ガイド</a><a href="/ja/our-process/">進め方</a><a href="/ja/faq/">FAQ</a><a href="/ja/about/">会社情報</a></nav><LanguageSwitcher /><a className="zhoni-header-cta" href="/ja/request-a-quote/">プロジェクト相談 <Arrow /></a></header>;
}

function Footer() {
  return <footer className="site-footer"><div className="site-footer-main"><a className="zhoni-wordmark" href="/ja/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><div className="site-footer-copy"><p>カスタムゴルフ用品、ギフトセット、パッケージのプロジェクトパートナー。</p><span>製品選定 · ロゴ · サンプル · 品質 · パッケージ · 納品</span><div className="site-footer-contact"><b>直接のお問い合わせ</b><a href="mailto:sales@zhonigolf.com">sales@zhonigolf.com</a><a href={WHATSAPP_URL}>WhatsApp +86 177 5919 0848 <Arrow /></a></div></div><nav><a href="/ja/products/">製品</a><a href="/ja/solutions/">ソリューション</a><a href="/ja/guides/">購入ガイド</a><a href="/ja/capabilities/">対応範囲</a><a href="/ja/first-order-guide/">初回注文</a><a href="/ja/our-process/">進め方</a><a href="/ja/request-a-quote/">お問い合わせ <Arrow /></a></nav></div><div className="site-footer-base"><span>ZHONI · CUSTOM GOLF MERCHANDISE</span><span>運営法人: Xiamen Jindongyu Trading Co., Ltd.</span></div></footer>;
}

const hubContent = {
  jaGolfGifts: { active:"solutions", label:"カスタムゴルフギフト・プロジェクト", title:"アイデアから手渡しまで、\n一つのギフトプロジェクトとして。", intro:"受取人と目的を先に定め、製品、ブランド表現、パッケージ、納品準備を一つの流れにつなげます。", image:"/assets/images/zhoni-product-gift-sets-v3.png", steps:[["01","受取人と目的","顧客、選手、会員、スポンサー、社員など、対象と贈る場面を分けます。"],["02","製品またはセット","主役となる単品か、複数製品を組み合わせるセットかを決めます。"],["03","ロゴと承認","ロゴデータ、色、位置、校正やサンプルの必要性を確認します。"],["04","パッケージと納品","渡し方、希望受取日、納品先、必要な保護構造を一緒に検討します。"]], checklist:["受取人とイベントの目的","予定数量と予算の方向","製品またはセットの参考","ロゴ、色、ブランド資料","希望受取日と納品先"], links:[["製品カテゴリー","/ja/products/"],["大会ギフト","/ja/solutions/golf-tournament-gifts/"],["企業向けゴルフギフト","/ja/solutions/corporate-golf-gifts/"],["プロジェクト相談","/ja/request-a-quote/"]] },
  jaFirstOrder: { active:"guides", label:"MOQ・見積もり・初回注文", title:"初回注文は、価格より先に\n範囲を明確にする。", intro:"製品とロゴだけでなく、数量、希望日、パッケージ、納品先を整理すると、適用できるMOQと見積もり条件をより正確に確認できます。", image:"/assets/images/zhoni-golf-product-development-v2.png", steps:[["01","製品経路を定義","製品カテゴリー、使用目的、必要なカスタム範囲を整理します。"],["02","数量と仕様を準備","製品別数量、素材、色、ロゴ、参考画像をまとめます。"],["03","確認方法を選ぶ","校正、既存サンプル、新規サンプルなど必要な承認経路を検討します。"],["04","商業条件を整理","MOQ、見積範囲、スケジュール、パッケージ、納品条件を確認します。"]], checklist:["製品別の予定数量","ベクターロゴと色指定","希望する素材・構造の参考","パッケージの要否","希望受取日と納品先"], links:[["MOQガイド","/ja/guides/custom-golf-merchandise-moq-explained/"],["見積もり要因","/ja/guides/what-affects-a-custom-golf-merchandise-quote/"],["アートワーク準備","/ja/guides/prepare-artwork-for-custom-golf-products/"],["プロジェクト相談","/ja/request-a-quote/"]] },
  jaExportReadiness: { active:"guides", label:"品質・パッケージ・輸出準備", title:"生産完了ではなく、\n安全な引き渡しまで準備する。", intro:"合意した仕様に基づく品質確認、個装、ギフトボックス、外装カートン、納品先、引き渡し条件を出荷前につなげます。", image:"/assets/images/zhoni-carton-packing-v1.png", steps:[["01","製品品質基準","素材、寸法、縫製、ロゴ、部品、外観の確認項目を製品別に定めます。"],["02","個装とセット梱包","個装、箱、インサート、保護材が製品と配布方法に合うか確認します。"],["03","外装カートンと表示","入数、重量、寸法、カートンマーク、輸送中の保護を確認します。"],["04","納品先と条件","国、住所、希望受取日、連絡先、合意した引き渡し条件を整理します。"]], checklist:["承認済み仕様とロゴ","製品別の品質確認項目","個装とセット構成","外装カートン要件","納品先、連絡先、引き渡し条件"], links:[["品質チェックリスト","/ja/guides/custom-golf-merchandise-quality-checklist/"],["カスタムパッケージ","/ja/custom-golf-packaging/"],["納期計画","/ja/guides/how-to-plan-a-golf-merchandise-delivery-date/"],["プロジェクト相談","/ja/request-a-quote/"]] },
};

function HubPage({ pageKey }) {
  const content = hubContent[pageKey];
  const links = [...content.links, ["製品カテゴリー","/ja/products/"], ["Solutions","/ja/solutions/"], ["進め方","/ja/our-process/"], ["プロジェクト相談","/ja/request-a-quote/"]].filter((item,index,array) => array.findIndex(candidate => candidate[1] === item[1]) === index);
  return <main className="zhoni-page guide-page ja-page"><Header active={content.active} /><section className="guide-hero"><div><p>{content.label}</p><h1>{content.title.split("\n").map((line,index) => <span key={line}>{line}{index === 0 && <br />}</span>)}</h1><p>{content.intro}</p><a href="/ja/request-a-quote/">プロジェクト概要を送る <Arrow /></a></div><img src={content.image} alt={content.label} /></section><section className="guide-intro"><p>PROJECT ROUTE</p><h2>実際の購入判断につながる4段階。</h2><p>最終条件は製品と合意したプロジェクト範囲によって変わります。初期段階では、確認できる情報と未決事項を分けて整理してください。</p></section><section className="guide-products"><div>{content.steps.map(([number,title,copy]) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{copy}</p></article>)}</div></section><LocalizedBuyerEvidence locale="ja" context={`hub-${pageKey.replace("ja", "").toLowerCase()}`} /><section className="guide-decision"><div><p>購入担当者の準備</p><h2>次の会話を具体的にする情報。</h2><p>ブリーフは確定注文書ではありません。現在の方向と制約を共有し、適用可能な製品、確認方法、商業条件を検討する出発点です。</p></div><aside><p>CHECKLIST</p><h3>準備する基本情報</h3><ul>{content.checklist.map(item => <li key={item}>{item}</li>)}</ul></aside></section><section className="guide-products"><p>関連する購入経路</p><h2>必要な次の情報へ進む。</h2><div>{links.map(([title,href]) => <a href={href} key={href}>{title}<Arrow /></a>)}</div></section><Footer /></main>;
}

const guideContent = {
  jaBrandingGuide: { label:"ロゴ・ブランド表現", title:"製品と素材に合うロゴ方法を選ぶ", intro:"同じロゴでも、刺繍、型押し、印刷、パッチ、金属加工では線の再現性と印象が異なります。", image:"/assets/images/zhoni-embroidery-sample-v1.png", rows:[["刺繍","キャップ、タオル、織物製品。糸色、線幅、裏面への影響を確認"],["型押し／浮き出し","PU、革調素材、箱。控えめなトーン・オン・トーン表現"],["印刷","ボール、カード、箱、平面素材。色数と印刷可能範囲を確認"],["パッチ","複雑なロゴや反復使用。織り、刺繍、ラバーを比較"],["金属仕上げ","ボールマーカー、グリーンフォーク。メッキ、エナメル、刻印、端部を確認"]], checklist:["ベクターロゴ","最小文字と線幅","ブランドカラー値","製品別のロゴ位置","希望表現の参考画像"], faqs:[["すべての製品に同じロゴ方法を使うべきですか？","いいえ。素材ごとに適した方法を使い、サイズ、色、位置の共通ルールでコレクションの一貫性を作れます。"],["小さな文字も刺繍できますか？","糸の太さと生地による限界があります。小さな文字は簡略化、パッチ、印刷など別の方法が適する場合があります。"],["Pantone色はそのまま再現されますか？","糸、生地、金属、印刷素材で見え方が異なるため、基準色と許容範囲を確認する必要があります。"]] },
  jaArtworkGuide: { label:"アートワーク準備", title:"良いファイルだけでなく、適用指示を明確にする", intro:"ロゴ原本に加えて、製品、位置、サイズ、色、希望する仕上げを示すことで、実際の製造条件を確認できます。", image:"/assets/images/zhoni-golf-product-development-v2.png", rows:[["ロゴファイル","AI、EPS、PDF、SVGなど編集可能なベクターデータ"],["色の基準","Pantone、CMYK、RGB、HEX、または現物参考"],["位置とサイズ","製品面、方向、希望幅・高さ、余白"],["参考画像","希望する素材、刺繍、印刷、パッケージ表現"],["パッケージファイル","箱、スリーブ、カード、ラベルの展開図と文言"],["版管理","最終ファイル名、日付、承認担当者"]], checklist:["元のベクターロゴ","使用可能なロゴバリエーション","色指定","製品別の位置指示","最終文言とスペル確認"], faqs:[["PNGやJPGだけでも開始できますか？","初期検討には使えますが、生産用に再作成が必要になる場合があります。可能であれば元のベクターデータも提供してください。"],["ロゴサイズは供給側に任せてもよいですか？","製品構造に基づく推奨はできますが、ブランド規定と希望する見え方は購入担当者から共有する方が確実です。"],["サンプル前に校正を確認できますか？","確認方法は製品とカスタム範囲によって異なります。ブリーフ確認後に校正、既存サンプル、新規サンプルの経路を決めます。"]] },
  jaMoqGuide: { label:"MOQ・最小注文数量", title:"MOQは単なる数字ではなく、生産条件の結果", intro:"同じ製品でも、素材、色、構造、ロゴ、パッケージが変われば、適用できる最小注文数量も変わります。", image:"/assets/images/zhoni-material-direction-v1.png", rows:[["製品構造","既存構造か、新しい型・パターンが必要か"],["素材と色","既存材料か、別注生産・染色が必要か"],["ブランド表現","刺繍、印刷、パッチ、金属部品ごとの生産条件"],["数量配分","色、サイズ、デザイン別に数量をどう分けるか"],["パッケージ","箱、インサート、印刷物に別条件があるか"],["生産効率","設備準備と工程切り替えに必要な実際のロット"]], checklist:["総数量と製品別数量","色・サイズ別の内訳","カスタム構造の範囲","ロゴ方法","パッケージの有無"], faqs:[["複数製品の数量を合算してMOQを満たせますか？","通常は製品と工程ごとの条件があるため、単純合算できません。セットでも各製品の条件を確認します。"],["MOQより少ない数量を注文できますか？","既存素材や構造の利用可能性によって代替案がある場合もありますが、常に可能とは限りません。"],["数量が少ないと単価は大きく上がりますか？","固定の準備費用が少ない数量に配分されるため上がる場合があります。影響は仕様と工程に基づいて確認します。"]] },
  jaQuoteFactorsGuide: { label:"見積もりの構成要因", title:"単価ではなく、含まれる範囲を比較する", intro:"製品仕様、ロゴ、サンプル、パッケージ、納品条件が同じときに、初めて見積もりを有効に比較できます。", image:"/assets/images/zhoni-product-gift-sets-v3.png", rows:[["製品仕様","寸法、構造、素材、部品、仕上げ"],["数量構成","総数量と色・サイズ・デザイン別の内訳"],["ブランド表現","方法、位置、サイズ、色数、適用面数"],["確認方法","校正、サンプル、修正回数、承認範囲"],["パッケージ","個装、ギフト箱、インサート、印刷物"],["納品範囲","出荷条件、納品先、輸送、関税・税金の扱い"]], checklist:["同一の製品仕様書","数量内訳","ロゴとパッケージ範囲","サンプル費用と条件","引き渡し条件と除外項目"], faqs:[["最も安い単価を選べばよいですか？","製品、ロゴ、パッケージ、配送の範囲が異なる場合、低い数字が実際の総費用を意味するとは限りません。"],["配送費は製品見積もりに含めるべきですか？","比較するときは製品価格と輸送・税金の範囲を分けて確認すると明確です。"],["最終見積もり前になぜ質問が必要ですか？","範囲が曖昧なままだと各社が異なる前提を使い、同じ条件で比較できないためです。"]] },
  jaQualityChecklistGuide: { label:"品質確認", title:"製品別の基準と承認仕様を一緒に確認する", intro:"一般的な外観検査だけでは不十分です。製品構造、ロゴ方法、パッケージに合う確認項目が必要です。", image:"/assets/images/zhoni-quality-inspection-v1.png", rows:[["素材と色","承認基準、ロット内差異、表面の汚れ・損傷"],["寸法と構造","重要寸法、フィット、対称性、縫製、組み立て"],["ロゴ","位置、サイズ、色、鮮明さ、裏面への影響"],["部品","マグネット、クリップ、ファスナー、バックル、金属仕上げ"],["機能","実際の使用、開閉、固定、耐久に関する確認"],["包装とカートン","構成漏れ、ラベル、保護、入数、カートン状態"]], checklist:["承認サンプルまたは仕様書","寸法の許容範囲","ロゴ位置と色の基準","機能確認方法","包装構成表とカートン表示"], faqs:[["量産品は承認サンプルと完全に同じですか？","合理的な工程差が生じる場合があるため、重要特性と許容範囲を事前に合意する必要があります。"],["検査基準は誰が決めますか？","製品特性と購入者の要件に基づいて合意します。市場固有の必須要件があれば初期段階で共有してください。"],["パッケージも品質確認に含まれますか？","製品保護と受取体験に直接影響するため、構成、印刷、固定、外装状態も確認対象です。"]] },
  jaDeliveryDateGuide: { label:"納期計画", title:"イベント日ではなく、必要な受取日から逆算する", intro:"カスタム製品のスケジュールには、アートワーク、承認、サンプル、生産、パッケージ、国際配送が含まれます。", image:"/assets/images/zhoni-carton-packing-v1.png", rows:[["希望受取日","社内確認、仕分け、現場準備の余裕を含める"],["ブリーフ確定","製品、数量、ロゴ、パッケージ、納品先を確認"],["アートワーク・サンプル","データ修正、校正、サンプル作成、承認時間"],["生産","素材準備、工程、組み立て、品質確認"],["パッケージ","箱生産、セット組み、ラベル、外装カートン"],["配送","輸送方法、通関、現地休日、最終配達"]], checklist:["イベント日と希望受取日","承認担当者と回答時間","サンプルの要否","納品国と郵便番号","予備日程と代替案"], faqs:[["生産期間だけで納期を決められますか？","いいえ。承認の遅れ、パッケージ、配送時間も全体スケジュールに含める必要があります。"],["急ぎの案件にも対応できますか？","仕様、数量、素材の入手状況、納品先に基づいて確認しますが、品質確認を省略する前提では計画しません。"],["イベント前にどれくらい余裕が必要ですか？","現地での仕分けや再配送の可能性を考え、イベント直前ではなく内部準備が可能な受取日を設定してください。"]] },
  jaPostBriefGuide: { label:"お問い合わせ後の流れ", title:"ブリーフ送信後は、自動見積もりではなく確認が始まる", intro:"共有された情報から製品方向と不足条件を確認し、現実的な次の段階を決めます。", image:"/assets/images/zhoni-golf-product-development-v2.png", rows:[["1. 受付","連絡先、製品、数量、プロジェクト背景を確認"],["2. 適合性確認","製品経路、カスタム範囲、希望日、納品先を確認"],["3. 追加質問","仕様、ロゴ、パッケージ、条件の不足項目を整理"],["4. 方向の整理","適用できる製品、確認方法、商業上の前提をまとめる"],["5. 次の段階","見積もり、校正、サンプル、追加資料の経路を案内"]], checklist:["連絡可能な業務用メール","製品または参考画像","予定数量","希望受取日と納品先","ロゴとパッケージ要件"], faqs:[["問い合わせ後すぐ最終見積もりが届きますか？","必要な仕様が揃っていれば範囲を速やかに確認できます。不足があれば先に質問と前提を整理します。"],["資料がすべて揃っていなくても問い合わせできますか？","はい。現在分かっている内容と未決事項を分けて共有してください。"],["返信はどこに届きますか？","入力された業務用メールを基本連絡先とし、必要に応じてWhatsAppでも同じ案件情報を引き継げます。"]] },
};

function GuidePage({ pageKey }) {
  const content = guideContent[pageKey];
  return <main className="zhoni-page guide-page ja-page"><Header /><section className="guide-hero"><div><p>{content.label} · 購入ガイド</p><h1>{content.title}</h1><p>{content.intro}</p><small>実務確認 · 購入チェックリスト · よくある質問</small></div><img src={content.image} alt={content.label} /></section><section className="guide-intro"><p>BUYER REVIEW</p><h2>見積もりと生産の前に確認する基本項目。</h2><p>以下は初期検討の基準です。最終条件と許容範囲は、合意した製品仕様とプロジェクト範囲に基づいて確認します。</p></section><section className="guide-table"><table><thead><tr><th>確認領域</th><th>実務上の確認内容</th></tr></thead><tbody>{content.rows.map(row => <tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td></tr>)}</tbody></table></section><LocalizedBuyerEvidence locale="ja" context={`procurement-${pageKey.replace("ja", "").replace("Guide", "").toLowerCase()}`} /><section className="guide-decision"><div><p>プロジェクト準備</p><h2>同じ基準で比較できるブリーフを作る。</h2><p>具体的な情報は不要な推測を減らし、製品、MOQ、見積もり、サンプル、日程の実際の範囲を明確にします。</p></div><aside><p>CHECKLIST</p><h3>購入担当者が準備する内容</h3><ul>{content.checklist.map(item => <li key={item}>{item}</li>)}</ul></aside></section><section className="guide-faq"><p>よくある質問</p><h2>次の判断に使える回答。</h2><div>{content.faqs.map(([question,answer],index) => <article key={question}><b>{String(index + 1).padStart(2,"0")}</b><h3>{question}</h3><p>{answer}</p></article>)}</div></section><section className="guide-products"><p>関連するプロジェクト経路</p><h2>情報を実際のブリーフにつなげる。</h2><div><a href="/ja/products/">製品カテゴリー<Arrow /></a><a href="/ja/solutions/">Solutions<Arrow /></a><a href="/ja/our-process/">進め方<Arrow /></a><a href="/ja/request-a-quote/">プロジェクト相談<Arrow /></a></div></section><Footer /></main>;
}

export function JapaneseProcurement({ routeKey }) {
  if (hubContent[routeKey]) return <HubPage pageKey={routeKey} />;
  if (guideContent[routeKey]) return <GuidePage pageKey={routeKey} />;
  return <JapaneseFinalGuides routeKey={routeKey} />;
}
