import { useState } from "react";
import { LanguageSwitcher } from "./locale.jsx";

const WHATSAPP_URL = import.meta.env.VITE_WHATSAPP_URL ?? "https://wa.me/8617759190848";
const Arrow = () => <span aria-hidden="true">↗</span>;

function Header({ active }) {
  const [menu, setMenu] = useState(false);
  return <header className={`zhoni-header ko-header ${menu ? "zhoni-header-open" : ""}`}><a className="zhoni-wordmark" href="/ko/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><button className="zhoni-menu" onClick={() => setMenu(value => !value)} aria-expanded={menu}>{menu ? "닫기" : "메뉴"}</button><nav aria-label="주요 메뉴"><a className={active === "products" ? "active" : ""} href="/ko/products/">제품</a><a className={active === "solutions" ? "active" : ""} href="/ko/solutions/">솔루션</a><a className={active === "guides" ? "active" : ""} href="/ko/guides/">구매 가이드</a><a className={active === "process" ? "active" : ""} href="/ko/our-process/">진행 과정</a><a href="/ko/faq/">FAQ</a><a href="/ko/about/">회사 소개</a></nav><LanguageSwitcher /><a className="zhoni-header-cta" href="/ko/request-a-quote/">프로젝트 문의 <Arrow /></a></header>;
}

function Footer() {
  return <footer className="site-footer"><div className="site-footer-main"><a className="zhoni-wordmark" href="/ko/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><div className="site-footer-copy"><p>클럽, 골프대회, 기업 및 브랜드를 위한 맞춤 골프용품과 패키징.</p><span>기프트 세트 · 헤드커버 · 모자 · 타월 · 액세서리 · 패키징</span><div className="site-footer-contact"><b>직접 문의</b><a href="mailto:sales@zhonigolf.com">sales@zhonigolf.com</a><a href={WHATSAPP_URL}>WhatsApp +86 177 5919 0848 <Arrow /></a></div></div><nav><a href="/ko/products/">제품</a><a href="/ko/solutions/">솔루션</a><a href="/ko/guides/">구매 가이드</a><a href="/ko/our-process/">진행 과정</a><a href="/ko/faq/">FAQ</a><a href="/ko/request-a-quote/">문의 <Arrow /></a></nav></div><div className="site-footer-base"><span>ZHONI · CUSTOM GOLF MERCHANDISE</span><span>운영 법인: Xiamen Jindongyu Trading Co., Ltd.</span></div></footer>;
}

const categoryContent = {
  koHeadcovers: { eyebrow:"맞춤 골프 헤드커버", title:"클럽을 보호하고,\n브랜드를 기억하게.", intro:"드라이버, 페어웨이, 하이브리드와 퍼터 헤드커버를 사용 환경, 브랜드 표현과 세트 구성에 맞춰 개발합니다.", image:"/assets/images/zhoni-product-headcovers-v3.png", alt:"금색 Z 로고가 적용된 맞춤 골프 헤드커버", rows:[["제품 유형","드라이버 · 페어웨이 · 하이브리드 · 블레이드/말렛 퍼터"],["소재 방향","PU, 합성가죽, 패브릭, 니트 및 혼합 구조"],["브랜딩","자수, 아플리케, 디보싱, 패치 및 라벨"],["확인 포인트","클럽 핏, 개구부, 안감, 봉제, 로고 위치와 세트 구분"]], checklist:["필요한 클럽 유형과 수량 구성","원하는 소재와 촉감 참고","로고 원본 파일과 색상","개별 포장 또는 세트 패키징","희망 수령일과 배송지"], guide:"/ko/guides/custom-golf-headcovers-procurement-guide/", guideLabel:"헤드커버 구매 가이드" },
  koCaps: { eyebrow:"맞춤 골프 모자 & 바이저", title:"필드 위에서 이어지는\n브랜드 아이덴티티.", intro:"골프대회, 클럽 멤버 프로그램과 기업 행사를 위한 모자와 바이저를 핏, 기후, 원단과 로고 방식에 맞춰 검토합니다.", image:"/assets/images/zhoni-product-caps-v3.png", alt:"금색 Z 자수가 적용된 맞춤 골프 모자와 바이저", rows:[["스타일","구조형/비구조형 캡 · 퍼포먼스 캡 · 바이저 · 메시 캡"],["원단","코튼 트윌, 폴리에스터, 기능성 원단, 메시"],["브랜딩","평면/입체 자수, 직조 패치, 고무 패치, 측면·후면 로고"],["확인 포인트","크라운, 챙, 땀받이, 잠금 방식, 사이즈 범위"]], checklist:["착용 대상과 사용 계절","캡 또는 바이저 스타일","원단 성능과 색상","전면·측면·후면 로고 위치","수량, 일정과 배송지"], guide:"/ko/guides/custom-golf-caps-and-visors/", guideLabel:"골프 모자 구매 가이드" },
  koTowels: { eyebrow:"맞춤 골프 타월", title:"라운드의 실용성에\n브랜드 디테일을 더하다.", intro:"와플 원단, 자수, 클립과 마그네틱 구조를 실제 사용 장면과 기프트 구성에 맞춰 계획합니다.", image:"/assets/images/zhoni-product-magnetic-towel-v4.png", alt:"금색 Z 자수와 자석 구조가 적용된 맞춤 골프 타월", rows:[["제품 방향","와플 타월 · 마그네틱 타월 · 클립형 타월 · 기프트용 타월"],["소재","마이크로화이버 와플, 코튼 및 프로젝트별 대안"],["브랜딩","자수, 직조 라벨, 인쇄 및 패키지 카드"],["확인 포인트","크기, 중량, 테두리, 자석/클립 부품, 세탁 후 형태"]], checklist:["사용 목적과 원하는 크기","원단·색상 참고","자수 로고 크기와 위치","자석 또는 클립 필요 여부","개별 포장과 세트 구성"], guide:"/ko/guides/custom-golf-towels-procurement-guide/", guideLabel:"골프 타월 구매 가이드" },
  koAccessories: { eyebrow:"맞춤 골프 액세서리", title:"작은 제품에도\n분명한 브랜드 경험을.", intro:"볼 마커, 디봇 툴, 백 태그와 파우치를 플레이어 팩, 기업 선물과 클럽 프로그램의 역할에 맞춰 구성합니다.", image:"/assets/images/zhoni-product-accessories-v3.png", alt:"금색 Z 브랜딩이 적용된 골프 파우치와 백 태그", rows:[["제품군","볼 마커 · 디봇 툴 · 햇 클립 · 백 태그 · 파우치"],["소재","금속, PU, 직물 및 제품별 혼합 소재"],["브랜딩","각인, 에나멜, 디보싱, 자수, 인쇄"],["확인 포인트","크기, 도금색, 모서리, 부품 결합, 개별 포장"]], checklist:["선물 대상과 사용 목적","제품 조합과 수량","금속 마감 또는 소재 방향","로고 선 굵기와 색상","세트 패키징 여부"], guide:"/ko/guides/", guideLabel:"전체 구매 가이드" },
  koPackaging: { eyebrow:"맞춤 골프 패키징", title:"제품을 넘어\n전달 순간까지 완성하다.", intro:"기프트 박스, 인서트, 슬리브, 카드와 보호 포장을 제품 구성, 브랜드 경험과 실제 출고 조건에 맞춰 설계합니다.", image:"/assets/images/zhoni-product-packaging-v3.png", alt:"맞춤 인서트와 금색 Z 로고가 적용된 골프 기프트 박스", rows:[["구조","접이식 박스 · 리지드 박스 · 슬리브 · 인서트"],["표면 마감","인쇄, 포일, 엠보싱/디보싱, 라벨"],["내부 구성","EVA, 종이 보드, 패브릭, 완충재 및 제품 고정"],["확인 포인트","제품 치수, 개봉 순서, 보호 성능, 카톤 효율과 배송 방식"]], checklist:["박스에 들어갈 최종 제품 목록","제품별 치수와 배치 우선순위","브랜드 색상과 로고 파일","카드·슬리브·라벨 요구","배송지와 외부 카톤 조건"], guide:"/ko/guides/custom-golf-packaging-procurement-guide/", guideLabel:"패키징 구매 가이드" },
};

function CategoryPage({ pageKey }) {
  const c=categoryContent[pageKey];
  return <main className="zhoni-page category-page ko-page"><Header active="products" /><section className="category-hero"><aside className="category-rail"><strong>Z</strong><span>CUSTOM GOLF PRODUCTS</span></aside><div className="category-intro"><p>{c.eyebrow}</p><h1>{c.title.split("\n").map((line,i)=><span key={line}>{line}{i===0&&<br />}</span>)}</h1><p>{c.intro}</p><a href={`/ko/request-a-quote/?product=${encodeURIComponent(c.eyebrow)}`}>제품 문의 시작 <Arrow /></a><small>클럽 · 골프대회 · 기업 · 브랜드</small></div><img src={c.image} alt={c.alt} /></section><section className="guide-table"><table><thead><tr><th>검토 항목</th><th>실무 선택 방향</th></tr></thead><tbody>{c.rows.map(row=><tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td></tr>)}</tbody></table></section><section className="guide-decision"><div><p>PROJECT PREPARATION</p><h2>견적보다 먼저 사양의 기준을 맞춥니다.</h2><p>MOQ, 단가, 샘플 방식과 일정은 제품 구조, 맞춤 범위, 수량, 패키징과 배송지에 따라 달라집니다. 아래 정보가 있으면 더 현실적인 검토가 가능합니다.</p></div><aside><p>구매자 체크리스트</p><h3>브리프에 준비할 내용</h3><ul>{c.checklist.map(item=><li key={item}>{item}</li>)}</ul></aside></section><section className="guide-products"><p>관련 구매 경로</p><h2>제품 검토에서 실제 프로젝트로.</h2><div><a href={c.guide}>{c.guideLabel}<Arrow /></a><a href="/ko/solutions/">프로젝트 솔루션<Arrow /></a><a href="/ko/our-process/">제작 진행 과정<Arrow /></a><a href="/ko/request-a-quote/">프로젝트 문의<Arrow /></a></div></section><section className="guide-close"><div><p>READY TO REVIEW THE PROJECT?</p><h2>제품, 수량과 목표 일정을 알려주세요.</h2><a href="/ko/request-a-quote/">브리프 보내기 <Arrow /></a></div><img src={c.image} alt={c.alt} /></section><Footer /></main>;
}

const solutionContent={
  koTournamentGifts:{label:"골프대회 기념품 & 플레이어 팩",title:"대회의 역할과 수령 대상에 맞춘 골프 기프트.",intro:"참가자 웰컴 팩, 스폰서 선물, VIP 기프트와 수상자 상품은 같은 행사 안에서도 서로 다른 목적을 가집니다.",image:"/assets/images/zhoni-golf-tournament-gift-delivery-v2.png", steps:[["01","수령 그룹 구분","참가자, 스폰서, VIP, 운영팀과 수상자를 먼저 구분합니다."],["02","제품 구성","사용 시점, 예산 방향과 휴대성을 기준으로 제품 조합을 정합니다."],["03","브랜딩과 패키징","행사 로고, 스폰서 노출과 현장 배포 방식을 함께 검토합니다."],["04","일정 역산","행사일에서 생산, 확인, 포장과 배송에 필요한 시간을 역산합니다."]], products:"마그네틱 타월, 모자, 볼 마커, 디봇 툴, 파우치와 기프트 박스를 행사 목적에 맞춰 조합할 수 있습니다."},
  koCorporateGifts:{label:"기업 골프 선물",title:"관계와 전달 순간을 고려한 기업 골프 기프트.",intro:"고객 감사, 임직원 포상, 파트너 행사와 브랜드 캠페인을 위해 수령 대상과 선물의 격을 먼저 정합니다.",image:"/assets/images/zhoni-custom-golf-packaging-v2.png",steps:[["01","수령 대상","고객, 임원, 팀, 파트너 또는 행사 참석자를 구분합니다."],["02","선물 수준","한 가지 실용 제품 또는 프리미엄 세트 방향을 정합니다."],["03","브랜드 표현","로고의 크기와 노출 강도를 제품과 관계에 맞게 조율합니다."],["04","전달 준비","메시지 카드, 개별 포장, 배송지와 수령일을 확인합니다."]],products:"헤드커버, 모자, 타월, 금속 액세서리와 맞춤 박스를 하나의 기업 기프트 경험으로 구성할 수 있습니다."}
};

function SolutionDetail({ pageKey }){const c=solutionContent[pageKey];return <main className="zhoni-page corporate-page ko-page"><Header active="solutions"/><section className="corporate-hero"><aside className="corporate-rail"><strong>Z</strong><span>GOLF GIFT SOLUTIONS</span></aside><div><p>{c.label}</p><h1>{c.title}</h1><p>{c.intro}</p><a href="/ko/request-a-quote/">프로젝트 브리프 시작 <Arrow/></a></div><img src={c.image} alt={c.label}/></section><section className="corporate-ledger"><div><p>프로젝트 계획 경로</p>{c.steps.map(([n,t,d])=><article key={n}><b>{n}</b><h2>{t}</h2><p>{d}</p><span>→</span></article>)}</div><aside><p>PROJECT ESSENTIALS</p><ul><li><b>수령 대상</b><span>누가, 몇 명이 받는지</span></li><li><b>목표 일정</b><span>행사일 또는 희망 수령일</span></li><li><b>배송지</b><span>국가, 도시와 배포 지점</span></li><li><b>브랜드 자료</b><span>로고, 색상과 참고 이미지</span></li><li><b>패키징</b><span>개별 포장 또는 세트 구성</span></li></ul></aside></section><section className="corporate-closing"><img src="/assets/images/zhoni-golf-product-development-v2.png" alt="맞춤 골프용품 브랜딩 검토"/><div><p>COORDINATED GOLF GIFTS</p><h2>제품보다 먼저, 선물의 역할을 정합니다.</h2><p>{c.products}</p><a href="/ko/products/">제품군 살펴보기 <Arrow/></a></div></section><section className="guide-products"><p>연결된 구매 경로</p><h2>더 구체적인 다음 단계.</h2><div><a href="/ko/guides/">한국어 구매 가이드<Arrow/></a><a href="/ko/custom-golf-packaging/">맞춤 패키징<Arrow/></a><a href="/ko/our-process/">진행 과정<Arrow/></a><a href="/ko/request-a-quote/">프로젝트 문의<Arrow/></a></div></section><Footer/></main>}

const guides=[
  {key:"headcovers",label:"제품 & 맞춤 제작",title:"맞춤 골프 헤드커버 구매 가이드",copy:"유형, 소재, 클럽 핏, 로고와 샘플 확인 항목을 준비합니다.",href:"/ko/guides/custom-golf-headcovers-procurement-guide/"},
  {key:"caps",label:"제품 & 맞춤 제작",title:"맞춤 골프 모자·바이저 구매 가이드",copy:"스타일, 원단, 핏, 잠금 방식과 자수 위치를 비교합니다.",href:"/ko/guides/custom-golf-caps-and-visors/"},
  {key:"towels",label:"제품 & 맞춤 제작",title:"맞춤 골프 타월 구매 가이드",copy:"와플 원단, 마그네틱 구조, 크기와 자수 사양을 정리합니다.",href:"/ko/guides/custom-golf-towels-procurement-guide/"},
  {key:"packaging",label:"패키징 & 납품",title:"맞춤 골프 패키징 구매 가이드",copy:"박스 구조, 인서트, 인쇄, 보호와 출고 조건을 검토합니다.",href:"/ko/guides/custom-golf-packaging-procurement-guide/"},
];

function GuidesHub(){const [filter,setFilter]=useState("all");return <main className="zhoni-page guides-page ko-page"><Header active="guides"/><section className="guides-hero"><div><p>GOLF MERCHANDISE BUYER GUIDES</p><h1>맞춤 골프용품<br/>구매 가이드.</h1><p>제품을 고르는 단계부터 사양, MOQ, 샘플, 패키징과 납품 준비까지 실제 프로젝트 결정에 필요한 정보를 정리했습니다.</p></div><aside><b>첫 번째 질문</b><p>무엇을 만들지보다 누가, 언제, 어떤 목적으로 받을지부터 정하면 제품 선택이 더 분명해집니다.</p><a href="/ko/request-a-quote/">프로젝트 문의 <Arrow/></a></aside></section><section className="guide-filter" aria-label="구매 가이드 필터"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>전체</button><button className={filter==="product"?"active":""} onClick={()=>setFilter("product")}>제품 & 맞춤 제작</button><button className={filter==="packaging"?"active":""} onClick={()=>setFilter("packaging")}>패키징 & 납품</button></section><section className="guide-catalog">{guides.filter(g=>filter==="all"||(filter==="product"&&g.key!=="packaging")||(filter==="packaging"&&g.key==="packaging")).map((g,i)=><a href={g.href} key={g.key}><b>{String(i+1).padStart(2,"0")}</b><span>{g.label}</span><h2>{g.title}</h2><p>{g.copy}</p><em>가이드 읽기 <Arrow/></em></a>)}</section><section className="guide-decision"><div><p>구매 준비</p><h2>가이드를 읽고, 프로젝트 정보로 연결하세요.</h2><p>제품 방향, 수량, 브랜드 자료, 일정과 배송지가 모이면 MOQ와 견적을 더 정확하게 검토할 수 있습니다.</p></div><aside><p>공통 브리프 항목</p><ul>{["수령 대상과 사용 목적","제품 또는 참고 이미지","예상 수량","목표 수령일과 배송지","로고와 패키징 요구"].map(v=><li key={v}>{v}</li>)}</ul></aside></section><Footer/></main>}

const articleContent={
  koHeadcoversGuide:{label:"맞춤 골프 헤드커버",title:"헤드커버 구매 전에 결정해야 할 6가지",intro:"좋은 헤드커버 브리프는 외관뿐 아니라 클럽 유형, 핏, 소재, 로고, 세트 구분과 포장까지 연결합니다.",image:"/assets/images/zhoni-product-headcovers-v3.png",rows:[["클럽 구성","드라이버, 페어웨이, 하이브리드, 퍼터의 수량과 세트 구분"],["형태와 핏","클럽 크기, 개구부, 길이, 탄성 또는 잠금 구조"],["소재","PU, 패브릭, 니트의 촉감, 내구성과 로고 적합성"],["브랜딩","자수, 아플리케, 디보싱과 로고 위치"],["내부와 마감","안감, 봉제, 가장자리와 번호 표시"],["포장","개별 포장, 세트 박스와 라벨"]],checklist:["클럽 유형별 예상 수량","앞·뒤·측면 참고 이미지","벡터 로고와 색상값","원하는 소재 샘플 또는 사진","목표 수령일과 배송 국가"],faqs:[["헤드커버 MOQ는 모두 같나요?","아닙니다. 형태, 소재, 색상 수, 로고 방식과 세트 구성에 따라 적용 가능한 MOQ가 달라집니다."],["실물 샘플이 필요한가요?","새 구조나 정확한 핏이 중요한 경우 실물 확인이 유용합니다. 프로젝트에 따라 시안, 기존 샘플 또는 신규 샘플 경로를 검토합니다."],["드라이버와 퍼터를 같은 디자인으로 만들 수 있나요?","가능하지만 패널 구조와 로고 가용 면적이 다르므로 각 유형에 맞게 디자인을 조정해야 합니다."]],product:"/ko/custom-golf-headcovers/"},
  koTowelsGuide:{label:"맞춤 골프 타월",title:"원단, 크기와 부착 방식을 함께 선택하세요",intro:"골프 타월은 단순 인쇄물이 아니라 라운드 중 반복 사용하는 도구입니다. 흡수성, 건조, 부착 방식과 로고 가독성을 함께 확인합니다.",image:"/assets/images/zhoni-product-magnetic-towel-v4.png",rows:[["사용 장면","골프백, 카트, 플레이어 팩 또는 기프트 세트"],["원단","와플 구조, 중량, 촉감과 건조 특성"],["크기","접었을 때의 부피와 실제 닦는 면적"],["부착","자석, 카라비너, 아일렛 또는 별도 클립"],["로고","자수 크기, 위치, 실 색상과 뒷면 영향"],["포장","밴드, 폴리백, 카드 또는 기프트 박스"]],checklist:["원하는 가로·세로 크기","원단 색상과 참고 타월","자석 또는 클립 사양","자수 로고 원본","세트에 함께 넣을 제품"],faqs:[["마그네틱 타월은 무엇을 확인해야 하나요?","자석의 위치와 고정 방식, 금속 접점, 타월 중량과 실제 카트·클럽 환경에서의 사용성을 확인해야 합니다."],["자수 면적이 클수록 좋은가요?","반드시 그렇지는 않습니다. 큰 자수는 타월의 유연성과 건조에 영향을 줄 수 있어 로고 가독성과 실용성 사이의 균형이 필요합니다."],["여러 색상을 한 주문에 넣을 수 있나요?","가능 여부와 수량 분할 조건은 원단, 염색 또는 재고 방향과 전체 주문량에 따라 검토합니다."]],product:"/ko/custom-golf-towels/"},
  koCapsStyleGuide:{label:"맞춤 골프 모자 & 바이저",title:"스타일보다 먼저 착용 환경을 정하세요",intro:"골프 모자는 크라운 구조, 원단, 통기성, 잠금 방식과 로고 위치가 착용감과 완성도를 함께 결정합니다.",image:"/assets/images/zhoni-product-caps-v3.png",rows:[["착용자","성인/주니어, 성별 구성과 사이즈 범위"],["형태","구조형, 비구조형, 로우/미드 프로파일, 바이저"],["환경","더운 날씨, 장시간 라운드, 행사 또는 일상 사용"],["원단","코튼 트윌, 폴리에스터, 기능성, 메시"],["잠금","스냅, 버클, 벨크로 또는 스트레치 핏"],["브랜딩","전면 자수, 패치, 측면·후면 로고"]],checklist:["캡/바이저 스타일 참고","착용 지역과 계절","필요한 사이즈 범위","로고 위치별 파일","행사일과 수량"],faqs:[["골프용 모자에 기능성 원단이 필요한가요?","더운 기후와 장시간 착용이라면 경량, 건조와 통기성을 우선 검토할 수 있습니다. 선물의 촉감과 외관이 더 중요하면 트윌도 적합할 수 있습니다."],["입체 자수는 모든 로고에 적합한가요?","아닙니다. 가는 선, 작은 글자와 복잡한 디테일은 평면 자수나 패치가 더 선명할 수 있습니다."],["프리사이즈면 충분한가요?","수령자 구성과 잠금 방식에 따라 다릅니다. 실제 조절 범위와 크라운 깊이를 함께 확인해야 합니다."]],product:"/ko/custom-golf-caps/"},
  koPackagingGuide:{label:"맞춤 골프 패키징",title:"박스보다 먼저 제품과 전달 방식을 확정하세요",intro:"좋은 패키징은 보기 좋은 것뿐 아니라 제품을 고정하고, 운송 중 보호하며, 현장에서 쉽게 전달될 수 있어야 합니다.",image:"/assets/images/zhoni-product-packaging-v3.png",rows:[["제품 목록","최종 구성, 수량, 실제 치수와 무게"],["박스 구조","리지드, 접이식, 슬리브와 개봉 방식"],["인서트","제품 고정, 꺼내는 순서와 재질"],["브랜딩","인쇄, 포일, 엠보싱, 라벨과 카드"],["보호","스크래치, 눌림, 습기와 부품 충돌 방지"],["출고","외부 카톤, 카톤당 수량, 배송지와 인도 조건"]],checklist:["최종 제품과 실제 치수","원하는 개봉 경험","박스·인서트 참고 이미지","인쇄 파일과 색상 기준","배송 국가와 배포 방식"],faqs:[["제품 개발 전에 박스를 확정해도 되나요?","권장하지 않습니다. 최종 제품 치수와 배치가 달라지면 인서트와 박스 구조도 바뀔 수 있습니다."],["프리미엄 박스가 항상 필요한가요?","아닙니다. 행사 현장 배포, 국제 운송과 예산을 고려하면 접이식 구조나 슬리브가 더 적절할 수 있습니다."],["패키징 MOQ는 제품 MOQ와 같나요?","항상 같지 않습니다. 박스 구조, 인쇄, 인서트와 소재별 생산 조건이 별도로 적용될 수 있습니다."]],product:"/ko/custom-golf-packaging/"}
};

function GuideArticle({pageKey}){const c=articleContent[pageKey];return <main className="zhoni-page guide-page ko-page"><Header active="guides"/><section className="guide-hero"><div><p>{c.label} · 구매 가이드</p><h1>{c.title}</h1><p>{c.intro}</p><small>제품 선택 · 사양 준비 · 샘플 확인 · 프로젝트 문의</small></div><img src={c.image} alt={c.label}/></section><section className="guide-intro"><p>PRACTICAL BUYER REVIEW</p><h2>견적 전에 결정하면 좋은 실무 항목.</h2><p>모든 내용을 처음부터 확정할 필요는 없습니다. 현재 알고 있는 정보와 참고 자료를 정리하면 적용 가능한 제품, MOQ, 샘플과 일정 경로를 더 정확히 검토할 수 있습니다.</p></section><section className="guide-table"><table><thead><tr><th>검토 항목</th><th>구매자가 준비할 내용</th></tr></thead><tbody>{c.rows.map(row=><tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td></tr>)}</tbody></table></section><section className="guide-decision"><div><p>브리프 준비</p><h2>공급업체와 같은 기준으로 대화하세요.</h2><p>제품 사양, 로고, 수량, 일정, 포장과 배송지를 함께 전달하면 단가만 비교하는 것보다 실제 프로젝트 범위를 분명하게 확인할 수 있습니다.</p></div><aside><p>체크리스트</p><h3>문의 전에 준비할 자료</h3><ul>{c.checklist.map(v=><li key={v}>{v}</li>)}</ul></aside></section><section className="guide-faq"><p>자주 묻는 구매 질문</p><h2>다음 결정을 위한 현실적인 답변.</h2><div>{c.faqs.map(([q,a],i)=><article key={q}><b>{String(i+1).padStart(2,"0")}</b><h3>{q}</h3><p>{a}</p></article>)}</div></section><section className="guide-products"><p>관련 페이지</p><h2>가이드에서 실제 프로젝트로.</h2><div><a href={c.product}>관련 제품 페이지<Arrow/></a><a href="/ko/solutions/">Solutions<Arrow/></a><a href="/ko/our-process/">진행 과정<Arrow/></a><a href="/ko/request-a-quote/">프로젝트 문의<Arrow/></a></div></section><section className="guide-close"><div><p>READY TO PREPARE THE BRIEF?</p><h2>제품, 수량과 목표 일정을 공유하세요.</h2><a href="/ko/request-a-quote/">프로젝트 브리프 보내기 <Arrow/></a></div><img src={c.image} alt={c.label}/></section><Footer/></main>}

export function KoreanExpansion({routeKey}) {
  if (categoryContent[routeKey]) return <CategoryPage pageKey={routeKey}/>;
  if (solutionContent[routeKey]) return <SolutionDetail pageKey={routeKey}/>;
  if (articleContent[routeKey]) return <GuideArticle pageKey={routeKey}/>;
  if (routeKey === "koGuides") return <GuidesHub/>;
  return null;
}
