import { useState } from "react";
import { LanguageSwitcher } from "./locale.jsx";
import { TurnstileField } from "./turnstile.jsx";
import { trackAnalytics } from "./analytics.jsx";

const WHATSAPP_URL = import.meta.env.VITE_WHATSAPP_URL ?? "https://wa.me/8617759190848";
const Arrow = () => <span aria-hidden="true">↗</span>;
const productFamilies = [
  ["헤드커버", "클럽, 골프대회, 브랜드 프로젝트를 위한 맞춤형 헤드커버", "/assets/images/zhoni-product-headcovers-v3.png"],
  ["골프 모자 & 바이저", "착용 환경과 브랜드 표현을 함께 고려한 맞춤 헤드웨어", "/assets/images/zhoni-product-caps-v3.png"],
  ["마그네틱 골프 타월", "라운드 중 사용성과 자수 디테일을 고려한 골프 타월", "/assets/images/zhoni-product-magnetic-towel-v4.png"],
  ["골프 액세서리", "파우치, 백 태그, 볼 마커, 디봇 툴 등 브랜드 소품", "/assets/images/zhoni-product-accessories-v3.png"],
  ["기프트 세트", "수령 대상과 전달 순간에 맞춰 구성하는 골프 선물 세트", "/assets/images/zhoni-product-gift-sets-v3.png"],
  ["맞춤 패키징", "박스, 인서트, 카드와 마감까지 연결되는 선물 패키징", "/assets/images/zhoni-product-packaging-v3.png"],
];

function KoreanHeader({ active }) {
  const [menu, setMenu] = useState(false);
  return <header className={`zhoni-header ko-header ${menu ? "zhoni-header-open" : ""}`}>
    <a className="zhoni-wordmark" href="/ko/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a>
    <button className="zhoni-menu" onClick={() => setMenu(value => !value)} aria-expanded={menu}>{menu ? "닫기" : "메뉴"}</button>
    <nav aria-label="주요 메뉴"><a className={active === "products" ? "active" : ""} href="/ko/products/">제품</a><a className={active === "solutions" ? "active" : ""} href="/ko/solutions/">솔루션</a><a className={active === "process" ? "active" : ""} href="/ko/our-process/">진행 과정</a><a className={active === "faq" ? "active" : ""} href="/ko/faq/">FAQ</a><a className={active === "about" ? "active" : ""} href="/ko/about/">회사 소개</a></nav>
    <LanguageSwitcher />
    <a className="zhoni-header-cta" href="/ko/request-a-quote/">프로젝트 문의 <Arrow /></a>
  </header>;
}

function KoreanFooter() {
  return <footer className="site-footer"><div className="site-footer-main"><a className="zhoni-wordmark" href="/ko/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><div className="site-footer-copy"><p>클럽, 골프대회, 기업 및 브랜드를 위한 맞춤 골프용품과 패키징.</p><span>기프트 세트 · 헤드커버 · 모자 · 타월 · 액세서리 · 패키징</span><div className="site-footer-contact"><b>직접 문의</b><a href="mailto:sales@zhonigolf.com">sales@zhonigolf.com</a><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer">WhatsApp +86 177 5919 0848 <Arrow /></a></div></div><nav aria-label="하단 메뉴"><a href="/ko/products/">제품</a><a href="/ko/solutions/">솔루션</a><a href="/ko/our-process/">진행 과정</a><a href="/ko/faq/">FAQ</a><a href="/ko/about/">회사 소개</a><a href="/ko/request-a-quote/">문의 <Arrow /></a></nav></div><div className="site-footer-base"><span>ZHONI · CUSTOM GOLF MERCHANDISE</span><span>운영 법인: Xiamen Jindongyu Trading Co., Ltd.</span></div></footer>;
}

function KoreanHome() {
  return <main className="zhoni-page ko-page"><KoreanHeader />
    <section className="gifts-hero"><aside><span>CLUBS</span><span>EVENTS</span><span>BRANDS</span><span>ON COURSE</span></aside><div><p>맞춤 골프용품 · 기프트 세트 · 패키징</p><h1>브랜드의 이야기를<br />필드 위의 경험으로.</h1><p>ZHONI는 골프 클럽, 대회, 기업 프로그램과 브랜드를 위해 제품 개발, 로고 적용, 기프트 구성 및 패키징을 하나의 프로젝트로 연결합니다.</p><div className="gifts-fit"><article><b>추천 프로젝트</b><span>여러 제품을 일관된 브랜드 경험으로 구성해야 하는 B2B 프로젝트</span></article><article><b>시작에 필요한 정보</b><span>제품 방향, 예상 수량, 목표 일정, 배송 국가와 브랜드 자료</span></article></div><a href="/ko/request-a-quote/">프로젝트 브리프 작성 <Arrow /></a></div><img src="/assets/images/zhoni-golf-collection-hero-v2.png" alt="ZHONI 맞춤 골프용품과 기프트 패키지" /></section>
    <section className="gift-atlas"><p>ZHONI PROJECT ROUTE</p><h2>제품 하나부터 완성된 컬렉션까지.</h2><p className="atlas-intro">누가, 언제, 어떤 목적으로 받는지부터 확인한 뒤 제품·브랜딩·패키징의 적절한 방향을 함께 검토합니다.</p>{[["01","제품 선택","헤드커버, 모자, 타월, 액세서리 또는 기프트 세트의 기본 방향을 정합니다.","제품 보기","/ko/products/"],["02","프로그램 구성","골프대회, 기업 선물, 클럽 프로그램 또는 프라이빗 라벨 목적에 맞춰 구성합니다.","솔루션 보기","/ko/solutions/"],["03","사양과 샘플 확인","소재, 로고 방식, 색상, 패키징 및 필요한 승인 단계를 프로젝트별로 확인합니다.","진행 과정","/ko/our-process/"],["04","견적을 위한 브리프","예상 수량, 목표 일정, 배송지와 브랜드 자료를 공유하면 다음 단계를 안내합니다.","문의 시작","/ko/request-a-quote/"]].map(([n,t,c,l,h])=><article key={n}><b>{n}</b><div><h3>{t}</h3><p>{c}</p></div><a href={h}>{l} <Arrow /></a></article>)}</section>
    <section className="gifts-closing"><img src="/assets/images/zhoni-custom-golf-packaging-v2.png" alt="ZHONI 맞춤 골프 기프트 패키징" /><div><p>한 번의 브리프, 더 일관된 결과</p><h2>받는 사람과 전달 순간에 맞는 골프 프로젝트.</h2><p>제품, 수량, 일정과 패키징 요구사항을 알려주세요. 확인 가능한 정보부터 현실적인 다음 단계를 안내합니다.</p><a href="/ko/request-a-quote/">프로젝트 문의 <Arrow /></a></div></section><KoreanFooter />
  </main>;
}

function KoreanProducts() {
  return <main className="products-hub ko-page"><KoreanHeader active="products" /><section className="products-hero"><img src="/assets/images/zhoni-golf-collection-hero-v2.png" alt="ZHONI 맞춤 골프 제품 컬렉션" /><div className="products-hero-copy"><p className="products-kicker">맞춤 골프용품</p><h1>개별 제품을 넘어,<br />하나의 컬렉션으로.</h1><p>골프 클럽, 대회, 기업 프로그램과 브랜드를 위한 제품을 용도와 전달 경험에 맞춰 구성합니다.</p><a href="/ko/request-a-quote/">프로젝트 시작 <Arrow /></a></div></section><section className="family-index"><div className="family-heading"><p className="products-kicker">제품군</p><h2>Product Families</h2><p>목적은 달라도<br />브랜드 경험은 하나로.</p></div><div className="family-grid">{productFamilies.map(([title,copy,image])=><a className="family-card" href="/ko/request-a-quote/" key={title}><img src={image} alt={`ZHONI ${title}`} /><h3>{title}</h3><p>{copy}</p><span>— &nbsp; <Arrow /></span></a>)}</div></section><section className="products-intro"><p className="products-kicker">COORDINATED APPROACH</p><h2>제품, 브랜딩과 패키징을 함께 검토합니다.</h2><p>최종 사양, MOQ, 가격과 일정은 제품 구조, 맞춤 범위, 수량, 패키징 및 배송지에 따라 달라집니다. 먼저 프로젝트 맥락을 공유해 주세요.</p><a href="/ko/our-process/">프로젝트 진행 과정 <Arrow /></a></section><KoreanFooter /></main>;
}

function KoreanSolutions() {
  const programs=[["01","골프대회 플레이어 팩","참가자 웰컴 기프트, 스폰서 선물과 시상품 구성","/assets/images/zhoni-golf-tournament-gift-delivery-v2.png"],["02","기업 골프 기프트","고객 감사, 임직원 선물과 비즈니스 관계 프로그램","/assets/images/zhoni-custom-golf-packaging-v2.png"],["03","클럽 멤버 프로그램","회원 행사, 기념일과 반복 운영을 위한 맞춤 제품","/assets/images/zhoni-golf-product-development-v2.png"],["04","프라이빗 라벨 컬렉션","브랜드 제품군, 공동 브랜딩과 제품 개발 프로젝트","/assets/images/zhoni-golf-collection-hero-v2.png"]];
  return <main className="zhoni-page solutions-page ko-page"><KoreanHeader active="solutions" /><section className="solutions-index-hero"><div className="solutions-rail" aria-hidden="true"><strong>Z</strong><span>SOLUTIONS</span><i>PEOPLE · GOLF · BRANDS</i></div><div className="solutions-index-intro"><p>프로젝트 솔루션</p><h1>받는 사람과 목적에서<br />시작하는 골프용품.</h1><p>제품을 먼저 나열하기보다 대상, 행사, 수량과 전달 방식을 기준으로 적절한 프로젝트 방향을 선택합니다.</p></div><figure><img src="/assets/images/zhoni-custom-golf-packaging-v2.png" alt="맞춤 골프 기프트 세트와 패키징" /><figcaption>MORE THAN PRODUCTS.<br />A MORE THOUGHTFUL APPROACH.</figcaption></figure></section><section className="solutions-program-index">{programs.map(([n,t,c,img])=><a className="solutions-program" href="/ko/request-a-quote/" key={n}><b>{n}</b><img src={img} alt={t} /><div><h2>{t}</h2><p><strong>적합한 용도</strong>{c}</p></div><span>→</span></a>)}</section><section className="solutions-brief-bridge"><div><p>하나의 브리프로 시작하세요</p><h2>목표를 먼저 정하고,<br />컬렉션을 구성합니다.</h2><p>수령 대상, 수량, 목표 일정, 배송 국가와 원하는 제품 방향을 공유하면 적절한 검토 경로를 안내합니다.</p><a href="/ko/request-a-quote/">프로젝트 브리프 작성 <Arrow /></a></div><aside><p>유용한 시작 정보</p><ul><li>누가 받나요?</li><li>어떤 행사 또는 프로그램인가요?</li><li>예상 수량은 얼마인가요?</li><li>언제, 어느 국가에서 필요하나요?</li><li>로고와 참고 자료가 있나요?</li></ul></aside></section><KoreanFooter /></main>;
}

function KoreanProcess() {
  const steps=[["01","브리프","목표, 수령 대상, 예상 수량, 희망 일정과 배송지를 공유합니다.","/assets/images/zhoni-material-direction-v1.png"],["02","제품 방향","용도에 맞는 제품, 소재, 브랜딩과 패키징 방향을 검토합니다.","/assets/images/zhoni-embroidery-sample-v1.png"],["03","사양 확인","적용 가능한 도안, 시안, 샘플 또는 사양 확인 단계를 조율합니다.","/assets/images/zhoni-gift-packaging-process-v1.png"],["04","생산 준비","합의된 범위에 따라 생산과 품질 확인 기준을 정리합니다.","/assets/images/zhoni-quality-inspection-v1.png"],["05","포장 및 출고","포장, 카톤, 배송지와 인도 조건을 프로젝트별로 확인합니다.","/assets/images/zhoni-carton-packing-v1.png"]];
  return <main className="zhoni-page process-page ko-page"><KoreanHeader active="process" /><section className="process-hero"><div><p>진행 과정</p><h1>브리프에서 납품까지,<br />확인 가능한 단계로.</h1><p>맞춤 골프용품은 제품, 로고, 패키징과 일정이 연결된 프로젝트입니다. 각 단계의 확인 사항을 분명히 정리합니다.</p><a href="/ko/request-a-quote/">브리프 보내기 <Arrow /></a></div><img src="/assets/images/zhoni-material-direction-v1.png" alt="맞춤 골프용품 소재와 색상 검토" /></section><section className="process-ledger"><p>THE PROCESS</p><span>5단계 프로젝트 경로</span><div>{steps.map(([n,t,c,img])=><article key={n}><b>{n}</b><h2>{t}</h2><p>{c}</p><img src={img} alt={t} /></article>)}</div></section><section className="project-input"><div><p>고객이 준비할 정보</p><h2>정확한 검토는<br />구체적인 맥락에서 시작됩니다.</h2><p>처음부터 모든 사양이 확정될 필요는 없습니다. 알고 있는 정보와 참고 자료부터 공유해 주세요.</p></div><ul><li><b>용도</b><span>클럽, 대회, 기업 선물 또는 브랜드 컬렉션</span></li><li><b>예상 수량</b><span>대략적인 범위로 시작 가능</span></li><li><b>일정과 배송지</b><span>희망 수령일과 국가/도시</span></li><li><b>브랜드 자료</b><span>로고, 색상 규정과 참고 이미지</span></li><li><b>패키징</b><span>박스, 인서트, 카드 등 전달 방식</span></li></ul><aside>MOQ, 가격, 샘플, 생산 일정과 배송 조건은 합의된 프로젝트 범위에 따라 확인됩니다.</aside></section><KoreanFooter /></main>;
}

function KoreanFAQ() {
  const [open,setOpen]=useState(0); const items=[["어떤 골프용품을 맞춤 제작할 수 있나요?","헤드커버, 골프 모자와 바이저, 타월, 파우치, 백 태그, 볼 마커, 디봇 툴, 골프공, 기프트 세트와 패키징을 프로젝트 범위에 따라 검토할 수 있습니다."],["MOQ는 얼마인가요?","최소 주문 수량은 제품 구조, 소재, 로고 적용 방식, 색상, 패키징과 맞춤 범위에 따라 달라집니다. 원하는 제품과 예상 수량을 알려주시면 적용 가능한 조건을 확인합니다."],["샘플과 승인은 어떻게 진행되나요?","제품과 맞춤 범위에 따라 시안, 교정본 또는 실물 샘플 등 필요한 확인 단계가 달라집니다. 먼저 브리프를 검토한 뒤 적절한 승인 경로를 안내합니다."],["견적에 필요한 정보는 무엇인가요?","제품 방향, 예상 수량, 로고 자료, 패키징 요구, 목표 일정과 배송지가 필요합니다. 정보가 구체적일수록 실제 범위에 가까운 검토가 가능합니다."],["생산과 배송 기간은 얼마나 걸리나요?","도안 준비 상태, 제품, 샘플 확인, 수량, 생산 난이도, 패키징과 배송지에 따라 달라집니다. 반드시 희망 수령일을 함께 알려주세요."],["여러 제품을 하나의 기프트 세트로 구성할 수 있나요?","가능합니다. 수령 대상과 행사 목적을 기준으로 제품 조합, 로고 표현과 패키징을 하나의 경험으로 구성할 수 있습니다."]];
  return <main className="zhoni-page faq-page ko-page"><KoreanHeader active="faq" /><section className="faq-ledger-hero"><div><p>FAQ · 구매 검토 가이드</p><h1>맞춤 골프 프로젝트의<br />주요 질문과 답변.</h1><p>제품, 수량, 브랜딩, 패키징과 배송지를 함께 검토해야 더 정확한 다음 단계를 정할 수 있습니다.</p></div><aside><p>문의 전 준비 사항</p><h2>브리프에 포함하면 좋은 정보</h2><ol><li>수령 대상과 사용 목적</li><li>제품 방향 또는 참고 이미지</li><li>예상 수량과 희망 수령일</li><li>로고 자료와 패키징 요구</li><li>배송 국가와 도시</li></ol></aside></section><section className="capability-faq"><div><p>자주 묻는 질문</p><h2>실제 구매 검토에 필요한 답변.</h2></div><div>{items.map(([q,a],i)=><article key={q}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><span>{q}</span><b>{open===i?"−":"+"}</b></button>{open===i&&<p>{a}</p>}</article>)}</div></section><section className="faq-path"><p>다음 단계</p><div><a href="/ko/products/"><b>01</b><span>제품군 살펴보기</span><Arrow /></a><a href="/ko/solutions/"><b>02</b><span>프로젝트 방향 선택</span><Arrow /></a><a href="/ko/request-a-quote/"><b>03</b><span>브리프 작성</span><Arrow /></a></div></section><KoreanFooter /></main>;
}

function KoreanAbout() {
  return <main className="zhoni-page about-page ko-page"><KoreanHeader active="about" /><section className="zhoni-about-hero"><img src="/assets/images/zhoni-golf-collection-hero-v2.png" alt="ZHONI 맞춤 골프 기프트 컬렉션" /><div><p>ABOUT ZHONI</p><h1>목적이 분명한<br />골프 프로젝트를 위해.</h1><p>ZHONI는 클럽, 골프대회, 기업과 브랜드를 위한 맞춤 골프용품, 기프트 세트 및 패키징 프로젝트를 지원합니다.</p><a href="/ko/request-a-quote/">프로젝트 시작 <Arrow /></a></div></section><section className="relationship"><div><p>운영 구조</p><h2>분명한 주체,<br />일관된 프로젝트 관리.</h2></div><div className="relationship-copy"><p>ZHONI는 Xiamen Jindongyu Trading Co., Ltd.가 운영하는 맞춤 골프용품 전문 브랜드입니다. 제품 방향, 맞춤 제작, 패키징과 상업적 준비를 프로젝트 단위로 조율합니다.</p><p>모든 프로젝트에 같은 답을 적용하지 않습니다. 제품 범위, MOQ, 일정과 요구사항은 고객이 준비하는 실제 브리프를 기준으로 검토합니다.</p></div><div className="relationship-map"><article><b>ZHONI</b><span>맞춤 골프용품 전문 브랜드</span><small>제품 방향 · 맞춤 제작 · 고객 프로젝트</small></article><i>운영 법인</i><article><b>Xiamen Jindongyu<br />Trading Co., Ltd.</b><span>법적 운영 주체</span><small>상업 · 계약 · 운영 체계</small></article></div></section><KoreanFooter /></main>;
}

function KoreanQuote() {
  const [status,setStatus]=useState("idle"); const [message,setMessage]=useState("");
  const submit=async event=>{event.preventDefault();if(status==="submitting")return;const form=event.currentTarget;const data=new FormData(form);data.set("source","ko-direct-quote");data.set("page_language","ko");data.set("page_path",window.location.pathname);data.set("page_url",window.location.href);if(data.get("company_website")){form.reset();setStatus("success");setMessage("프로젝트 브리프가 접수되었습니다.");return;}setStatus("submitting");setMessage("브리프를 전송하고 있습니다…");try{const response=await fetch(import.meta.env.VITE_INQUIRY_ENDPOINT??"/api/inquiry",{method:"POST",body:data,headers:{Accept:"application/json"}});const result=await response.json().catch(()=>({}));if(!response.ok||!result.ok)throw new Error();form.reset();setStatus("success");setMessage("감사합니다. 담당자가 내용을 검토한 후 적절한 다음 단계로 회신드리겠습니다.");trackAnalytics("generate_lead",{form_name:"ko_quote_page_project_brief",page_language:"ko",page_path:window.location.pathname});}catch{setStatus("error");setMessage("전송하지 못했습니다. 다시 시도하거나 이메일 또는 WhatsApp으로 문의해 주세요.");}};
  return <main className="zhoni-page quote-page ko-page"><KoreanHeader active="quote" /><section className="quote-ledger-hero"><div className="quote-rail" aria-hidden="true"><strong>Z</strong><span>CUSTOM GOLF MERCHANDISE</span><i>BRANDED FOR A HIGHER STANDARD</i></div><div className="quote-ledger-main"><div className="quote-ledger-intro"><p>프로젝트 문의</p><h1>먼저 브리프를<br />알려주세요.</h1><p>제품 하나부터 완성된 기프트 세트까지, 확인 가능한 정보부터 함께 검토합니다.</p></div><form className="quote-ledger-form" onSubmit={submit}><fieldset><legend><b>01</b><span>연락처<small>회신받을 담당자 정보를 입력해 주세요.</small></span></legend><div className="quote-form-row"><label>이름<input required name="name" autoComplete="name" placeholder="담당자 이름" /></label><label>업무용 이메일<input required type="email" name="email" autoComplete="email" placeholder="you@company.com" /></label></div></fieldset><fieldset><legend><b>02</b><span>프로젝트<small>핵심 정보를 공유하면 다음 단계를 안내합니다.</small></span></legend><div className="quote-form-row"><label>제품 또는 프로젝트<select required name="project_type" defaultValue=""><option value="" disabled>제품 또는 유형 선택</option><option>맞춤 골프 헤드커버</option><option>맞춤 골프 모자 &amp; 바이저</option><option>맞춤 골프 타월</option><option>볼 마커 &amp; 디봇 툴</option><option>골프 액세서리</option><option>골프 기프트 세트</option><option>골프대회 용품</option><option>기업 골프 기프트</option><option>프라이빗 라벨 컬렉션</option><option>맞춤 패키징</option></select></label><label>예상 수량<input name="quantity_range" placeholder="예: 200개" /></label></div><label className="quote-project-details">프로젝트 상세<textarea required name="message" rows="5" placeholder="제품, 맞춤 아이디어, 행사일, 배송 국가와 패키징 요구사항을 알려주세요." /></label></fieldset><label className="honeypot" aria-hidden="true">Website<input name="company_website" tabIndex="-1" autoComplete="off" /></label><TurnstileField /><button className="quote-submit" type="submit" disabled={status==="submitting"}>{status==="submitting"?"전송 중…":"프로젝트 브리프 보내기"} <Arrow /></button><div className={`quote-form-status ${status}`} role="status">{message}{status==="error"&&<> <a href="mailto:sales@zhonigolf.com">이메일</a><a href={WHATSAPP_URL}>WhatsApp</a></>}</div><small>입력한 정보는 프로젝트 검토와 회신을 위해서만 사용합니다.</small></form></div></section><section className="quote-after-inquiry"><div><p>직접 문의</p><h2>이메일 또는 WhatsApp으로도<br />프로젝트 정보를 보낼 수 있습니다.</h2><div className="after-inquiry-actions"><a href="mailto:sales@zhonigolf.com"><span>EMAIL</span><strong>sales@zhonigolf.com</strong><Arrow /></a><a href={WHATSAPP_URL}><span>WHATSAPP</span><strong>+86 177 5919 0848</strong><Arrow /></a></div></div></section><KoreanFooter /></main>;
}

export function KoreanSite({ routeKey }) {
  const pages={koHome:<KoreanHome />,koProducts:<KoreanProducts />,koSolutions:<KoreanSolutions />,koProcess:<KoreanProcess />,koFaq:<KoreanFAQ />,koAbout:<KoreanAbout />,koQuote:<KoreanQuote />};
  return pages[routeKey] ?? pages.koHome;
}
