import { useState } from "react";
import { LanguageSwitcher } from "./locale.jsx";

const WHATSAPP_URL = import.meta.env.VITE_WHATSAPP_URL ?? "https://wa.me/8617759190848";
const Arrow = () => <span aria-hidden="true">↗</span>;

function Header({ active = "guides" }) {
  const [menu,setMenu]=useState(false);
  return <header className={`zhoni-header ko-header ${menu?"zhoni-header-open":""}`}><a className="zhoni-wordmark" href="/ko/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><button className="zhoni-menu" onClick={()=>setMenu(v=>!v)}>{menu?"닫기":"메뉴"}</button><nav><a href="/ko/products/">제품</a><a href="/ko/solutions/">솔루션</a><a className={active==="guides"?"active":""} href="/ko/guides/">구매 가이드</a><a className={active==="process"?"active":""} href="/ko/our-process/">진행 과정</a><a href="/ko/faq/">FAQ</a><a href="/ko/about/">회사 소개</a></nav><LanguageSwitcher/><a className="zhoni-header-cta" href="/ko/request-a-quote/">프로젝트 문의 <Arrow/></a></header>;
}
function Footer(){return <footer className="site-footer"><div className="site-footer-main"><a className="zhoni-wordmark" href="/ko/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><div className="site-footer-copy"><p>맞춤 골프용품, 기프트 세트와 패키징을 위한 프로젝트 파트너.</p><span>제품 선택 · 브랜딩 · 샘플 · 품질 · 패키징 · 납품</span><div className="site-footer-contact"><b>직접 문의</b><a href="mailto:sales@zhonigolf.com">sales@zhonigolf.com</a><a href={WHATSAPP_URL}>WhatsApp +86 177 5919 0848 <Arrow/></a></div></div><nav><a href="/ko/products/">제품</a><a href="/ko/solutions/">솔루션</a><a href="/ko/guides/">구매 가이드</a><a href="/ko/first-order-guide/">첫 주문</a><a href="/ko/our-process/">진행 과정</a><a href="/ko/request-a-quote/">문의 <Arrow/></a></nav></div><div className="site-footer-base"><span>ZHONI · CUSTOM GOLF MERCHANDISE</span><span>운영 법인: Xiamen Jindongyu Trading Co., Ltd.</span></div></footer>}

const hubContent={
  koGolfGifts:{active:"solutions",label:"맞춤 골프 선물 프로젝트 허브",title:"아이디어에서 전달까지,\n하나의 골프 기프트 프로젝트로.",intro:"선물의 대상과 목적을 먼저 정한 뒤 제품, 브랜드 표현, 패키징과 납품 준비를 연결합니다.",image:"/assets/images/zhoni-product-gift-sets-v3.png",steps:[["01","수령 대상과 목적","고객, 선수, 회원, 스폰서 또는 임직원과 전달 상황을 구분합니다."],["02","제품 또는 세트","한 가지 핵심 제품인지 여러 제품을 조합한 세트인지 정합니다."],["03","브랜딩과 승인","로고 파일, 색상, 위치와 필요한 시안·샘플 경로를 확인합니다."],["04","패키징과 납품","전달 방식, 목표 수령일, 배송지와 포장 구조를 함께 검토합니다."]],checklist:["수령 대상과 행사 목적","예상 수량과 예산 방향","제품 또는 기프트 세트 참고","로고·색상·브랜드 자료","희망 수령일과 배송지"],links:[["제품군","/ko/products/"],["골프대회 기프트","/ko/solutions/golf-tournament-gifts/"],["기업 골프 선물","/ko/solutions/corporate-golf-gifts/"],["프로젝트 문의","/ko/request-a-quote/"]]},
  koFirstOrder:{active:"guides",label:"MOQ · 견적 · 첫 주문",title:"첫 주문은 가격보다\n명확한 범위에서 시작됩니다.",intro:"제품과 로고만 보내는 것보다 수량, 일정, 패키징과 배송지를 함께 정리하면 적용 가능한 MOQ와 견적을 더 정확히 검토할 수 있습니다.",image:"/assets/images/zhoni-golf-product-development-v2.png",steps:[["01","제품 경로 정의","제품군, 사용 목적과 필요한 맞춤 수준을 정합니다."],["02","수량과 사양 준비","제품별 수량, 소재, 색상, 로고와 참고 자료를 정리합니다."],["03","확인 방식 검토","시안, 교정본, 기존 샘플 또는 신규 샘플 필요 여부를 확인합니다."],["04","상업 조건 정리","MOQ, 견적 범위, 일정, 패키징, 배송지와 인도 조건을 맞춥니다."]],checklist:["제품별 예상 수량","벡터 로고와 색상값","원하는 소재·구조 참고","패키징 필요 여부","목표 수령일과 목적지"],links:[["MOQ 가이드","/ko/guides/custom-golf-merchandise-moq-explained/"],["견적 요소","/ko/guides/what-affects-a-custom-golf-merchandise-quote/"],["아트워크 준비","/ko/guides/prepare-artwork-for-custom-golf-products/"],["프로젝트 문의","/ko/request-a-quote/"]]},
  koExportReadiness:{active:"guides",label:"품질 · 패키징 · 수출 준비",title:"생산 완료가 아니라,\n안전한 인도까지 준비합니다.",intro:"합의된 사양에 맞는 품질 확인, 개별 포장, 외부 카톤, 목적지와 인도 조건을 출고 전에 연결합니다.",image:"/assets/images/zhoni-carton-packing-v1.png",steps:[["01","제품 품질 기준","소재, 치수, 봉제, 로고, 부품과 외관 기준을 제품별로 확인합니다."],["02","포장 확인","개별 포장, 기프트 박스, 인서트와 보호재가 제품에 맞는지 검토합니다."],["03","카톤과 표시","카톤당 수량, 중량, 크기, 마킹과 운송 중 보호를 확인합니다."],["04","목적지와 조건","배송 국가, 주소, 희망 수령일과 합의된 인도 조건을 정리합니다."]],checklist:["승인된 제품 사양과 로고","제품별 품질 확인 항목","개별 포장과 세트 구성","외부 카톤 요구","목적지·연락처·인도 조건"],links:[["품질 체크리스트","/ko/guides/custom-golf-merchandise-quality-checklist/"],["맞춤 패키징","/ko/custom-golf-packaging/"],["납기 계획","/ko/guides/how-to-plan-a-golf-merchandise-delivery-date/"],["프로젝트 문의","/ko/request-a-quote/"]]}
};

function HubPage({pageKey}){const c=hubContent[pageKey];return <main className="zhoni-page guide-page ko-page"><Header active={c.active}/><section className="guide-hero"><div><p>{c.label}</p><h1>{c.title.split("\n").map((v,i)=><span key={v}>{v}{i===0&&<br/>}</span>)}</h1><p>{c.intro}</p><a href="/ko/request-a-quote/">프로젝트 브리프 시작 <Arrow/></a></div><img src={c.image} alt={c.label}/></section><section className="guide-intro"><p>PROJECT ROUTE</p><h2>실제 구매 결정을 위한 네 단계.</h2><p>최종 조건은 합의된 제품과 프로젝트 범위에 따라 달라집니다. 초기 검토 단계에서는 확인 가능한 정보부터 정리하면 됩니다.</p></section><section className="guide-products"><div>{c.steps.map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div></section><section className="guide-decision"><div><p>구매자 준비 사항</p><h2>다음 대화를 더 구체적으로 만드는 정보.</h2><p>브리프는 확정 주문서가 아닙니다. 현재의 방향과 제약 조건을 공유해 적용 가능한 제품, 확인 절차와 상업 조건을 검토하는 출발점입니다.</p></div><aside><p>CHECKLIST</p><h3>준비할 핵심 정보</h3><ul>{c.checklist.map(v=><li key={v}>{v}</li>)}</ul></aside></section><section className="guide-products"><p>연결된 구매 경로</p><h2>필요한 다음 내용을 확인하세요.</h2><div>{c.links.map(([t,h])=><a href={h} key={h}>{t}<Arrow/></a>)}</div></section><Footer/></main>}

const guideContent={
  koBrandingGuide:{label:"로고 & 브랜딩 방식",title:"제품과 소재에 맞는 로고 방식을 선택하세요",intro:"같은 로고도 자수, 디보싱, 인쇄, 패치와 금속 마감에서 선명도와 인상이 달라집니다.",image:"/assets/images/zhoni-embroidery-sample-v1.png",rows:[["자수","모자, 타월과 패브릭 제품 · 실 색상, 선 굵기와 뒷면 영향 확인"],["디보싱/엠보싱","PU, 가죽 계열과 박스 · 톤온톤의 절제된 표현"],["인쇄","골프공, 카드, 박스와 평면 소재 · 색상과 인쇄 면적 확인"],["패치","복잡한 로고와 반복 사용 · 직조, 자수, 고무 소재 비교"],["금속 마감","볼 마커와 디봇 툴 · 도금, 에나멜, 각인과 모서리 확인"]],checklist:["벡터 로고 파일","최소 글자와 선 굵기","브랜드 색상값","제품별 로고 위치","원하는 표현의 참고 이미지"],faqs:[["모든 제품에 같은 로고 방식을 써야 하나요?","아닙니다. 제품 소재에 적합한 방식을 사용하면서 크기, 색상과 위치의 공통 규칙을 유지하면 컬렉션의 일관성을 만들 수 있습니다."],["작은 글자도 자수할 수 있나요?","실 굵기와 원단에 따라 한계가 있습니다. 작은 글자는 단순화하거나 패치·인쇄 등 다른 방식을 검토할 수 있습니다."],["Pantone 색상이 그대로 나오나요?","실, 원단, 금속과 인쇄 소재마다 표현 차이가 있으므로 기준 색상과 허용 범위를 확인해야 합니다."]]},
  koArtworkGuide:{label:"아트워크 준비",title:"좋은 파일보다 중요한 것은 명확한 적용 지시입니다",intro:"로고 원본과 함께 제품, 위치, 크기, 색상과 원하는 마감 방향을 전달해야 실제 검토가 가능합니다.",image:"/assets/images/zhoni-golf-product-development-v2.png",rows:[["로고 파일","AI, EPS, PDF, SVG 등 편집 가능한 벡터 파일"],["색상 기준","Pantone, CMYK, RGB, HEX 또는 실물 참고"],["위치와 크기","제품 면, 방향, 예상 폭·높이와 여백"],["참고 이미지","원하는 원단, 자수, 인쇄와 패키징 표현"],["패키징 파일","박스, 슬리브, 카드, 라벨의 도면과 문구"],["버전 관리","최종 파일명, 날짜와 승인 담당자"]],checklist:["원본 벡터 로고","사용 가능한 로고 변형","색상 규정","제품별 위치 표시","최종 문구와 철자 확인"],faqs:[["PNG나 JPG만 있어도 시작할 수 있나요?","초기 검토에는 사용할 수 있지만 생산 파일로 다시 정리해야 할 수 있습니다. 가능한 경우 원본 벡터 파일을 함께 제공하세요."],["로고 크기를 공급업체가 정해도 되나요?","제품 구조에 맞는 권장안을 제시할 수 있지만 브랜드 가이드와 원하는 노출 수준은 구매자가 알려주는 것이 좋습니다."],["샘플 전에 시안을 받을 수 있나요?","적용 가능한 확인 방식은 제품과 맞춤 범위에 따라 다릅니다. 브리프 검토 후 시안, 교정본 또는 샘플 경로를 정합니다."]]},
  koMoqGuide:{label:"MOQ 최소 주문 수량",title:"MOQ는 단순한 숫자가 아니라 생산 조건의 결과입니다",intro:"같은 제품이라도 소재, 색상, 구조, 로고와 패키징이 달라지면 적용 가능한 최소 주문 수량도 달라집니다.",image:"/assets/images/zhoni-material-direction-v1.png",rows:[["제품 구조","기존 구조인지 신규 금형·패턴이 필요한지"],["소재와 색상","재고 원단 또는 별도 생산·염색 여부"],["브랜딩","자수, 인쇄, 패치와 금속 부품의 개별 최소 수량"],["수량 분할","색상, 사이즈, 디자인별 수량이 어떻게 나뉘는지"],["패키징","박스, 인서트와 인쇄물의 별도 생산 조건"],["생산 효율","설비 준비와 공정 전환에 필요한 실제 배치"]],checklist:["총수량과 제품별 수량","색상·사이즈별 분할","맞춤 구조의 깊이","로고 적용 방식","패키징 포함 여부"],faqs:[["여러 제품의 수량을 합쳐 MOQ를 맞출 수 있나요?","보통 제품과 공정별 MOQ가 적용되므로 단순 합산되지 않습니다. 세트 구성이라도 각 품목의 조건을 확인해야 합니다."],["MOQ보다 적게 주문할 수 있나요?","제품과 기존 소재·구조의 가용성에 따라 대안이 있을 수 있지만 항상 가능한 것은 아닙니다."],["MOQ가 낮으면 단가가 많이 오르나요?","고정 준비 비용이 적은 수량에 배분되기 때문에 단가가 높아질 수 있습니다. 정확한 영향은 사양과 공정에 따라 검토합니다."]]},
  koQuoteFactorsGuide:{label:"견적 구성 요소",title:"단가가 아니라 포함 범위를 비교하세요",intro:"맞춤 골프용품 견적은 제품 사양, 로고, 샘플, 포장과 배송 조건이 같을 때에만 의미 있게 비교할 수 있습니다.",image:"/assets/images/zhoni-product-gift-sets-v3.png",rows:[["제품 사양","크기, 구조, 소재, 부품과 마감"],["수량 구성","총수량과 색상·사이즈·디자인별 분할"],["브랜딩","방법, 위치, 크기, 색상 수와 적용 면 수"],["확인 절차","시안, 교정본, 샘플과 수정 범위"],["패키징","개별 포장, 기프트 박스, 인서트와 인쇄물"],["배송 범위","출발 조건, 목적지, 운송, 관세·세금 포함 여부"]],checklist:["동일한 제품 사양서","수량 분할표","로고와 패키징 범위","샘플 비용과 환급 조건","인도 조건과 제외 항목"],faqs:[["가장 낮은 단가를 선택하면 되나요?","제품, 로고, 포장과 배송의 포함 범위가 다르면 낮은 숫자가 실제 총비용을 의미하지 않을 수 있습니다."],["배송비를 제품 견적에 포함해야 하나요?","비교 목적이라면 제품 가격과 운송·세금 범위를 구분해 확인하는 것이 좋습니다."],["왜 최종 견적 전에 질문이 필요한가요?","제품과 범위가 불분명한 상태에서는 공급업체마다 서로 다른 가정을 사용하게 되어 비교가 어려워집니다."]]},
  koQualityChecklistGuide:{label:"품질 검사",title:"제품별 기준과 승인 사양을 함께 확인하세요",intro:"일반적인 외관 검사만으로는 부족합니다. 제품 구조, 로고 방식과 패키징에 맞는 확인 항목이 필요합니다.",image:"/assets/images/zhoni-quality-inspection-v1.png",rows:[["소재와 색상","승인 기준과 로트 내 차이, 표면 오염과 손상"],["치수와 구조","핵심 치수, 핏, 대칭, 봉제와 조립"],["로고","위치, 크기, 색상, 선명도와 뒷면 영향"],["부품","자석, 클립, 지퍼, 버클과 금속 마감"],["기능","실제 사용, 개폐, 고정과 내구 관련 확인"],["포장과 카톤","구성 누락, 라벨, 보호와 카톤 수량"]],checklist:["승인 샘플 또는 사양서","허용 치수 범위","로고 위치·색상 기준","기능 확인 방법","포장 구성표와 카톤 마킹"],faqs:[["승인 샘플과 완전히 같아야 하나요?","대량 생산에는 합리적인 공정 편차가 있을 수 있으므로 중요한 특성과 허용 범위를 미리 정하는 것이 필요합니다."],["검사 기준은 누가 정하나요?","제품 특성과 구매자의 요구를 기준으로 합의해야 합니다. 시장별 필수 요구사항이 있다면 초기에 공유해야 합니다."],["포장도 품질 검사에 포함되나요?","포장은 제품 보호와 전달 경험에 직접 영향을 주므로 구성, 인쇄, 고정과 카톤 상태를 함께 확인해야 합니다."]]},
  koDeliveryDateGuide:{label:"납기 계획",title:"행사일이 아니라 필요한 수령일에서 역산하세요",intro:"맞춤 제품 일정에는 아트워크, 확인, 샘플, 생산, 패키징과 국제 배송이 모두 포함됩니다.",image:"/assets/images/zhoni-carton-packing-v1.png",rows:[["목표 수령일","행사 준비와 내부 배포에 필요한 여유 포함"],["브리프 확정","제품, 수량, 로고, 패키징과 목적지 확인"],["아트워크·샘플","파일 수정, 시안, 샘플 제작과 승인 시간"],["생산","소재 준비, 공정, 조립과 품질 확인"],["패키징","박스 생산, 세트 조립, 라벨과 카톤"],["배송","운송 방식, 통관, 현지 휴일과 최종 배송"]],checklist:["행사일과 희망 수령일","승인 담당자와 응답 시간","샘플 필요 여부","배송 국가·우편번호","예비 일정과 대체안"],faqs:[["생산 기간만 알면 납기를 정할 수 있나요?","아닙니다. 승인 지연, 패키징과 배송 시간이 전체 일정에 포함되어야 합니다."],["급한 프로젝트도 가능한가요?","사양, 수량, 소재 가용성과 배송지에 따라 검토할 수 있지만 품질 확인 단계를 생략하는 전제로 계획해서는 안 됩니다."],["행사일까지 며칠의 여유가 필요한가요?","현장 분류와 재배송 가능성을 고려해 행사 직전이 아닌 내부 준비가 가능한 수령일을 정하는 것이 좋습니다."]]},
  koPostBriefGuide:{label:"문의 후 진행 과정",title:"브리프를 보내면 자동 견적이 아니라 검토가 시작됩니다",intro:"제출된 정보를 바탕으로 제품 방향과 누락된 조건을 확인한 뒤 현실적인 다음 단계를 정합니다.",image:"/assets/images/zhoni-golf-product-development-v2.png",rows:[["1. 접수","연락처, 제품, 수량과 프로젝트 맥락 확인"],["2. 적합성 검토","제품 경로, 맞춤 범위, 일정과 목적지 검토"],["3. 추가 질문","사양, 로고, 패키징과 조건 중 필요한 항목 확인"],["4. 방향 정리","적용 가능한 제품, 확인 절차와 상업 가정 정리"],["5. 다음 단계","견적, 시안, 샘플 또는 추가 자료 준비 경로 안내"]],checklist:["연락 가능한 업무용 이메일","제품 또는 참고 이미지","예상 수량","목표 수령일과 배송지","로고와 패키징 요구"],faqs:[["문의하면 바로 최종 견적을 받나요?","핵심 사양이 충분하면 빠르게 범위를 검토할 수 있지만 누락된 정보가 있으면 먼저 질문과 가정을 정리합니다."],["어떤 자료가 없으면 문의할 수 없나요?","모든 자료가 완성될 필요는 없습니다. 현재 알고 있는 내용과 불확실한 부분을 구분해 공유하면 됩니다."],["회신은 어디로 오나요?","제출한 업무용 이메일을 기본 연락처로 사용하며 필요한 경우 WhatsApp으로도 프로젝트 맥락을 이어갈 수 있습니다."]]}
};

function GuidePage({pageKey}){const c=guideContent[pageKey];return <main className="zhoni-page guide-page ko-page"><Header/><section className="guide-hero"><div><p>{c.label} · 구매 가이드</p><h1>{c.title}</h1><p>{c.intro}</p><small>실무 검토 · 구매자 체크리스트 · 자주 묻는 질문</small></div><img src={c.image} alt={c.label}/></section><section className="guide-intro"><p>BUYER REVIEW</p><h2>견적과 생산 전에 확인할 핵심 항목.</h2><p>아래 기준은 초기 검토를 위한 출발점입니다. 최종 조건과 허용 범위는 합의된 제품 사양과 프로젝트 범위에 따라 확인됩니다.</p></section><section className="guide-table"><table><thead><tr><th>검토 영역</th><th>실무 확인 내용</th></tr></thead><tbody>{c.rows.map(row=><tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td></tr>)}</tbody></table></section><section className="guide-decision"><div><p>프로젝트 준비</p><h2>같은 기준으로 비교할 수 있는 브리프를 만드세요.</h2><p>구체적인 정보는 불필요한 가정을 줄이고 제품, MOQ, 견적, 샘플과 일정의 실제 범위를 더 분명하게 만듭니다.</p></div><aside><p>CHECKLIST</p><h3>구매자가 준비할 내용</h3><ul>{c.checklist.map(v=><li key={v}>{v}</li>)}</ul></aside></section><section className="guide-faq"><p>자주 묻는 질문</p><h2>다음 결정을 위한 답변.</h2><div>{c.faqs.map(([q,a],i)=><article key={q}><b>{String(i+1).padStart(2,"0")}</b><h3>{q}</h3><p>{a}</p></article>)}</div></section><section className="guide-products"><p>연결된 프로젝트 경로</p><h2>정보를 실제 브리프로 연결하세요.</h2><div><a href="/ko/products/">제품군<Arrow/></a><a href="/ko/solutions/">Solutions<Arrow/></a><a href="/ko/our-process/">진행 과정<Arrow/></a><a href="/ko/request-a-quote/">프로젝트 문의<Arrow/></a></div></section><Footer/></main>}

export function KoreanProcurement({routeKey}){
  if(hubContent[routeKey]) return <HubPage pageKey={routeKey}/>;
  if(guideContent[routeKey]) return <GuidePage pageKey={routeKey}/>;
  return null;
}
