import { useState } from "react";
import { LanguageSwitcher } from "./locale.jsx";

const Arrow=()=> <span aria-hidden="true">↗</span>;
const WHATSAPP_URL=import.meta.env.VITE_WHATSAPP_URL??"https://wa.me/8617759190848";

function Header({active="guides"}){const [menu,setMenu]=useState(false);return <header className={`zhoni-header ko-header ${menu?"zhoni-header-open":""}`}><a className="zhoni-wordmark" href="/ko/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><button className="zhoni-menu" onClick={()=>setMenu(v=>!v)}>{menu?"닫기":"메뉴"}</button><nav><a href="/ko/products/">제품</a><a href="/ko/solutions/">솔루션</a><a className={active==="guides"?"active":""} href="/ko/guides/">구매 가이드</a><a href="/ko/our-process/">진행 과정</a><a href="/ko/faq/">FAQ</a><a href="/ko/about/">회사 소개</a></nav><LanguageSwitcher/><a className="zhoni-header-cta" href="/ko/request-a-quote/">프로젝트 문의 <Arrow/></a></header>}
function Footer(){return <footer className="site-footer"><div className="site-footer-main"><a className="zhoni-wordmark" href="/ko/"><strong>ZHONI</strong><small>CUSTOM GOLF MERCHANDISE</small></a><div className="site-footer-copy"><p>클럽, 골프대회, 기업과 브랜드를 위한 맞춤 골프용품 프로젝트.</p><span>제품 개발 · 브랜딩 · 기프트 · 품질 · 패키징 · 납품</span><div className="site-footer-contact"><b>직접 문의</b><a href="mailto:sales@zhonigolf.com">sales@zhonigolf.com</a><a href={WHATSAPP_URL}>WhatsApp +86 177 5919 0848 <Arrow/></a></div></div><nav><a href="/ko/products/">제품</a><a href="/ko/solutions/">솔루션</a><a href="/ko/guides/">구매 가이드</a><a href="/ko/first-order-guide/">첫 주문</a><a href="/ko/our-process/">진행 과정</a><a href="/ko/request-a-quote/">문의 <Arrow/></a></nav></div><div className="site-footer-base"><span>ZHONI · CUSTOM GOLF MERCHANDISE</span><span>운영 법인: Xiamen Jindongyu Trading Co., Ltd.</span></div></footer>}

const content={
  koGolfGiftGuide:{group:"기프트 선택",title:"맞춤 골프 선물은 제품보다 목적부터 선택하세요",intro:"좋은 골프 선물은 로고가 있는 물건이 아니라 수령자, 사용 장면과 전달 순간에 맞는 제품입니다.",image:"/assets/images/zhoni-product-gift-sets-v3.png",rows:[["수령 대상","고객, 회원, 선수, 임직원 또는 VIP"],["전달 목적","감사, 환영, 기념, 포상 또는 브랜드 경험"],["제품 방향","한 가지 실용 제품 또는 여러 제품의 세트"],["브랜드 강도","눈에 띄는 행사 로고 또는 절제된 기업 표현"],["전달 방식","현장 배포, 개별 배송 또는 프리미엄 패키지"]],check:["수령자와 인원","행사·프로그램 목적","예상 수량과 예산 방향","목표 수령일과 배송지","로고와 패키징 기대"],faq:[["한 가지 제품도 좋은 선물이 될 수 있나요?","가능합니다. 사용성이 높고 브랜드 적용이 적절한 핵심 제품 하나가 불필요한 구성품이 많은 세트보다 효과적일 수 있습니다."],["예산을 먼저 알려야 하나요?","정확한 금액이 아니어도 제품 수준과 패키징 방향을 판단할 수 있는 범위가 있으면 유용합니다."]],related:"/ko/custom-golf-gifts/"},
  koAudienceGiftGuide:{group:"기프트 선택",title:"받는 사람에 따라 골프 선물의 역할이 달라집니다",intro:"고객, 대회 참가자, 클럽 회원과 VIP는 같은 골프용품이라도 기대하는 실용성과 표현 수준이 다릅니다.",image:"/assets/images/zhoni-golf-tournament-gift-delivery-v2.png",rows:[["고객·파트너","관계와 브랜드 품격을 보여주는 절제된 구성"],["대회 참가자","현장에서 바로 쓰고 휴대하기 쉬운 제품"],["클럽 회원","반복 사용과 소속감을 고려한 일관된 제품"],["VIP·임원","소재, 마감과 개봉 경험이 분명한 세트"],["운영팀·자원봉사자","구분, 실용성과 배포 효율을 우선한 구성"]],check:["수령 그룹별 인원","각 그룹의 선물 역할","공통 제품과 차등 제품","로고 노출 수준","배포·배송 방식"],faq:[["모든 수령자에게 같은 선물을 줘야 하나요?","행사 정체성을 유지하면서 제품, 포장 또는 메시지 카드로 그룹별 역할을 구분할 수 있습니다."],["골프를 치지 않는 수령자도 고려할 수 있나요?","가능합니다. 일상에서도 사용할 수 있는 모자, 파우치, 타월 또는 선물형 액세서리를 검토할 수 있습니다."]],related:"/ko/solutions/"},
  koTournamentGuide:{group:"골프대회",title:"플레이어 팩은 참가자의 하루를 기준으로 구성하세요",intro:"등록 데스크에서 라운드, 시상과 귀가까지 참가자가 언제 제품을 받고 사용하는지 생각하면 구성이 명확해집니다.",image:"/assets/images/zhoni-golf-tournament-gift-delivery-v2.png",rows:[["등록·환영","쉽게 배포하고 바로 확인할 수 있는 패키징"],["라운드 전","모자, 타월, 볼 마커처럼 즉시 사용할 제품"],["플레이 중","휴대성과 날씨, 골프백 부착을 고려한 구성"],["시상·네트워킹","수상자, 스폰서와 VIP를 위한 별도 수준"],["행사 후","반복 사용하며 행사와 브랜드를 기억할 제품"]],check:["참가 인원과 그룹","행사 형식과 일정","현장 배포 위치","스폰서 로고 규칙","배송·보관 공간"],faq:[["플레이어 팩에 몇 개의 제품이 적당한가요?","개수보다 각 제품의 역할이 중요합니다. 한 가지 핵심 제품과 보조 액세서리 정도로도 충분히 일관된 팩을 만들 수 있습니다."],["대회 당일 조립해도 되나요?","누락과 배포 지연을 줄이려면 사전에 세트 구성과 수량 확인을 완료하는 것이 좋습니다."]],related:"/ko/solutions/golf-tournament-gifts/"},
  koCorporateGuide:{group:"기업 기프트",title:"기업 골프 선물은 관계와 브랜드 강도를 함께 조율합니다",intro:"고객 감사와 임직원 선물은 같은 제품이라도 로고 크기, 소재와 패키징의 적절한 수준이 다릅니다.",image:"/assets/images/zhoni-custom-golf-packaging-v2.png",rows:[["관계","신규 고객, 장기 파트너, 임원 또는 내부 팀"],["상황","감사, 계약 기념, 행사, 포상 또는 시즌 선물"],["제품 수준","실용 단품, 조합 세트 또는 프리미엄 박스"],["브랜드 표현","기업 로고, 공동 브랜딩과 개인 메시지"],["전달","행사 현장, 사무실 일괄 또는 개별 배송"]],check:["수령자 직급·관계","기업 브랜드 가이드","제품과 패키징 수준","카드 문구·개인화","배송지 수와 일정"],faq:[["기업 로고는 크게 넣는 것이 좋은가요?","고급 선물에서는 작고 정교한 표현이 더 적합할 수 있습니다. 사용 장면과 관계를 기준으로 결정하세요."],["여러 주소로 배송할 수 있나요?","가능 여부와 포장·주소 자료 형식은 프로젝트 범위와 목적지에 따라 사전에 검토해야 합니다."]],related:"/ko/solutions/corporate-golf-gifts/"},
  koHeadcoverMaterialsGuide:{group:"헤드커버 개발",title:"헤드커버 소재는 촉감, 구조와 로고를 함께 결정합니다",intro:"외관만 비교하지 말고 보호 성능, 형태 유지, 봉제와 브랜드 방식에 미치는 영향을 확인해야 합니다.",image:"/assets/images/zhoni-product-headcovers-v3.png",rows:[["PU·합성가죽","형태가 선명하고 디보싱·자수 등 선택 폭이 넓음"],["직물","색상과 촉감이 다양하며 캐주얼한 브랜드 표현"],["니트","부드럽고 전통적인 인상, 번호와 폼폼 구성 검토"],["혼합 소재","패널별 역할과 시각적 대비를 만들 수 있음"],["안감·충전","클럽 보호, 핏과 전체 두께에 직접 영향"]],check:["원하는 촉감과 형태","사용 빈도와 환경","로고 방식","클럽별 핏","관리·포장 조건"],faq:[["천연가죽이 항상 더 좋은가요?","가격과 인상은 높을 수 있지만 관리, 색상 일관성과 프로젝트 조건을 함께 고려해야 합니다."],["사진만으로 소재를 확정할 수 있나요?","질감과 두께가 중요하면 실제 스와치 또는 샘플 확인이 더 안전합니다."]],related:"/ko/custom-golf-headcovers/"},
  koHeadcoverTypesGuide:{group:"헤드커버 개발",title:"클럽 유형마다 필요한 구조와 핏이 다릅니다",intro:"드라이버, 페어웨이, 하이브리드와 퍼터를 같은 외관으로 맞추더라도 패턴과 사용 방식은 따로 검토해야 합니다.",image:"/assets/images/zhoni-product-headcovers-v3.png",rows:[["드라이버","큰 헤드, 넓은 로고 면과 안정적인 개구부"],["페어웨이","번호 표시와 드라이버와의 크기 구분"],["하이브리드","작은 형태, 클럽 식별과 세트 일관성"],["블레이드 퍼터","슬림한 핏과 잠금·보호 구조"],["말렛 퍼터","형태별 패턴, 넥 방향과 자석 위치"]],check:["클럽 유형별 수량","오른손·왼손 방향","번호 또는 라벨","잠금 방식","세트 패키징"],faq:[["한 패턴으로 모든 브랜드 클럽에 맞나요?","범용 범위는 가능하지만 특히 퍼터는 형태 차이가 커 대상 모델과 치수를 확인해야 합니다."],["세트마다 다른 색상을 넣을 수 있나요?","가능 여부와 MOQ 영향은 소재 색상과 유형별 수량 분할에 따라 달라집니다."]],related:"/ko/custom-golf-headcovers/"},
  koProductSpecificationGuide:{group:"제품 개발",title:"사양서는 참고 이미지를 생산 가능한 기준으로 바꿉니다",intro:"제품명만으로는 동일한 견적과 샘플을 만들 수 없습니다. 치수, 소재, 부품, 로고와 포장 기준을 문서화하세요.",image:"/assets/images/zhoni-material-direction-v1.png",rows:[["기본 정보","제품명, 용도, 버전과 담당자"],["치수·허용 범위","측정 위치, 단위와 핵심 허용 오차"],["소재·색상","재질, 중량·두께와 색상 기준"],["구조·부품","패널, 봉제, 자석, 지퍼, 버클과 금속"],["로고·포장","파일, 위치, 크기, 방식과 개별 포장"]],check:["치수 도면","소재 참고","부품 목록","로고 배치도","품질·포장 기준"],faq:[["사양서는 누가 작성하나요?","구매자가 목적과 필수 기준을 제공하고 공급업체와 함께 생산 가능한 세부 내용을 정리하는 방식이 실용적입니다."],["모든 치수에 허용 오차가 필요한가요?","핵심 기능과 외관에 영향을 주는 치수부터 우선 정의하는 것이 좋습니다."]],related:"/ko/first-order-guide/"},
  koSampleApprovalGuide:{group:"제품 개발",title:"샘플 승인은 보기 좋다는 확인보다 구체적이어야 합니다",intro:"승인 샘플은 대량 생산의 기준이 되므로 치수, 기능, 소재, 로고와 포장까지 기록해야 합니다.",image:"/assets/images/zhoni-quality-inspection-v1.png",rows:[["형태·치수","사양과 측정 위치, 핏과 대칭"],["소재·색상","촉감, 두께, 광택과 승인 색상"],["기능","개폐, 자석, 클립, 착용과 실제 사용"],["로고·마감","크기, 위치, 선명도, 봉제와 모서리"],["포장","구성, 라벨, 인서트와 보호 상태"]],check:["승인·수정·보류 구분","사진과 측정값 기록","수정 항목 번호화","재확인 필요 항목","승인자와 날짜"],faq:[["샘플 사진만 보고 승인해도 되나요?","색상, 촉감, 핏과 기능이 중요한 제품은 실물 확인이 더 적절할 수 있습니다."],["샘플 수정 후 다시 확인해야 하나요?","기능이나 외관에 중요한 수정이라면 변경 항목을 재확인하는 것이 안전합니다."]],related:"/ko/our-process/"},
  koCollectionPlanningGuide:{group:"컬렉션 개발",title:"제품을 늘리기보다 하나의 디자인 규칙을 만드세요",intro:"여러 골프 액세서리는 같은 로고만 넣는다고 컬렉션이 되지 않습니다. 대상, 역할과 공통 디자인 시스템이 필요합니다.",image:"/assets/images/zhoni-golf-collection-hero-v2.png",rows:[["공통 목적","대회, 회원 프로그램, 기업 선물 또는 판매 컬렉션"],["핵심 제품","프로젝트의 중심이 되는 한 가지 제품"],["보조 제품","사용 장면을 확장하는 액세서리"],["디자인 시스템","색상, 로고 크기, 소재와 금속 마감 규칙"],["패키징","제품 순서와 전달 순간을 완성하는 구조"]],check:["수령자와 목적","핵심 제품 선정","제품별 역할","공통·개별 디자인 요소","목표 가격과 수량"],faq:[["모든 제품 색상을 같게 해야 하나요?","동일 색상뿐 아니라 보완 색상과 반복되는 금속·로고 디테일로도 통일감을 만들 수 있습니다."],["제품 수는 많을수록 좋은가요?","아닙니다. 목적이 불분명한 구성품보다 역할이 분명한 소수 제품이 더 강한 경험을 만듭니다."]],related:"/ko/solutions/golf-club-member-programs/"},
  koHeadcoverLogoGuide:{group:"헤드커버 개발",title:"로고 위치는 평면 도안이 아니라 완성된 클럽 위에서 판단하세요",intro:"곡면, 봉제선과 개구부는 로고의 실제 가독성에 영향을 줍니다. 소재와 패널 구조를 먼저 확인하세요.",image:"/assets/images/zhoni-product-headcovers-v3.png",rows:[["전면 패널","가장 높은 가시성, 곡면 왜곡과 중심선 확인"],["측면 패널","보조 로고, 번호 또는 제품 구분"],["상단·넥","작은 심볼과 반복 디테일에 적합"],["자수·아플리케","질감과 색상 표현, 선 굵기 제한"],["디보싱·패치","절제된 표현 또는 복잡한 로고 대안"]],check:["완성 크기 표시","패널별 위치 도면","최소 선·글자","실·소재 색상","좌우 방향 확인"],faq:[["큰 로고가 더 선명한가요?","곡면과 패널 경계를 넘으면 오히려 왜곡될 수 있으므로 사용 가능한 면 안에서 비율을 조정해야 합니다."],["퍼터 커버도 같은 위치를 쓸 수 있나요?","형태와 개폐 방향이 달라 별도의 배치 검토가 필요합니다."]],related:"/ko/custom-golf-headcovers/"},
  koCapsMaterialsGuide:{group:"골프 모자 개발",title:"골프 모자 원단은 기후와 착용 시간을 기준으로 선택하세요",intro:"코튼의 촉감, 기능성 원단의 건조, 메시의 통기성은 각각 다른 사용 장면에 적합합니다.",image:"/assets/images/zhoni-product-caps-v3.png",rows:[["코튼 트윌","익숙한 촉감과 구조, 일상·기프트 용도"],["기능성 폴리에스터","경량, 건조와 장시간 라운드"],["메시","통기성, 패널 구조와 로고 면적 확인"],["혼방","촉감, 형태 유지와 관리의 균형"],["땀받이·안감","착용감, 흡수와 전체 품질 인상"]],check:["사용 지역과 계절","착용 시간","원하는 크라운 형태","세탁·관리 조건","자수·패치 방식"],faq:[["더운 지역에는 메시가 항상 좋은가요?","통기성은 좋지만 행사 격식, 로고 면적과 자외선 노출을 함께 고려해야 합니다."],["원단 색상을 Pantone으로 맞출 수 있나요?","재고 원단과 별도 염색 여부에 따라 가능 범위와 MOQ가 달라집니다."]],related:"/ko/custom-golf-caps/"},
  koCapsBrandingGuide:{group:"골프 모자 개발",title:"모자 로고는 전면만이 아니라 착용 시 전체 균형을 봐야 합니다",intro:"전면 자수, 측면 스폰서, 후면 텍스트와 패치는 크라운 구조와 봉제선 안에서 계획해야 합니다.",image:"/assets/images/zhoni-product-caps-v3.png",rows:[["전면 중앙","주 로고, 크라운 봉제선과 높이 확인"],["전면 오프셋","작은 심볼과 현대적인 비대칭 표현"],["측면","스폰서, 행사명 또는 보조 마크"],["후면","짧은 텍스트, URL 또는 작은 로고"],["자수·패치","평면, 입체, 직조·고무 패치의 디테일 차이"]],check:["위치별 로고 파일","완성 크기","평면·입체 여부","실 색상과 원단 대비","뒷면 잠금 방식"],faq:[["입체 자수에 작은 글자를 넣을 수 있나요?","가는 선과 작은 글자는 뭉개질 수 있어 평면 자수나 직조 패치를 검토하는 것이 좋습니다."],["측면 로고는 어디에나 넣을 수 있나요?","패널 봉제, 통기 구멍과 내부 테이프 위치를 피해서 배치해야 합니다."]],related:"/ko/custom-golf-caps/"},
  koProductDevelopmentBriefGuide:{group:"제품 개발",title:"제품 개발 브리프는 아이디어와 제약 조건을 함께 보여줘야 합니다",intro:"원하는 모습뿐 아니라 대상, 사용 환경, 수량, 일정과 반드시 지켜야 할 기준을 알려주세요.",image:"/assets/images/zhoni-golf-product-development-v2.png",rows:[["목표와 사용자","누가 어디에서 왜 사용하는지"],["제품 방향","기존 제품 수정 또는 신규 구조 개발"],["필수 사양","치수, 소재, 기능과 품질 기준"],["브랜드 자료","로고, 색상, 위치와 참고 이미지"],["상업 조건","예상 수량, 목표 일정, 패키징과 배송지"]],check:["한 문장의 프로젝트 목표","필수·선호 조건 구분","참고 이미지 설명","예상 수량 범위","의사결정자와 일정"],faq:[["스케치가 없어도 제품 개발을 시작할 수 있나요?","용도와 참고 이미지가 명확하면 초기 방향을 논의할 수 있지만 구조가 복잡할수록 치수와 도면이 필요합니다."],["예산을 공개해야 하나요?","필수는 아니지만 목표 수준과 맞지 않는 방향을 줄이기 위해 범위를 공유하는 것이 유용할 수 있습니다."]],related:"/ko/solutions/private-label-golf-collections/"},
  koTournamentGiftBudgetGuide:{group:"골프대회",title:"골프대회 기프트 예산은 제품 단가만으로 계획하지 마세요",intro:"로고, 샘플, 패키징, 조립, 운송과 현장 배포까지 포함해야 실제 프로젝트 예산이 보입니다.",image:"/assets/images/zhoni-golf-tournament-gift-delivery-v2.png",rows:[["수령 그룹","참가자, 스폰서, VIP와 수상자별 수량"],["제품 비용","핵심 제품과 보조 구성품"],["브랜딩·샘플","로고 방식, 시안과 확인 비용"],["패키징·조립","박스, 인서트, 카드와 세트 작업"],["운송·현장","국제 배송, 보관, 분류와 배포 준비"]],check:["그룹별 인원","총예산과 우선순위","필수 제품","포장 수준","예비 수량과 일정"],faq:[["모든 참가자에게 같은 예산을 써야 하나요?","행사 정체성을 유지하면서 VIP와 수상자 등 역할별로 제품 또는 포장 수준을 구분할 수 있습니다."],["예비 수량도 주문해야 하나요?","등록 변경, 손상과 현장 누락 가능성을 고려해 합리적인 예비 수량을 검토하는 것이 좋습니다."]],related:"/ko/solutions/golf-tournament-gifts/"},
  koPlayerPackGuide:{group:"골프대회",title:"좋은 플레이어 팩은 현장에서 바로 쓸 수 있습니다",intro:"참가자가 골프백에 넣고 이동하는 과정, 날씨와 라운드 중 필요를 기준으로 구성하세요.",image:"/assets/images/zhoni-product-gift-sets-v3.png",rows:[["핵심 제품","모자, 타월 또는 헤드커버 중 행사와 맞는 중심 제품"],["필드 액세서리","볼 마커, 디봇 툴과 파우치"],["정보 요소","일정 카드, 스폰서 메시지와 이름표"],["패키징","휴대, 등록 데스크 배포와 폐기 편의"],["예비 구성","현장 변경과 누락을 위한 여유 수량"]],check:["참가자 프로필","라운드 환경","배포 시간·장소","스폰서 로고","조립·보관 계획"],faq:[["박스가 꼭 필요한가요?","현장 이동이 많다면 파우치, 슬리브 또는 간결한 포장이 더 실용적일 수 있습니다."],["골프공을 포함해야 하나요?","브랜드, 규격과 플레이어 선호가 다양하므로 행사 목적과 제품 정책을 기준으로 결정하세요."]],related:"/ko/solutions/golf-tournament-gifts/"},
  koRecipientRolesGuide:{group:"골프대회",title:"참가자, 스폰서와 수상자는 서로 다른 선물 역할을 가집니다",intro:"수령자 역할을 먼저 나누면 제품 수준, 브랜드 노출과 전달 시점을 더 정확히 계획할 수 있습니다.",image:"/assets/images/zhoni-golf-tournament-gift-delivery-v2.png",rows:[["참가자","환영, 실용성과 행사 일체감"],["스폰서","관계 감사와 공동 브랜드 가시성"],["VIP·초청객","절제된 브랜딩과 높은 소재·포장 수준"],["수상자","성취와 기념성을 보여주는 차별화된 구성"],["운영팀","구분, 실용성과 현장 효율"]],check:["역할별 인원","공통·차등 제품","로고 우선순위","전달 시점","포장·라벨 구분"],faq:[["수상자 선물을 참가자 팩과 같이 만들어도 되나요?","공통 디자인을 유지하면서 핵심 제품, 색상 또는 패키징으로 수상자 경험을 차별화할 수 있습니다."],["스폰서 로고는 몇 개까지 넣을 수 있나요?","제품 면적과 가독성에 따라 달라지며 많은 로고는 카드나 패키징으로 분리하는 것이 더 적절할 수 있습니다."]],related:"/ko/solutions/golf-tournament-gifts/"},
  koPremiumGiftSetGuide:{group:"기프트 선택",title:"프리미엄 골프 기프트 세트는 제품 수보다 위계가 중요합니다",intro:"한 가지 주인공 제품, 유용한 보조 제품과 정돈된 패키징이 명확한 세트를 만듭니다.",image:"/assets/images/zhoni-product-gift-sets-v3.png",rows:[["핵심 제품","가치와 브랜드 인상을 이끄는 중심 제품"],["보조 제품","핵심 제품의 사용 장면을 확장하는 액세서리"],["소재·마감","제품 간 색상, 촉감과 금속 마감의 연결"],["브랜딩","크기와 위치를 통제한 일관된 표현"],["개봉 경험","제품 순서, 인서트, 카드와 보호"]],check:["수령자와 관계","핵심 제품 선정","제품별 역할","공통 디자인 규칙","패키징·배송 방식"],faq:[["프리미엄 세트에는 제품이 많아야 하나요?","아닙니다. 두세 개의 잘 선택된 제품과 좋은 패키징이 더 명확한 가치를 만들 수 있습니다."],["개인 이름을 넣을 수 있나요?","제품과 방식에 따라 가능하지만 데이터 관리, 추가 비용, 일정과 오류 확인 절차가 필요합니다."]],related:"/ko/solutions/corporate-golf-gifts/"},
  koEventBriefGuide:{group:"골프대회",title:"골프 이벤트 브리프에는 행사 정보와 제품 조건이 함께 있어야 합니다",intro:"행사명과 날짜만으로는 적절한 제품과 견적을 판단하기 어렵습니다. 수령자, 수량, 배포와 배송까지 정리하세요.",image:"/assets/images/zhoni-material-direction-v1.png",rows:[["행사 맥락","행사 유형, 장소, 날짜와 브랜드 목표"],["수령자","그룹별 인원과 골프 경험"],["제품 방향","필수 제품, 참고 이미지와 제외 사항"],["브랜딩·패키징","로고, 스폰서, 카드와 배포 방식"],["일정·배송","희망 수령일, 목적지와 현장 준비"]],check:["행사 일정표","그룹별 수량","브랜드·스폰서 파일","예산 우선순위","승인 담당자"],faq:[["제품이 정해지지 않아도 문의할 수 있나요?","가능합니다. 대상, 수량, 일정과 목적을 공유하면 적절한 제품 경로를 검토할 수 있습니다."],["행사일과 수령일은 왜 구분하나요?","내부 확인, 분류와 현장 운송을 위해 행사 전에 실제 물품을 받아야 하기 때문입니다."]],related:"/ko/solutions/golf-tournament-gifts/"},
  koQuoteComparisonGuide:{group:"첫 주문 & 견적",title:"맞춤 골프용품 견적은 같은 사양과 조건에서 비교하세요",intro:"숫자만 비교하면 소재, 로고, 샘플, 포장과 배송 범위의 차이를 놓칠 수 있습니다.",image:"/assets/images/zhoni-product-gift-sets-v3.png",rows:[["제품 사양","치수, 소재, 부품과 품질 기준이 같은지"],["MOQ·수량","총수량과 색상·사이즈별 분할 조건"],["브랜딩","위치, 크기, 방식과 색상 수 포함 범위"],["샘플·승인","비용, 수정 횟수와 생산 전 확인 단계"],["포장·배송","개별 포장, 카톤, 운송과 세금 범위"]],check:["동일 사양서 배포","포함·제외 항목 표","샘플 조건","결제·인도 조건","유효기간과 일정 가정"],faq:[["단가가 낮은 공급업체가 더 경쟁력 있나요?","동일한 품질, 포함 범위와 인도 조건인지 확인하기 전에는 판단하기 어렵습니다."],["견적에 관세와 세금이 포함되나요?","인도 조건과 목적지에 따라 다르므로 운송, 통관, 관세와 세금의 책임 주체를 명시적으로 확인해야 합니다."]],related:"/ko/guides/what-affects-a-custom-golf-merchandise-quote/"}
};

function Guide({pageKey}){const c=content[pageKey];return <main className="zhoni-page guide-page ko-page"><Header/><section className="guide-hero"><div><p>{c.group} · 구매 가이드</p><h1>{c.title}</h1><p>{c.intro}</p><small>의사결정 기준 · 체크리스트 · 구매 질문</small></div><img src={c.image} alt={c.title}/></section><section className="guide-intro"><p>PRACTICAL BUYER REVIEW</p><h2>실제 프로젝트 전에 확인할 항목.</h2><p>아래 내용은 초기 브리프와 공급업체 검토에 사용할 수 있습니다. 최종 제품, MOQ, 가격, 샘플, 품질과 일정은 합의된 프로젝트 범위에 따라 확인됩니다.</p></section><section className="guide-table"><table><thead><tr><th>검토 영역</th><th>구매 결정 기준</th></tr></thead><tbody>{c.rows.map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td></tr>)}</tbody></table></section><section className="guide-decision"><div><p>구매자 준비</p><h2>구체적인 정보가 불필요한 가정을 줄입니다.</h2><p>모든 조건을 처음부터 확정할 필요는 없습니다. 알고 있는 내용, 선호 조건과 반드시 지켜야 할 기준을 구분해 공유하세요.</p></div><aside><p>CHECKLIST</p><h3>브리프에 포함할 내용</h3><ul>{c.check.map(v=><li key={v}>{v}</li>)}</ul></aside></section><section className="guide-faq"><p>자주 묻는 질문</p><h2>다음 결정을 위한 현실적인 답변.</h2><div>{c.faq.map(([q,a],i)=><article key={q}><b>{String(i+1).padStart(2,"0")}</b><h3>{q}</h3><p>{a}</p></article>)}</div></section><section className="guide-products"><p>연결된 프로젝트 경로</p><h2>읽은 내용을 실제 브리프로 연결하세요.</h2><div><a href={c.related}>관련 제품 또는 솔루션<Arrow/></a><a href="/ko/products/">제품군<Arrow/></a><a href="/ko/our-process/">진행 과정<Arrow/></a><a href="/ko/request-a-quote/">프로젝트 문의<Arrow/></a></div></section><Footer/></main>}

function Capabilities(){const items=[["제품 방향","헤드커버, 모자, 타월, 액세서리와 패키징을 목적에 맞춰 검토합니다."],["브랜드 적용","자수, 인쇄, 디보싱, 패치와 금속 마감을 소재와 로고에 맞춥니다."],["기프트 세트","수령 대상과 전달 순간을 기준으로 제품 조합과 패키징을 구성합니다."],["샘플·품질","제품별 확인 단계, 승인 기준과 생산 전후 품질 항목을 정리합니다."],["패키징·출고","개별 포장, 기프트 박스, 카톤, 목적지와 인도 조건을 검토합니다."]];return <main className="zhoni-page capabilities-page ko-page"><Header active="capabilities"/><section className="capability-hero"><img src="/assets/images/zhoni-golf-collection-hero-v2.png" alt="ZHONI 맞춤 골프용품 컬렉션"/></section><section className="capability-intro"><div><p>CAPABILITIES</p><h1>제품부터 전달까지 연결하는 맞춤 골프 프로젝트.</h1><p>ZHONI는 단일 제품 또는 조합형 기프트 프로젝트에서 제품 방향, 브랜딩, 확인 절차, 패키징과 납품 준비를 함께 검토합니다.</p><div className="capability-list">{items.slice(0,4).map(([t,d])=><article key={t}><h2>{t}</h2><p>{d}</p></article>)}</div></div><aside><p>프로젝트 적합성</p><h2>문의 전에 준비하면 좋은 정보</h2><ul><li>수령 대상과 사용 목적</li><li>제품 또는 참고 이미지</li><li>예상 수량과 목표 수령일</li><li>로고와 브랜드 가이드</li><li>패키징과 배송지</li></ul><small>MOQ, 가격, 샘플, 일정과 인도 조건은 제품과 합의된 범위에 따라 검토됩니다.</small></aside></section><section className="guide-products"><p>지원 범위</p><h2>프로젝트의 핵심 연결 지점.</h2><div>{items.map(([t])=><a href="/ko/request-a-quote/" key={t}>{t}<Arrow/></a>)}</div></section><section className="capability-cta"><img src="/assets/golf-flag-cta.png" alt="골프 코스의 깃발"/><div><p>READY TO REVIEW YOUR PROJECT?</p><a href="/ko/request-a-quote/">프로젝트 브리프 보내기 <Arrow/></a></div></section><Footer/></main>}

export function KoreanFinalGuides({routeKey}){if(routeKey==="koCapabilities")return <Capabilities/>;if(content[routeKey])return <Guide pageKey={routeKey}/>;return null}
